// Class: ReadMLPTuned
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPTuned
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : ineuteli
Date           : Thu Nov 19 14:00:47 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.11.2.el6.x86_64 #1 SMP Wed Mar 26 09:39:43 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/ineuteli/phase2/CMSSW_5_3_24/src/Delphes/plots
Training events: 21448
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
HiddenLayers: "N+10" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
NCycles: "500" [Number of training cycles]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
bjet1Pt                       bjet1Pt                       bjet1Pt                       bjet1Pt                                                         'F'    [23.8701992035,1105.5402832]
bjet2Pt                       bjet2Pt                       bjet2Pt                       bjet2Pt                                                         'F'    [15.71296978,472.949127197]
DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                                                      'F'    [0.427045226097,457.230957031]
DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                                                      'F'    [0.423246353865,769.836181641]
M_bb_closest                  M_bb_closest                  M_bb_closest                  M_bb_closest                                                    'F'    [8.52508640289,3205.42749023]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPTuned : public IClassifierReader {

 public:

   // constructor
   ReadMLPTuned( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPTuned" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "bjet1Pt", "bjet2Pt", "DeltaR_j2l", "DeltaR_b2l", "M_bb_closest" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPTuned() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPTuned::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.338779455269023;
   fWeightMatrix0to1[1][0] = 1.99473878798013;
   fWeightMatrix0to1[2][0] = -0.31637625922509;
   fWeightMatrix0to1[3][0] = 3.60112918982387;
   fWeightMatrix0to1[4][0] = -1.10687427267699;
   fWeightMatrix0to1[5][0] = -1.96795881577535;
   fWeightMatrix0to1[6][0] = -0.611510885827322;
   fWeightMatrix0to1[7][0] = 2.88226836760322;
   fWeightMatrix0to1[8][0] = -1.17299851557176;
   fWeightMatrix0to1[9][0] = -0.390082372582537;
   fWeightMatrix0to1[10][0] = -0.893725926819705;
   fWeightMatrix0to1[11][0] = -0.372479643825627;
   fWeightMatrix0to1[12][0] = -3.6086112029754;
   fWeightMatrix0to1[13][0] = -0.58508430962465;
   fWeightMatrix0to1[14][0] = -0.977260317308143;
   fWeightMatrix0to1[0][1] = 0.77766032157633;
   fWeightMatrix0to1[1][1] = -0.421848830893876;
   fWeightMatrix0to1[2][1] = 0.855561595809291;
   fWeightMatrix0to1[3][1] = 1.88219391877037;
   fWeightMatrix0to1[4][1] = -0.7066865329394;
   fWeightMatrix0to1[5][1] = 0.231880260737064;
   fWeightMatrix0to1[6][1] = -0.34899869417122;
   fWeightMatrix0to1[7][1] = 0.318704361425118;
   fWeightMatrix0to1[8][1] = -1.79694813969979;
   fWeightMatrix0to1[9][1] = -0.406496694443329;
   fWeightMatrix0to1[10][1] = 0.537237878045957;
   fWeightMatrix0to1[11][1] = 1.17576724686952;
   fWeightMatrix0to1[12][1] = -1.87661769865693;
   fWeightMatrix0to1[13][1] = -1.85118983727788;
   fWeightMatrix0to1[14][1] = -0.329037311962546;
   fWeightMatrix0to1[0][2] = 1.11022902594672;
   fWeightMatrix0to1[1][2] = 1.64557866136102;
   fWeightMatrix0to1[2][2] = -1.48787687830976;
   fWeightMatrix0to1[3][2] = -0.640371894110629;
   fWeightMatrix0to1[4][2] = -0.736428920163597;
   fWeightMatrix0to1[5][2] = -0.977657949098931;
   fWeightMatrix0to1[6][2] = -1.25769941537491;
   fWeightMatrix0to1[7][2] = 0.998517315779396;
   fWeightMatrix0to1[8][2] = -1.85691931672393;
   fWeightMatrix0to1[9][2] = 1.70151646313535;
   fWeightMatrix0to1[10][2] = 2.9872165306372;
   fWeightMatrix0to1[11][2] = 2.69458772910079;
   fWeightMatrix0to1[12][2] = 4.15410887214161;
   fWeightMatrix0to1[13][2] = 1.63911213556766;
   fWeightMatrix0to1[14][2] = -1.31191287964925;
   fWeightMatrix0to1[0][3] = -1.09366015073348;
   fWeightMatrix0to1[1][3] = 0.760123215013716;
   fWeightMatrix0to1[2][3] = -0.545137608542648;
   fWeightMatrix0to1[3][3] = 0.52267508312532;
   fWeightMatrix0to1[4][3] = -1.3024320698532;
   fWeightMatrix0to1[5][3] = 3.54536003040426;
   fWeightMatrix0to1[6][3] = 1.35832042397578;
   fWeightMatrix0to1[7][3] = -4.05135725128026;
   fWeightMatrix0to1[8][3] = -1.01977666953841;
   fWeightMatrix0to1[9][3] = -1.49103840635673;
   fWeightMatrix0to1[10][3] = -0.100398912537025;
   fWeightMatrix0to1[11][3] = -0.217008633079517;
   fWeightMatrix0to1[12][3] = -2.98981596884827;
   fWeightMatrix0to1[13][3] = 1.13382520993276;
   fWeightMatrix0to1[14][3] = -0.0965616115417102;
   fWeightMatrix0to1[0][4] = -2.25928092122741;
   fWeightMatrix0to1[1][4] = 0.361288423187612;
   fWeightMatrix0to1[2][4] = 0.00782181496617538;
   fWeightMatrix0to1[3][4] = 0.392352657020543;
   fWeightMatrix0to1[4][4] = 10.5605188627159;
   fWeightMatrix0to1[5][4] = 0.159875234011283;
   fWeightMatrix0to1[6][4] = 1.32420527822202;
   fWeightMatrix0to1[7][4] = 0.472876234214891;
   fWeightMatrix0to1[8][4] = 6.91397287601301;
   fWeightMatrix0to1[9][4] = -0.530312357072855;
   fWeightMatrix0to1[10][4] = -3.05724747000498;
   fWeightMatrix0to1[11][4] = -2.48701501881067;
   fWeightMatrix0to1[12][4] = 3.24430489756887;
   fWeightMatrix0to1[13][4] = 1.05565397615281;
   fWeightMatrix0to1[14][4] = 1.48365161705762;
   fWeightMatrix0to1[0][5] = -1.06568588856494;
   fWeightMatrix0to1[1][5] = -1.91589610493637;
   fWeightMatrix0to1[2][5] = -1.45941107261297;
   fWeightMatrix0to1[3][5] = 4.22543882952716;
   fWeightMatrix0to1[4][5] = 6.04518763392916;
   fWeightMatrix0to1[5][5] = 1.56066656082817;
   fWeightMatrix0to1[6][5] = 0.592128119796022;
   fWeightMatrix0to1[7][5] = 1.38713394446852;
   fWeightMatrix0to1[8][5] = 2.69160666849487;
   fWeightMatrix0to1[9][5] = -1.10115082619967;
   fWeightMatrix0to1[10][5] = -0.281090657472963;
   fWeightMatrix0to1[11][5] = 1.09289481677896;
   fWeightMatrix0to1[12][5] = -0.108547932802246;
   fWeightMatrix0to1[13][5] = -1.50910747165145;
   fWeightMatrix0to1[14][5] = -1.27826745209499;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.238776908420223;
   fWeightMatrix1to2[0][1] = 0.185431752344023;
   fWeightMatrix1to2[0][2] = 0.33004118361232;
   fWeightMatrix1to2[0][3] = -0.615885233523556;
   fWeightMatrix1to2[0][4] = -0.817982145274907;
   fWeightMatrix1to2[0][5] = 1.00784130674564;
   fWeightMatrix1to2[0][6] = 0.286926207355828;
   fWeightMatrix1to2[0][7] = 1.61194561969945;
   fWeightMatrix1to2[0][8] = -0.42845795525829;
   fWeightMatrix1to2[0][9] = -0.185032405876471;
   fWeightMatrix1to2[0][10] = -0.831176686384528;
   fWeightMatrix1to2[0][11] = -0.679345910679645;
   fWeightMatrix1to2[0][12] = -1.00694247650164;
   fWeightMatrix1to2[0][13] = 1.96499031946408;
   fWeightMatrix1to2[0][14] = 0.364418758161165;
   fWeightMatrix1to2[0][15] = 1.30997099514474;
}

inline double ReadMLPTuned::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPTuned::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPTuned::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPTuned::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPTuned::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 23.8701992035;
   fMax_1[0][0] = 904.02545166;
   fMin_1[1][0] = 27.4655246735;
   fMax_1[1][0] = 1105.5402832;
   fMin_1[2][0] = 23.8701992035;
   fMax_1[2][0] = 1105.5402832;
   fMin_1[0][1] = 20.0053157806;
   fMax_1[0][1] = 358.230773926;
   fMin_1[1][1] = 15.71296978;
   fMax_1[1][1] = 472.949127197;
   fMin_1[2][1] = 15.71296978;
   fMax_1[2][1] = 472.949127197;
   fMin_1[0][2] = 0.427045226097;
   fMax_1[0][2] = 457.230957031;
   fMin_1[1][2] = 0.505508899689;
   fMax_1[1][2] = 339.015960693;
   fMin_1[2][2] = 0.427045226097;
   fMax_1[2][2] = 457.230957031;
   fMin_1[0][3] = 0.548147320747;
   fMax_1[0][3] = 769.836181641;
   fMin_1[1][3] = 0.423246353865;
   fMax_1[1][3] = 631.76385498;
   fMin_1[2][3] = 0.423246353865;
   fMax_1[2][3] = 769.836181641;
   fMin_1[0][4] = 8.52508640289;
   fMax_1[0][4] = 1460.97070312;
   fMin_1[1][4] = 12.8134212494;
   fMax_1[1][4] = 3205.42749023;
   fMin_1[2][4] = 8.52508640289;
   fMax_1[2][4] = 3205.42749023;
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
