// Class: ReadMLPTuned
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPTuned
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : ineuteli
Date           : Thu Nov 26 21:29:30 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.11.2.el6.x86_64 #1 SMP Wed Mar 26 09:39:43 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/ineuteli/phase2/CMSSW_5_3_24/src/Delphes/plots
Training events: 33424
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
HiddenLayers: "N+10" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
NCycles: "500" [Number of training cycles]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                                                      'F'    [0.514531254768,5.80796384811]
DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                                                      'F'    [0.331118583679,4.68913269043]
DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                                                      'F'    [0.293443262577,5.25155687332]
DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                                                      'F'    [0.260792672634,5.09150838852]
DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                                                      'F'    [0.354219049215,6.81951332092]
M_bb_closest                  M_bb_closest                  M_bb_closest                  M_bb_closest                                                    'F'    [8.52508640289,3205.42749023]
M_jjb_leading                 M_jjb_leading                 M_jjb_leading                 M_jjb_leading                                                   'F'    [35.0392456055,3575.52978516]
M_blnu                        M_blnu                        M_blnu                        M_blnu                                                          'F'    [83.4304733276,2969.04516602]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPTuned : public IClassifierReader {

 public:

   // constructor
   ReadMLPTuned( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPTuned" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "DeltaR_b1l", "DeltaR_b2l", "DeltaR_bb1", "DeltaR_j1l", "DeltaR_j2l", "M_bb_closest", "M_jjb_leading", "M_blnu" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPTuned() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[19][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][19];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPTuned::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 19; fWeights[1] = new double[19]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 1.07740270510211;
   fWeightMatrix0to1[1][0] = 0.657138148429727;
   fWeightMatrix0to1[2][0] = 0.446933473708156;
   fWeightMatrix0to1[3][0] = 0.823620528414938;
   fWeightMatrix0to1[4][0] = -0.772681257273686;
   fWeightMatrix0to1[5][0] = 0.338354923182835;
   fWeightMatrix0to1[6][0] = -0.774562668577678;
   fWeightMatrix0to1[7][0] = 0.202529129957955;
   fWeightMatrix0to1[8][0] = -1.05215715016826;
   fWeightMatrix0to1[9][0] = 0.10279527159865;
   fWeightMatrix0to1[10][0] = -0.13328444852686;
   fWeightMatrix0to1[11][0] = -0.406184864729913;
   fWeightMatrix0to1[12][0] = -2.71876690142882;
   fWeightMatrix0to1[13][0] = -0.536902685031639;
   fWeightMatrix0to1[14][0] = -0.544870818209835;
   fWeightMatrix0to1[15][0] = 1.09542166376293;
   fWeightMatrix0to1[16][0] = -0.257369130265093;
   fWeightMatrix0to1[17][0] = 0.733369357841344;
   fWeightMatrix0to1[0][1] = 0.44795612501377;
   fWeightMatrix0to1[1][1] = -0.918231839830371;
   fWeightMatrix0to1[2][1] = -0.280555275401373;
   fWeightMatrix0to1[3][1] = -0.288443109628991;
   fWeightMatrix0to1[4][1] = 0.470904099750996;
   fWeightMatrix0to1[5][1] = -0.722865134695874;
   fWeightMatrix0to1[6][1] = -1.43240230389004;
   fWeightMatrix0to1[7][1] = -0.112505321250025;
   fWeightMatrix0to1[8][1] = 1.08988598495963;
   fWeightMatrix0to1[9][1] = -0.598404203556626;
   fWeightMatrix0to1[10][1] = -0.374937219600588;
   fWeightMatrix0to1[11][1] = 0.272901592042686;
   fWeightMatrix0to1[12][1] = -0.0118977097653451;
   fWeightMatrix0to1[13][1] = 1.56345834860285;
   fWeightMatrix0to1[14][1] = -0.336210252942704;
   fWeightMatrix0to1[15][1] = 0.303832505367485;
   fWeightMatrix0to1[16][1] = 0.580967678602216;
   fWeightMatrix0to1[17][1] = -0.916056479181788;
   fWeightMatrix0to1[0][2] = -0.406272011747264;
   fWeightMatrix0to1[1][2] = 3.68787174876907;
   fWeightMatrix0to1[2][2] = -0.471789689199003;
   fWeightMatrix0to1[3][2] = -0.261382525324418;
   fWeightMatrix0to1[4][2] = 0.543303878695488;
   fWeightMatrix0to1[5][2] = 0.376763675530107;
   fWeightMatrix0to1[6][2] = 3.45198818703505;
   fWeightMatrix0to1[7][2] = -0.230280448229066;
   fWeightMatrix0to1[8][2] = -0.172011880729622;
   fWeightMatrix0to1[9][2] = -0.503297227631206;
   fWeightMatrix0to1[10][2] = 0.524151128770484;
   fWeightMatrix0to1[11][2] = 0.325846740137191;
   fWeightMatrix0to1[12][2] = 0.487095260045511;
   fWeightMatrix0to1[13][2] = 1.28087320886284;
   fWeightMatrix0to1[14][2] = 0.286949721134514;
   fWeightMatrix0to1[15][2] = 1.43244759673218;
   fWeightMatrix0to1[16][2] = -1.45179528008256;
   fWeightMatrix0to1[17][2] = 3.43494315293692;
   fWeightMatrix0to1[0][3] = -3.38488392958783;
   fWeightMatrix0to1[1][3] = -0.0287708124073781;
   fWeightMatrix0to1[2][3] = -0.465890084803745;
   fWeightMatrix0to1[3][3] = -0.501992625061993;
   fWeightMatrix0to1[4][3] = 0.567427212328917;
   fWeightMatrix0to1[5][3] = 0.760044910634495;
   fWeightMatrix0to1[6][3] = 0.614206191841625;
   fWeightMatrix0to1[7][3] = -0.194415318583757;
   fWeightMatrix0to1[8][3] = -0.584415862266274;
   fWeightMatrix0to1[9][3] = -0.324113335549458;
   fWeightMatrix0to1[10][3] = -0.0326726511982371;
   fWeightMatrix0to1[11][3] = -0.567070671982773;
   fWeightMatrix0to1[12][3] = 0.314726211923575;
   fWeightMatrix0to1[13][3] = -0.725387853927039;
   fWeightMatrix0to1[14][3] = 0.109678537684073;
   fWeightMatrix0to1[15][3] = -0.770036376623576;
   fWeightMatrix0to1[16][3] = -0.97789601179673;
   fWeightMatrix0to1[17][3] = -0.192046479651913;
   fWeightMatrix0to1[0][4] = -0.32493202317959;
   fWeightMatrix0to1[1][4] = -0.498329149252326;
   fWeightMatrix0to1[2][4] = 0.527257973447865;
   fWeightMatrix0to1[3][4] = 0.27122767344326;
   fWeightMatrix0to1[4][4] = -0.600133600198459;
   fWeightMatrix0to1[5][4] = -2.6810468196557;
   fWeightMatrix0to1[6][4] = -0.0959796578452144;
   fWeightMatrix0to1[7][4] = -0.365447677620048;
   fWeightMatrix0to1[8][4] = 1.41502942812012;
   fWeightMatrix0to1[9][4] = 0.143778352197693;
   fWeightMatrix0to1[10][4] = 1.7358271258819;
   fWeightMatrix0to1[11][4] = -0.545229402294495;
   fWeightMatrix0to1[12][4] = 0.249229183811848;
   fWeightMatrix0to1[13][4] = 0.0635833803028688;
   fWeightMatrix0to1[14][4] = -0.13125166436409;
   fWeightMatrix0to1[15][4] = -1.01359964031956;
   fWeightMatrix0to1[16][4] = -1.63164598674031;
   fWeightMatrix0to1[17][4] = -0.397267391382583;
   fWeightMatrix0to1[0][5] = 0.265313012287743;
   fWeightMatrix0to1[1][5] = 2.99914067178326;
   fWeightMatrix0to1[2][5] = 2.1305271407433;
   fWeightMatrix0to1[3][5] = -2.04938083201565;
   fWeightMatrix0to1[4][5] = -0.742287586857565;
   fWeightMatrix0to1[5][5] = 1.57253431589574;
   fWeightMatrix0to1[6][5] = 0.219460355162283;
   fWeightMatrix0to1[7][5] = -1.54299589011421;
   fWeightMatrix0to1[8][5] = -1.21385257940216;
   fWeightMatrix0to1[9][5] = -0.230102863396285;
   fWeightMatrix0to1[10][5] = -2.73738107801459;
   fWeightMatrix0to1[11][5] = -1.63379025185384;
   fWeightMatrix0to1[12][5] = 0.340246979985274;
   fWeightMatrix0to1[13][5] = 1.82937125765976;
   fWeightMatrix0to1[14][5] = -0.706993358457332;
   fWeightMatrix0to1[15][5] = 1.81422676854523;
   fWeightMatrix0to1[16][5] = -0.359039483338479;
   fWeightMatrix0to1[17][5] = -4.45442171897959;
   fWeightMatrix0to1[0][6] = 0.789484180431574;
   fWeightMatrix0to1[1][6] = 2.20269634787892;
   fWeightMatrix0to1[2][6] = -0.893090991376283;
   fWeightMatrix0to1[3][6] = 0.127177959481428;
   fWeightMatrix0to1[4][6] = 0.23932850590263;
   fWeightMatrix0to1[5][6] = -0.626844585082371;
   fWeightMatrix0to1[6][6] = 0.545320096979608;
   fWeightMatrix0to1[7][6] = 3.39400278012886;
   fWeightMatrix0to1[8][6] = -0.184197151984394;
   fWeightMatrix0to1[9][6] = -0.827399802978061;
   fWeightMatrix0to1[10][6] = 0.47752266484314;
   fWeightMatrix0to1[11][6] = -1.10504838659104;
   fWeightMatrix0to1[12][6] = -2.18383822922744;
   fWeightMatrix0to1[13][6] = 0.608889331809948;
   fWeightMatrix0to1[14][6] = 0.256416340860698;
   fWeightMatrix0to1[15][6] = 1.23525123497155;
   fWeightMatrix0to1[16][6] = 1.18986206118444;
   fWeightMatrix0to1[17][6] = 2.18055456161496;
   fWeightMatrix0to1[0][7] = -0.784961851923294;
   fWeightMatrix0to1[1][7] = 1.00096218753967;
   fWeightMatrix0to1[2][7] = -1.24726221436076;
   fWeightMatrix0to1[3][7] = 1.1403579290265;
   fWeightMatrix0to1[4][7] = -0.0720270117542902;
   fWeightMatrix0to1[5][7] = -0.964963280489928;
   fWeightMatrix0to1[6][7] = -1.8188628750519;
   fWeightMatrix0to1[7][7] = -1.80595866116151;
   fWeightMatrix0to1[8][7] = -0.696168998345869;
   fWeightMatrix0to1[9][7] = 0.429221560875077;
   fWeightMatrix0to1[10][7] = -0.107734791222882;
   fWeightMatrix0to1[11][7] = -1.63823185041366;
   fWeightMatrix0to1[12][7] = 0.806027930747021;
   fWeightMatrix0to1[13][7] = 1.58136283317614;
   fWeightMatrix0to1[14][7] = 2.12695659442144;
   fWeightMatrix0to1[15][7] = 0.147883463814538;
   fWeightMatrix0to1[16][7] = -0.883423381989608;
   fWeightMatrix0to1[17][7] = 0.00334062530800021;
   fWeightMatrix0to1[0][8] = -2.69215553437174;
   fWeightMatrix0to1[1][8] = 8.21059527200329;
   fWeightMatrix0to1[2][8] = -0.159996079444543;
   fWeightMatrix0to1[3][8] = -1.11723292877107;
   fWeightMatrix0to1[4][8] = -0.223343876731736;
   fWeightMatrix0to1[5][8] = -1.836472296913;
   fWeightMatrix0to1[6][8] = 0.312049299024636;
   fWeightMatrix0to1[7][8] = -0.473562898908352;
   fWeightMatrix0to1[8][8] = 1.94006599738012;
   fWeightMatrix0to1[9][8] = -1.03450149348936;
   fWeightMatrix0to1[10][8] = -1.83994094001099;
   fWeightMatrix0to1[11][8] = 0.336212351634393;
   fWeightMatrix0to1[12][8] = 0.52649747006811;
   fWeightMatrix0to1[13][8] = -0.155651725934202;
   fWeightMatrix0to1[14][8] = 1.04998345766888;
   fWeightMatrix0to1[15][8] = -1.43042501138308;
   fWeightMatrix0to1[16][8] = 1.07081607598814;
   fWeightMatrix0to1[17][8] = 0.00485254768706413;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.301440899089092;
   fWeightMatrix1to2[0][1] = 1.02026095139996;
   fWeightMatrix1to2[0][2] = 0.0119520048967692;
   fWeightMatrix1to2[0][3] = 0.227067849190816;
   fWeightMatrix1to2[0][4] = 0.104999667391029;
   fWeightMatrix1to2[0][5] = 0.253462254493892;
   fWeightMatrix1to2[0][6] = -0.207238116934935;
   fWeightMatrix1to2[0][7] = 0.139995669916582;
   fWeightMatrix1to2[0][8] = 1.16621364081329;
   fWeightMatrix1to2[0][9] = 0.0293608837995202;
   fWeightMatrix1to2[0][10] = 0.251253497158399;
   fWeightMatrix1to2[0][11] = 1.42413870365343;
   fWeightMatrix1to2[0][12] = 0.250922434913773;
   fWeightMatrix1to2[0][13] = 0.217242676858993;
   fWeightMatrix1to2[0][14] = -0.204541994519473;
   fWeightMatrix1to2[0][15] = 0.390129656976314;
   fWeightMatrix1to2[0][16] = -0.0100161277040644;
   fWeightMatrix1to2[0][17] = -0.997315795309801;
   fWeightMatrix1to2[0][18] = -1.37701630323466;
}

inline double ReadMLPTuned::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPTuned::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPTuned::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPTuned::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPTuned::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.63454002142;
   fMax_1[0][0] = 5.7385263443;
   fMin_1[1][0] = 0.514531254768;
   fMax_1[1][0] = 5.80796384811;
   fMin_1[2][0] = 0.514531254768;
   fMax_1[2][0] = 5.80796384811;
   fMin_1[0][1] = 0.335011512041;
   fMax_1[0][1] = 4.68913269043;
   fMin_1[1][1] = 0.331118583679;
   fMax_1[1][1] = 4.59567117691;
   fMin_1[2][1] = 0.331118583679;
   fMax_1[2][1] = 4.68913269043;
   fMin_1[0][2] = 0.293443262577;
   fMax_1[0][2] = 5.23438882828;
   fMin_1[1][2] = 0.318634212017;
   fMax_1[1][2] = 5.25155687332;
   fMin_1[2][2] = 0.293443262577;
   fMax_1[2][2] = 5.25155687332;
   fMin_1[0][3] = 0.260792672634;
   fMax_1[0][3] = 4.59489059448;
   fMin_1[1][3] = 0.299051195383;
   fMax_1[1][3] = 5.09150838852;
   fMin_1[2][3] = 0.260792672634;
   fMax_1[2][3] = 5.09150838852;
   fMin_1[0][4] = 0.354219049215;
   fMax_1[0][4] = 5.93411493301;
   fMin_1[1][4] = 0.460506469011;
   fMax_1[1][4] = 6.81951332092;
   fMin_1[2][4] = 0.354219049215;
   fMax_1[2][4] = 6.81951332092;
   fMin_1[0][5] = 8.52508640289;
   fMax_1[0][5] = 2569.79931641;
   fMin_1[1][5] = 11.2259721756;
   fMax_1[1][5] = 3205.42749023;
   fMin_1[2][5] = 8.52508640289;
   fMax_1[2][5] = 3205.42749023;
   fMin_1[0][6] = 35.0392456055;
   fMax_1[0][6] = 3031.91503906;
   fMin_1[1][6] = 38.9231910706;
   fMax_1[1][6] = 3575.52978516;
   fMin_1[2][6] = 35.0392456055;
   fMax_1[2][6] = 3575.52978516;
   fMin_1[0][7] = 87.2694320679;
   fMax_1[0][7] = 2969.04516602;
   fMin_1[1][7] = 83.4304733276;
   fMax_1[1][7] = 2481.73486328;
   fMin_1[2][7] = 83.4304733276;
   fMax_1[2][7] = 2969.04516602;
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
