// Class: ReadMLPTuned
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPTuned
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : ineuteli
Date           : Thu Nov 26 21:15:43 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.11.2.el6.x86_64 #1 SMP Wed Mar 26 09:39:43 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/ineuteli/phase2/CMSSW_5_3_24/src/Delphes/plots
Training events: 33424
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
HiddenLayers: "N+10" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
NCycles: "500" [Number of training cycles]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 20
Njets20                       Njets20                       Njets20                       Njets20                                                         'F'    [4,10]
Nbjets30                      Nbjets30                      Nbjets30                      Nbjets30                                                        'F'    [2,6]
jet1Pt                        jet1Pt                        jet1Pt                        jet1Pt                                                          'F'    [20.3061256409,1141.5065918]
jet2Pt                        jet2Pt                        jet2Pt                        jet2Pt                                                          'F'    [20.0002479553,730.360351562]
bjet1Pt                       bjet1Pt                       bjet1Pt                       bjet1Pt                                                         'F'    [30.6644649506,1190.31469727]
bjet2Pt                       bjet2Pt                       bjet2Pt                       bjet2Pt                                                         'F'    [30.001663208,613.805419922]
leptonPt                      leptonPt                      leptonPt                      leptonPt                                                        'F'    [20.0020217896,743.405090332]
MET                           MET                           MET                           MET                                                             'F'    [20.003408432,855.639770508]
DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                                                      'F'    [0.260792672634,5.09150838852]
DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                                                      'F'    [0.354219049215,6.81951332092]
DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                                                      'F'    [0.514531254768,5.80796384811]
DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                                                      'F'    [0.331118583679,4.68913269043]
DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                                                      'F'    [0.293443262577,5.25155687332]
DeltaR_jjl_leading            DeltaR_jjl_leading            DeltaR_jjl_leading            DeltaR_jjl_leading                                              'F'    [0.0118044847623,7.40591907501]
DeltaPhi_METl                 DeltaPhi_METl                 DeltaPhi_METl                 DeltaPhi_METl                                                   'F'    [2.95639038086e-05,6.28109359741]
M_bb_closest                  M_bb_closest                  M_bb_closest                  M_bb_closest                                                    'F'    [8.52508640289,3205.42749023]
M_jjb_leading                 M_jjb_leading                 M_jjb_leading                 M_jjb_leading                                                   'F'    [35.0392456055,3575.52978516]
M_blnu                        M_blnu                        M_blnu                        M_blnu                                                          'F'    [83.4304733276,2969.04516602]
MT_lnu                        MT_lnu                        MT_lnu                        MT_lnu                                                          'F'    [0.00157363095786,460.327148438]
MT_jjlnu                      MT_jjlnu                      MT_jjlnu                      MT_jjlnu                                                        'F'    [0.000171629610122,1665.87695312]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPTuned : public IClassifierReader {

 public:

   // constructor
   ReadMLPTuned( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPTuned" ),
        fNvars( 20 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Njets20", "Nbjets30", "jet1Pt", "jet2Pt", "bjet1Pt", "bjet2Pt", "leptonPt", "MET", "DeltaR_j1l", "DeltaR_j2l", "DeltaR_b1l", "DeltaR_b2l", "DeltaR_bb1", "DeltaR_jjl_leading", "DeltaPhi_METl", "M_bb_closest", "M_jjb_leading", "M_blnu", "MT_lnu", "MT_jjlnu" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 0.99999988079071;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 0.99999988079071;
      fVmin[16] = -1;
      fVmax[16] = 1;
      fVmin[17] = -1;
      fVmax[17] = 1;
      fVmin[18] = -1;
      fVmax[18] = 1;
      fVmin[19] = -1;
      fVmax[19] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPTuned() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][20];
   double fMax_1[3][20];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[20];
   double fVmax[20];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[20];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[31][21];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][31];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPTuned::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 21; fWeights[0] = new double[21]; 
   fLayerSize[1] = 31; fWeights[1] = new double[31]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.182355189544908;
   fWeightMatrix0to1[1][0] = -0.108700574328611;
   fWeightMatrix0to1[2][0] = -0.125597851655397;
   fWeightMatrix0to1[3][0] = 0.130040552974927;
   fWeightMatrix0to1[4][0] = -0.808509834436756;
   fWeightMatrix0to1[5][0] = -0.0335808718489499;
   fWeightMatrix0to1[6][0] = 0.053339900712943;
   fWeightMatrix0to1[7][0] = 0.227047125592434;
   fWeightMatrix0to1[8][0] = -1.28811551554598;
   fWeightMatrix0to1[9][0] = -1.17488200905726;
   fWeightMatrix0to1[10][0] = -0.0205912915927209;
   fWeightMatrix0to1[11][0] = -0.314161924089771;
   fWeightMatrix0to1[12][0] = -0.40933336857343;
   fWeightMatrix0to1[13][0] = 0.503584109458047;
   fWeightMatrix0to1[14][0] = -0.538554415423894;
   fWeightMatrix0to1[15][0] = 0.612103740946113;
   fWeightMatrix0to1[16][0] = -0.317247093279448;
   fWeightMatrix0to1[17][0] = 1.05670541159961;
   fWeightMatrix0to1[18][0] = -0.084155521946491;
   fWeightMatrix0to1[19][0] = -0.141983422052606;
   fWeightMatrix0to1[20][0] = -0.0573717618227811;
   fWeightMatrix0to1[21][0] = -0.309717732822145;
   fWeightMatrix0to1[22][0] = -0.0822486503301509;
   fWeightMatrix0to1[23][0] = 0.142386278187034;
   fWeightMatrix0to1[24][0] = 0.0271146498930255;
   fWeightMatrix0to1[25][0] = -0.225046474156148;
   fWeightMatrix0to1[26][0] = 0.345813668394185;
   fWeightMatrix0to1[27][0] = -0.857667508371482;
   fWeightMatrix0to1[28][0] = -0.596993047718371;
   fWeightMatrix0to1[29][0] = 0.0625219182642496;
   fWeightMatrix0to1[0][1] = -0.362806536406737;
   fWeightMatrix0to1[1][1] = 0.483923318324546;
   fWeightMatrix0to1[2][1] = -0.860353899469437;
   fWeightMatrix0to1[3][1] = 0.0944076201528396;
   fWeightMatrix0to1[4][1] = 0.203146048611471;
   fWeightMatrix0to1[5][1] = -0.0706097238729379;
   fWeightMatrix0to1[6][1] = -2.09333458672125;
   fWeightMatrix0to1[7][1] = 1.55423479413686;
   fWeightMatrix0to1[8][1] = -0.169101821736697;
   fWeightMatrix0to1[9][1] = 1.02431045693344;
   fWeightMatrix0to1[10][1] = -1.86256032801649;
   fWeightMatrix0to1[11][1] = 1.01553841442355;
   fWeightMatrix0to1[12][1] = 0.644553265244001;
   fWeightMatrix0to1[13][1] = 2.43109457203969;
   fWeightMatrix0to1[14][1] = -0.533777423778691;
   fWeightMatrix0to1[15][1] = -1.68929516548661;
   fWeightMatrix0to1[16][1] = 0.164626001396949;
   fWeightMatrix0to1[17][1] = -0.409295529603329;
   fWeightMatrix0to1[18][1] = 0.302003288654353;
   fWeightMatrix0to1[19][1] = 1.1976549006394;
   fWeightMatrix0to1[20][1] = 0.814217977235105;
   fWeightMatrix0to1[21][1] = 1.47733173109293;
   fWeightMatrix0to1[22][1] = -0.700062967392951;
   fWeightMatrix0to1[23][1] = 0.171987523319704;
   fWeightMatrix0to1[24][1] = -0.798202957864185;
   fWeightMatrix0to1[25][1] = -0.932999888364018;
   fWeightMatrix0to1[26][1] = -1.43809630386143;
   fWeightMatrix0to1[27][1] = -1.9893556456421;
   fWeightMatrix0to1[28][1] = 0.978357190710853;
   fWeightMatrix0to1[29][1] = 0.611425361475101;
   fWeightMatrix0to1[0][2] = -1.18834879011131;
   fWeightMatrix0to1[1][2] = 2.49759991806658;
   fWeightMatrix0to1[2][2] = -0.701070297811353;
   fWeightMatrix0to1[3][2] = 0.702985727551989;
   fWeightMatrix0to1[4][2] = 1.32236261719451;
   fWeightMatrix0to1[5][2] = -0.396545682318598;
   fWeightMatrix0to1[6][2] = 0.352971871770447;
   fWeightMatrix0to1[7][2] = -0.43029004492569;
   fWeightMatrix0to1[8][2] = 0.293827556377935;
   fWeightMatrix0to1[9][2] = -1.19356858487419;
   fWeightMatrix0to1[10][2] = -0.1701780029791;
   fWeightMatrix0to1[11][2] = -1.13340800993775;
   fWeightMatrix0to1[12][2] = -0.152483552238442;
   fWeightMatrix0to1[13][2] = 0.937687007263993;
   fWeightMatrix0to1[14][2] = 1.47927132899549;
   fWeightMatrix0to1[15][2] = -0.419031246080579;
   fWeightMatrix0to1[16][2] = -1.20985200086661;
   fWeightMatrix0to1[17][2] = -1.89781680243831;
   fWeightMatrix0to1[18][2] = 1.29310519355398;
   fWeightMatrix0to1[19][2] = 0.41000185374865;
   fWeightMatrix0to1[20][2] = 1.92753006539677;
   fWeightMatrix0to1[21][2] = 0.571721551157184;
   fWeightMatrix0to1[22][2] = 0.918137513061511;
   fWeightMatrix0to1[23][2] = -0.71739750369434;
   fWeightMatrix0to1[24][2] = -0.259335381971884;
   fWeightMatrix0to1[25][2] = -0.0826046708997781;
   fWeightMatrix0to1[26][2] = 1.22315197436356;
   fWeightMatrix0to1[27][2] = -0.998740767390887;
   fWeightMatrix0to1[28][2] = -1.19612173933798;
   fWeightMatrix0to1[29][2] = -1.62763619370033;
   fWeightMatrix0to1[0][3] = -0.0271797806960753;
   fWeightMatrix0to1[1][3] = 1.42335481935263;
   fWeightMatrix0to1[2][3] = 1.77658720884645;
   fWeightMatrix0to1[3][3] = -2.076738175866;
   fWeightMatrix0to1[4][3] = -1.02784499006987;
   fWeightMatrix0to1[5][3] = 1.04411376635997;
   fWeightMatrix0to1[6][3] = -0.81028580431145;
   fWeightMatrix0to1[7][3] = -1.42332595298207;
   fWeightMatrix0to1[8][3] = -2.17339736420982;
   fWeightMatrix0to1[9][3] = -0.068462061847257;
   fWeightMatrix0to1[10][3] = -1.24686780439854;
   fWeightMatrix0to1[11][3] = -1.67138424543334;
   fWeightMatrix0to1[12][3] = -0.0114248453948183;
   fWeightMatrix0to1[13][3] = 1.11844306775783;
   fWeightMatrix0to1[14][3] = -0.979322110359837;
   fWeightMatrix0to1[15][3] = 1.55519109330224;
   fWeightMatrix0to1[16][3] = -0.278503343044321;
   fWeightMatrix0to1[17][3] = -1.11269152234677;
   fWeightMatrix0to1[18][3] = 0.414401034765911;
   fWeightMatrix0to1[19][3] = 0.706374935016993;
   fWeightMatrix0to1[20][3] = -1.41926620722559;
   fWeightMatrix0to1[21][3] = 0.499539276579248;
   fWeightMatrix0to1[22][3] = 0.389796091102153;
   fWeightMatrix0to1[23][3] = 0.54026814573815;
   fWeightMatrix0to1[24][3] = -1.05979676449966;
   fWeightMatrix0to1[25][3] = 1.63863483843729;
   fWeightMatrix0to1[26][3] = 0.405949194233044;
   fWeightMatrix0to1[27][3] = -0.916858028589571;
   fWeightMatrix0to1[28][3] = 0.593572543449212;
   fWeightMatrix0to1[29][3] = -1.04407651828714;
   fWeightMatrix0to1[0][4] = -3.04499384003777;
   fWeightMatrix0to1[1][4] = -3.22953444592526;
   fWeightMatrix0to1[2][4] = 0.788318905345126;
   fWeightMatrix0to1[3][4] = 2.19319941140198;
   fWeightMatrix0to1[4][4] = 0.62588313926701;
   fWeightMatrix0to1[5][4] = -2.49875904673629;
   fWeightMatrix0to1[6][4] = 0.0980196807167267;
   fWeightMatrix0to1[7][4] = 0.233983087438414;
   fWeightMatrix0to1[8][4] = -1.51415409478433;
   fWeightMatrix0to1[9][4] = 0.827112893088158;
   fWeightMatrix0to1[10][4] = 3.37503637137053;
   fWeightMatrix0to1[11][4] = -1.31682032757725;
   fWeightMatrix0to1[12][4] = -0.00733818347764386;
   fWeightMatrix0to1[13][4] = -3.12750307852689;
   fWeightMatrix0to1[14][4] = 0.0443881000091958;
   fWeightMatrix0to1[15][4] = 1.11847539096472;
   fWeightMatrix0to1[16][4] = 1.06210996951103;
   fWeightMatrix0to1[17][4] = -1.99170042633716;
   fWeightMatrix0to1[18][4] = -0.0206621040353649;
   fWeightMatrix0to1[19][4] = 1.09145471552679;
   fWeightMatrix0to1[20][4] = 1.49825771535003;
   fWeightMatrix0to1[21][4] = 0.177037367219454;
   fWeightMatrix0to1[22][4] = -1.26459172754116;
   fWeightMatrix0to1[23][4] = -2.70801492469472;
   fWeightMatrix0to1[24][4] = -1.1000287792803;
   fWeightMatrix0to1[25][4] = 1.77647095566041;
   fWeightMatrix0to1[26][4] = 1.94084297301677;
   fWeightMatrix0to1[27][4] = -0.651032320347663;
   fWeightMatrix0to1[28][4] = -0.66632459018917;
   fWeightMatrix0to1[29][4] = 0.188549459524829;
   fWeightMatrix0to1[0][5] = 0.24792307599634;
   fWeightMatrix0to1[1][5] = -0.0221519683588569;
   fWeightMatrix0to1[2][5] = 1.84437850799493;
   fWeightMatrix0to1[3][5] = -0.951847085936022;
   fWeightMatrix0to1[4][5] = -0.939681772401003;
   fWeightMatrix0to1[5][5] = -2.3758532279803;
   fWeightMatrix0to1[6][5] = 0.682250140330108;
   fWeightMatrix0to1[7][5] = 0.485709464442415;
   fWeightMatrix0to1[8][5] = 0.709571181747666;
   fWeightMatrix0to1[9][5] = -1.66636388959112;
   fWeightMatrix0to1[10][5] = 4.04756441355278;
   fWeightMatrix0to1[11][5] = 0.719142297766681;
   fWeightMatrix0to1[12][5] = -0.404840448845278;
   fWeightMatrix0to1[13][5] = -0.261616748498227;
   fWeightMatrix0to1[14][5] = 1.00831446061336;
   fWeightMatrix0to1[15][5] = -0.628271156109257;
   fWeightMatrix0to1[16][5] = -0.664378683413971;
   fWeightMatrix0to1[17][5] = 0.688238097196072;
   fWeightMatrix0to1[18][5] = -1.44232495714042;
   fWeightMatrix0to1[19][5] = -0.384924867204342;
   fWeightMatrix0to1[20][5] = 1.35786915425502;
   fWeightMatrix0to1[21][5] = 1.25391087866845;
   fWeightMatrix0to1[22][5] = 0.0359541665759173;
   fWeightMatrix0to1[23][5] = 0.0100679617457241;
   fWeightMatrix0to1[24][5] = 1.51079704011327;
   fWeightMatrix0to1[25][5] = -1.71202267715307;
   fWeightMatrix0to1[26][5] = 0.429925003735475;
   fWeightMatrix0to1[27][5] = -0.259211268160434;
   fWeightMatrix0to1[28][5] = 0.208537206631558;
   fWeightMatrix0to1[29][5] = -1.72902154058252;
   fWeightMatrix0to1[0][6] = -0.271372006841207;
   fWeightMatrix0to1[1][6] = 1.16934679472533;
   fWeightMatrix0to1[2][6] = 1.66695477987648;
   fWeightMatrix0to1[3][6] = -1.51834785137802;
   fWeightMatrix0to1[4][6] = -0.397566641141078;
   fWeightMatrix0to1[5][6] = 0.310581678004228;
   fWeightMatrix0to1[6][6] = 0.536217991939706;
   fWeightMatrix0to1[7][6] = 1.37186269494754;
   fWeightMatrix0to1[8][6] = -0.498002582825063;
   fWeightMatrix0to1[9][6] = -0.362891038943176;
   fWeightMatrix0to1[10][6] = -1.07386293385519;
   fWeightMatrix0to1[11][6] = 1.09860640381293;
   fWeightMatrix0to1[12][6] = 1.69974188482162;
   fWeightMatrix0to1[13][6] = -0.103044257368807;
   fWeightMatrix0to1[14][6] = 0.341985660500553;
   fWeightMatrix0to1[15][6] = -0.845542352048115;
   fWeightMatrix0to1[16][6] = -2.0268312756839;
   fWeightMatrix0to1[17][6] = 0.673297633834398;
   fWeightMatrix0to1[18][6] = 0.710589317772385;
   fWeightMatrix0to1[19][6] = -2.94512868339205;
   fWeightMatrix0to1[20][6] = -0.568309946660064;
   fWeightMatrix0to1[21][6] = 0.69821913759519;
   fWeightMatrix0to1[22][6] = 0.0467226552690682;
   fWeightMatrix0to1[23][6] = -1.78881147519203;
   fWeightMatrix0to1[24][6] = 1.20502384713047;
   fWeightMatrix0to1[25][6] = 0.924099184545189;
   fWeightMatrix0to1[26][6] = -0.745053872102016;
   fWeightMatrix0to1[27][6] = -0.372686644633967;
   fWeightMatrix0to1[28][6] = 1.19919326626801;
   fWeightMatrix0to1[29][6] = 1.03278411011181;
   fWeightMatrix0to1[0][7] = -0.688784842066234;
   fWeightMatrix0to1[1][7] = 0.526108492673675;
   fWeightMatrix0to1[2][7] = -0.39791567280577;
   fWeightMatrix0to1[3][7] = -1.57561443425049;
   fWeightMatrix0to1[4][7] = 1.43572947026807;
   fWeightMatrix0to1[5][7] = 0.295558739301534;
   fWeightMatrix0to1[6][7] = 0.382732871833326;
   fWeightMatrix0to1[7][7] = 0.281593498541789;
   fWeightMatrix0to1[8][7] = 0.278563253926957;
   fWeightMatrix0to1[9][7] = -1.82866363352592;
   fWeightMatrix0to1[10][7] = -0.832999595777499;
   fWeightMatrix0to1[11][7] = -0.07501838625834;
   fWeightMatrix0to1[12][7] = -1.66392558392217;
   fWeightMatrix0to1[13][7] = 1.21928239870558;
   fWeightMatrix0to1[14][7] = 1.78677895776937;
   fWeightMatrix0to1[15][7] = -1.34534727044793;
   fWeightMatrix0to1[16][7] = 1.17584537859708;
   fWeightMatrix0to1[17][7] = -0.682464481105102;
   fWeightMatrix0to1[18][7] = -0.552357577192112;
   fWeightMatrix0to1[19][7] = 0.652968983229308;
   fWeightMatrix0to1[20][7] = 0.860360974900587;
   fWeightMatrix0to1[21][7] = 0.117445842816333;
   fWeightMatrix0to1[22][7] = 0.761770553770832;
   fWeightMatrix0to1[23][7] = -1.35496747691313;
   fWeightMatrix0to1[24][7] = 1.44081747124734;
   fWeightMatrix0to1[25][7] = -1.77290338979429;
   fWeightMatrix0to1[26][7] = 0.838434323774026;
   fWeightMatrix0to1[27][7] = -0.180532773251005;
   fWeightMatrix0to1[28][7] = -1.23720438059546;
   fWeightMatrix0to1[29][7] = -1.17446805700447;
   fWeightMatrix0to1[0][8] = -0.317452871674657;
   fWeightMatrix0to1[1][8] = -0.900458520857031;
   fWeightMatrix0to1[2][8] = -4.17103002579467;
   fWeightMatrix0to1[3][8] = -1.35441908193913;
   fWeightMatrix0to1[4][8] = -1.37344851155112;
   fWeightMatrix0to1[5][8] = -0.0131453969758011;
   fWeightMatrix0to1[6][8] = -0.441600237741676;
   fWeightMatrix0to1[7][8] = -0.367879695700998;
   fWeightMatrix0to1[8][8] = 0.899458482177063;
   fWeightMatrix0to1[9][8] = -0.478245969490158;
   fWeightMatrix0to1[10][8] = -0.252137522839128;
   fWeightMatrix0to1[11][8] = -1.23018277921913;
   fWeightMatrix0to1[12][8] = 0.521058590554907;
   fWeightMatrix0to1[13][8] = 1.22565514178533;
   fWeightMatrix0to1[14][8] = 1.43407899087048;
   fWeightMatrix0to1[15][8] = -0.748279857073886;
   fWeightMatrix0to1[16][8] = -2.02054336908396;
   fWeightMatrix0to1[17][8] = -1.28510059360994;
   fWeightMatrix0to1[18][8] = -2.32681921804888;
   fWeightMatrix0to1[19][8] = -0.357939701538338;
   fWeightMatrix0to1[20][8] = 0.335662930144644;
   fWeightMatrix0to1[21][8] = 0.410677247228052;
   fWeightMatrix0to1[22][8] = 0.870354723511541;
   fWeightMatrix0to1[23][8] = 0.215817725789107;
   fWeightMatrix0to1[24][8] = -0.124625590185582;
   fWeightMatrix0to1[25][8] = -0.959062794577146;
   fWeightMatrix0to1[26][8] = -2.04759651834215;
   fWeightMatrix0to1[27][8] = 0.94733601073056;
   fWeightMatrix0to1[28][8] = 0.444881745766689;
   fWeightMatrix0to1[29][8] = -0.911453679824362;
   fWeightMatrix0to1[0][9] = 0.0251053738692279;
   fWeightMatrix0to1[1][9] = -0.226611876138912;
   fWeightMatrix0to1[2][9] = -0.15459740815817;
   fWeightMatrix0to1[3][9] = 0.478152150815667;
   fWeightMatrix0to1[4][9] = -0.740596658731992;
   fWeightMatrix0to1[5][9] = 0.286708638996393;
   fWeightMatrix0to1[6][9] = 1.08690705363415;
   fWeightMatrix0to1[7][9] = 1.07153697303781;
   fWeightMatrix0to1[8][9] = 1.4397800589062;
   fWeightMatrix0to1[9][9] = -0.0777892101760244;
   fWeightMatrix0to1[10][9] = -0.247769152945408;
   fWeightMatrix0to1[11][9] = -0.427630935270909;
   fWeightMatrix0to1[12][9] = -0.285129370992799;
   fWeightMatrix0to1[13][9] = 0.578303301372716;
   fWeightMatrix0to1[14][9] = -1.69590924808722;
   fWeightMatrix0to1[15][9] = -1.22646920006049;
   fWeightMatrix0to1[16][9] = -0.969802621395353;
   fWeightMatrix0to1[17][9] = 1.63749194029549;
   fWeightMatrix0to1[18][9] = -0.357106191406971;
   fWeightMatrix0to1[19][9] = -0.139708307273579;
   fWeightMatrix0to1[20][9] = -0.638424480578935;
   fWeightMatrix0to1[21][9] = 1.10376945432127;
   fWeightMatrix0to1[22][9] = -0.793237373602286;
   fWeightMatrix0to1[23][9] = 0.389039945824549;
   fWeightMatrix0to1[24][9] = 0.143302479029556;
   fWeightMatrix0to1[25][9] = -2.58712156105023;
   fWeightMatrix0to1[26][9] = -0.0997703772790316;
   fWeightMatrix0to1[27][9] = 0.319896293367068;
   fWeightMatrix0to1[28][9] = -1.77361388925834;
   fWeightMatrix0to1[29][9] = -1.44213020198686;
   fWeightMatrix0to1[0][10] = -1.23401942931851;
   fWeightMatrix0to1[1][10] = -0.232516727158204;
   fWeightMatrix0to1[2][10] = 1.31942717111928;
   fWeightMatrix0to1[3][10] = -0.780551831758251;
   fWeightMatrix0to1[4][10] = 0.297938605796363;
   fWeightMatrix0to1[5][10] = 0.0704315866798335;
   fWeightMatrix0to1[6][10] = -0.469077370279348;
   fWeightMatrix0to1[7][10] = -1.87911904666251;
   fWeightMatrix0to1[8][10] = -0.398550559153655;
   fWeightMatrix0to1[9][10] = -0.960428712855372;
   fWeightMatrix0to1[10][10] = 0.173812674753205;
   fWeightMatrix0to1[11][10] = -1.81352747112556;
   fWeightMatrix0to1[12][10] = -0.57976936214931;
   fWeightMatrix0to1[13][10] = -0.257962559070058;
   fWeightMatrix0to1[14][10] = 0.330137377768841;
   fWeightMatrix0to1[15][10] = -0.443258748805505;
   fWeightMatrix0to1[16][10] = 0.75480509836853;
   fWeightMatrix0to1[17][10] = -2.06013817525461;
   fWeightMatrix0to1[18][10] = 0.55886676032473;
   fWeightMatrix0to1[19][10] = 0.191745018134549;
   fWeightMatrix0to1[20][10] = -0.471191340615394;
   fWeightMatrix0to1[21][10] = -0.665427825707116;
   fWeightMatrix0to1[22][10] = 0.0653296414634991;
   fWeightMatrix0to1[23][10] = -1.73086934159047;
   fWeightMatrix0to1[24][10] = 0.344661552754498;
   fWeightMatrix0to1[25][10] = 1.52770776421075;
   fWeightMatrix0to1[26][10] = 0.698304043673928;
   fWeightMatrix0to1[27][10] = 1.48643696899431;
   fWeightMatrix0to1[28][10] = -0.825539327495117;
   fWeightMatrix0to1[29][10] = 0.979475150768958;
   fWeightMatrix0to1[0][11] = -0.274141586379449;
   fWeightMatrix0to1[1][11] = -0.150173743869159;
   fWeightMatrix0to1[2][11] = -0.0786259092737111;
   fWeightMatrix0to1[3][11] = -0.0601554270267122;
   fWeightMatrix0to1[4][11] = 0.0331916699634065;
   fWeightMatrix0to1[5][11] = 0.259009376426991;
   fWeightMatrix0to1[6][11] = 0.634401682431971;
   fWeightMatrix0to1[7][11] = -0.4209069567664;
   fWeightMatrix0to1[8][11] = -0.106865620531111;
   fWeightMatrix0to1[9][11] = -0.121880402112553;
   fWeightMatrix0to1[10][11] = 0.0493234404306118;
   fWeightMatrix0to1[11][11] = -0.296365439203686;
   fWeightMatrix0to1[12][11] = 0.528308878311567;
   fWeightMatrix0to1[13][11] = -2.49897808746987;
   fWeightMatrix0to1[14][11] = 0.418171825826007;
   fWeightMatrix0to1[15][11] = -1.36303004168105;
   fWeightMatrix0to1[16][11] = -1.09106086824034;
   fWeightMatrix0to1[17][11] = 0.179304193603309;
   fWeightMatrix0to1[18][11] = 0.756766252219151;
   fWeightMatrix0to1[19][11] = -1.22175212333849;
   fWeightMatrix0to1[20][11] = 0.368853776614252;
   fWeightMatrix0to1[21][11] = 1.77966808672757;
   fWeightMatrix0to1[22][11] = 0.0879649205013397;
   fWeightMatrix0to1[23][11] = -0.283793845309783;
   fWeightMatrix0to1[24][11] = -0.0339204539116314;
   fWeightMatrix0to1[25][11] = -1.52194356759344;
   fWeightMatrix0to1[26][11] = -1.69140943419033;
   fWeightMatrix0to1[27][11] = 0.832801485423088;
   fWeightMatrix0to1[28][11] = 0.367692939588377;
   fWeightMatrix0to1[29][11] = -1.2698494155923;
   fWeightMatrix0to1[0][12] = 0.190307394309951;
   fWeightMatrix0to1[1][12] = -0.408115594153089;
   fWeightMatrix0to1[2][12] = -0.853965629734445;
   fWeightMatrix0to1[3][12] = -0.761909990543863;
   fWeightMatrix0to1[4][12] = 0.22439487617385;
   fWeightMatrix0to1[5][12] = -3.30729149267477;
   fWeightMatrix0to1[6][12] = -1.31284419600117;
   fWeightMatrix0to1[7][12] = -0.252737080488581;
   fWeightMatrix0to1[8][12] = 0.0189233665337367;
   fWeightMatrix0to1[9][12] = -1.24133859464823;
   fWeightMatrix0to1[10][12] = 2.74743616039116;
   fWeightMatrix0to1[11][12] = -1.67591105800563;
   fWeightMatrix0to1[12][12] = -0.85068235521056;
   fWeightMatrix0to1[13][12] = 1.93500906650967;
   fWeightMatrix0to1[14][12] = 0.567715391048487;
   fWeightMatrix0to1[15][12] = 0.337114793076044;
   fWeightMatrix0to1[16][12] = 0.291124079666397;
   fWeightMatrix0to1[17][12] = 0.955760020871122;
   fWeightMatrix0to1[18][12] = 0.962324752428238;
   fWeightMatrix0to1[19][12] = 0.0861520491338901;
   fWeightMatrix0to1[20][12] = 0.310648973309455;
   fWeightMatrix0to1[21][12] = -0.287614596066685;
   fWeightMatrix0to1[22][12] = 0.101865358576579;
   fWeightMatrix0to1[23][12] = -0.375257121864353;
   fWeightMatrix0to1[24][12] = -0.242302636091142;
   fWeightMatrix0to1[25][12] = -0.497595418569971;
   fWeightMatrix0to1[26][12] = 0.93210796354891;
   fWeightMatrix0to1[27][12] = 0.665851844779537;
   fWeightMatrix0to1[28][12] = 0.583639839770973;
   fWeightMatrix0to1[29][12] = -1.31350668529279;
   fWeightMatrix0to1[0][13] = 0.436231969057972;
   fWeightMatrix0to1[1][13] = 1.58400272478539;
   fWeightMatrix0to1[2][13] = -1.43108785552848;
   fWeightMatrix0to1[3][13] = 0.155112168233361;
   fWeightMatrix0to1[4][13] = -0.864485424719483;
   fWeightMatrix0to1[5][13] = 0.00124363233437849;
   fWeightMatrix0to1[6][13] = -0.217156988671992;
   fWeightMatrix0to1[7][13] = 0.381849228734863;
   fWeightMatrix0to1[8][13] = 0.620360174546931;
   fWeightMatrix0to1[9][13] = -0.255702651573872;
   fWeightMatrix0to1[10][13] = 0.20375813755929;
   fWeightMatrix0to1[11][13] = 1.80061196555226;
   fWeightMatrix0to1[12][13] = 0.161411054376645;
   fWeightMatrix0to1[13][13] = -0.192841112359797;
   fWeightMatrix0to1[14][13] = 1.71490426378837;
   fWeightMatrix0to1[15][13] = -1.84739084385974;
   fWeightMatrix0to1[16][13] = -0.173840689937465;
   fWeightMatrix0to1[17][13] = 1.38494773770749;
   fWeightMatrix0to1[18][13] = -0.549800870761593;
   fWeightMatrix0to1[19][13] = -0.363107027687225;
   fWeightMatrix0to1[20][13] = 0.408876253655058;
   fWeightMatrix0to1[21][13] = -1.31791651409348;
   fWeightMatrix0to1[22][13] = -0.149735322488775;
   fWeightMatrix0to1[23][13] = -0.0441328755917919;
   fWeightMatrix0to1[24][13] = -0.0450882140751068;
   fWeightMatrix0to1[25][13] = -0.710984240086802;
   fWeightMatrix0to1[26][13] = 0.677152005818053;
   fWeightMatrix0to1[27][13] = 1.15390304479847;
   fWeightMatrix0to1[28][13] = 0.903283890689196;
   fWeightMatrix0to1[29][13] = -0.631028255303024;
   fWeightMatrix0to1[0][14] = 0.0836328806979163;
   fWeightMatrix0to1[1][14] = -0.189877977014761;
   fWeightMatrix0to1[2][14] = -0.329833371929951;
   fWeightMatrix0to1[3][14] = -0.0627769304234867;
   fWeightMatrix0to1[4][14] = -0.482078674316405;
   fWeightMatrix0to1[5][14] = 0.0120025540848853;
   fWeightMatrix0to1[6][14] = 0.062450480591665;
   fWeightMatrix0to1[7][14] = 0.123871910324235;
   fWeightMatrix0to1[8][14] = -0.625403116220002;
   fWeightMatrix0to1[9][14] = 0.394627549048437;
   fWeightMatrix0to1[10][14] = 0.0285396883509106;
   fWeightMatrix0to1[11][14] = -1.89321280120925;
   fWeightMatrix0to1[12][14] = -0.164006600888943;
   fWeightMatrix0to1[13][14] = 0.022586798812754;
   fWeightMatrix0to1[14][14] = 1.78140593547126;
   fWeightMatrix0to1[15][14] = 1.82284482971616;
   fWeightMatrix0to1[16][14] = 0.351758546852971;
   fWeightMatrix0to1[17][14] = -0.716966373459479;
   fWeightMatrix0to1[18][14] = -0.522045319343326;
   fWeightMatrix0to1[19][14] = 0.0287426846552094;
   fWeightMatrix0to1[20][14] = -0.258496585615205;
   fWeightMatrix0to1[21][14] = -1.35686037246063;
   fWeightMatrix0to1[22][14] = -0.153714475201536;
   fWeightMatrix0to1[23][14] = -0.0366137879413424;
   fWeightMatrix0to1[24][14] = -0.0819634420389559;
   fWeightMatrix0to1[25][14] = 1.01409532182053;
   fWeightMatrix0to1[26][14] = -0.0129173034729309;
   fWeightMatrix0to1[27][14] = -0.0951082149116203;
   fWeightMatrix0to1[28][14] = -0.0398705299149355;
   fWeightMatrix0to1[29][14] = -0.955969594400624;
   fWeightMatrix0to1[0][15] = 2.26662285586704;
   fWeightMatrix0to1[1][15] = 0.864372469750574;
   fWeightMatrix0to1[2][15] = -0.165964961568125;
   fWeightMatrix0to1[3][15] = 0.623928485501538;
   fWeightMatrix0to1[4][15] = 1.25663318179083;
   fWeightMatrix0to1[5][15] = -2.49660912582989;
   fWeightMatrix0to1[6][15] = 3.15134192770082;
   fWeightMatrix0to1[7][15] = -2.64058846794756;
   fWeightMatrix0to1[8][15] = 0.923736485855983;
   fWeightMatrix0to1[9][15] = 1.78642526973361;
   fWeightMatrix0to1[10][15] = -2.48564929584127;
   fWeightMatrix0to1[11][15] = -0.45209975802654;
   fWeightMatrix0to1[12][15] = 0.843695597228037;
   fWeightMatrix0to1[13][15] = 1.09813089250018;
   fWeightMatrix0to1[14][15] = 1.21300228538618;
   fWeightMatrix0to1[15][15] = 0.280476268721437;
   fWeightMatrix0to1[16][15] = -0.365357133828428;
   fWeightMatrix0to1[17][15] = -1.63146170285724;
   fWeightMatrix0to1[18][15] = -1.39778418012554;
   fWeightMatrix0to1[19][15] = 0.1554786494046;
   fWeightMatrix0to1[20][15] = 0.416368866430856;
   fWeightMatrix0to1[21][15] = -0.433958574651761;
   fWeightMatrix0to1[22][15] = -1.43580665733908;
   fWeightMatrix0to1[23][15] = 3.64619599471315;
   fWeightMatrix0to1[24][15] = 0.0734710883313391;
   fWeightMatrix0to1[25][15] = -1.21038755742086;
   fWeightMatrix0to1[26][15] = -0.267868885274061;
   fWeightMatrix0to1[27][15] = -1.36236701686299;
   fWeightMatrix0to1[28][15] = 0.562096397691875;
   fWeightMatrix0to1[29][15] = 1.48698009613647;
   fWeightMatrix0to1[0][16] = -1.66320966924896;
   fWeightMatrix0to1[1][16] = -0.819997727598758;
   fWeightMatrix0to1[2][16] = 1.25388330566368;
   fWeightMatrix0to1[3][16] = 1.57802256355846;
   fWeightMatrix0to1[4][16] = 0.322308755764235;
   fWeightMatrix0to1[5][16] = -0.0711584795040589;
   fWeightMatrix0to1[6][16] = -1.04612825358689;
   fWeightMatrix0to1[7][16] = -0.724896489733799;
   fWeightMatrix0to1[8][16] = 0.563314833962274;
   fWeightMatrix0to1[9][16] = 0.205837183244672;
   fWeightMatrix0to1[10][16] = 0.46869402906642;
   fWeightMatrix0to1[11][16] = -1.756431176513;
   fWeightMatrix0to1[12][16] = -2.74419126716242;
   fWeightMatrix0to1[13][16] = -2.10958242290123;
   fWeightMatrix0to1[14][16] = -0.188342945252292;
   fWeightMatrix0to1[15][16] = -1.83534507588236;
   fWeightMatrix0to1[16][16] = 0.717768759534761;
   fWeightMatrix0to1[17][16] = -0.55838446468797;
   fWeightMatrix0to1[18][16] = 0.70301509563962;
   fWeightMatrix0to1[19][16] = 0.550607669842092;
   fWeightMatrix0to1[20][16] = -1.56940191143588;
   fWeightMatrix0to1[21][16] = 1.63440408119705;
   fWeightMatrix0to1[22][16] = 1.78775587233396;
   fWeightMatrix0to1[23][16] = 0.277173618458472;
   fWeightMatrix0to1[24][16] = -0.0553849694742933;
   fWeightMatrix0to1[25][16] = -1.28584691402443;
   fWeightMatrix0to1[26][16] = 2.42257623044371;
   fWeightMatrix0to1[27][16] = -1.59547426300016;
   fWeightMatrix0to1[28][16] = 0.353061962493564;
   fWeightMatrix0to1[29][16] = -1.4030699292982;
   fWeightMatrix0to1[0][17] = 1.50168051188099;
   fWeightMatrix0to1[1][17] = -0.364901722811109;
   fWeightMatrix0to1[2][17] = 0.774565219557926;
   fWeightMatrix0to1[3][17] = -0.924138320315677;
   fWeightMatrix0to1[4][17] = 0.194641371985917;
   fWeightMatrix0to1[5][17] = 0.385345374208876;
   fWeightMatrix0to1[6][17] = -0.18743859843157;
   fWeightMatrix0to1[7][17] = 0.308482259640638;
   fWeightMatrix0to1[8][17] = -0.778097526715302;
   fWeightMatrix0to1[9][17] = 0.634024839332445;
   fWeightMatrix0to1[10][17] = 0.564401073759776;
   fWeightMatrix0to1[11][17] = -1.66218973046882;
   fWeightMatrix0to1[12][17] = 1.45938961336322;
   fWeightMatrix0to1[13][17] = -2.97212757794419;
   fWeightMatrix0to1[14][17] = 1.16205780792392;
   fWeightMatrix0to1[15][17] = 1.15240831833542;
   fWeightMatrix0to1[16][17] = 0.781791311895108;
   fWeightMatrix0to1[17][17] = 1.32553537503499;
   fWeightMatrix0to1[18][17] = 0.643467054275256;
   fWeightMatrix0to1[19][17] = -2.40919069601565;
   fWeightMatrix0to1[20][17] = -0.865250749304954;
   fWeightMatrix0to1[21][17] = -0.81044124800961;
   fWeightMatrix0to1[22][17] = 0.624952882568073;
   fWeightMatrix0to1[23][17] = 1.23743347556891;
   fWeightMatrix0to1[24][17] = -0.390251150809605;
   fWeightMatrix0to1[25][17] = -0.710339133456456;
   fWeightMatrix0to1[26][17] = -0.732695901055976;
   fWeightMatrix0to1[27][17] = -1.39998937625056;
   fWeightMatrix0to1[28][17] = -0.496302529350031;
   fWeightMatrix0to1[29][17] = -2.0321753019811;
   fWeightMatrix0to1[0][18] = -0.245351753034446;
   fWeightMatrix0to1[1][18] = -0.555051791583803;
   fWeightMatrix0to1[2][18] = -0.270788684001632;
   fWeightMatrix0to1[3][18] = -0.288973465282357;
   fWeightMatrix0to1[4][18] = 0.365861977936668;
   fWeightMatrix0to1[5][18] = -0.0976880573208311;
   fWeightMatrix0to1[6][18] = -0.0103267260239826;
   fWeightMatrix0to1[7][18] = -0.684948781742855;
   fWeightMatrix0to1[8][18] = 1.89636365199323;
   fWeightMatrix0to1[9][18] = -0.558487623931145;
   fWeightMatrix0to1[10][18] = 0.0349565156991824;
   fWeightMatrix0to1[11][18] = 0.768083873464938;
   fWeightMatrix0to1[12][18] = -0.568984159368737;
   fWeightMatrix0to1[13][18] = 0.157130090780751;
   fWeightMatrix0to1[14][18] = -0.102495264533994;
   fWeightMatrix0to1[15][18] = -2.04296993201208;
   fWeightMatrix0to1[16][18] = -0.77652838733231;
   fWeightMatrix0to1[17][18] = -1.2983328334096;
   fWeightMatrix0to1[18][18] = 1.09824947949889;
   fWeightMatrix0to1[19][18] = -1.61134118453525;
   fWeightMatrix0to1[20][18] = 0.986819365119104;
   fWeightMatrix0to1[21][18] = 1.82862847103915;
   fWeightMatrix0to1[22][18] = 0.816642854183907;
   fWeightMatrix0to1[23][18] = 0.137680649477764;
   fWeightMatrix0to1[24][18] = 0.315530592100981;
   fWeightMatrix0to1[25][18] = -0.109290281419358;
   fWeightMatrix0to1[26][18] = -0.856973565501547;
   fWeightMatrix0to1[27][18] = -2.1527572351384;
   fWeightMatrix0to1[28][18] = -0.533668681782236;
   fWeightMatrix0to1[29][18] = -0.896057308777796;
   fWeightMatrix0to1[0][19] = 1.44345531670861;
   fWeightMatrix0to1[1][19] = 1.44783005030429;
   fWeightMatrix0to1[2][19] = -0.133554476332961;
   fWeightMatrix0to1[3][19] = 1.07286137279228;
   fWeightMatrix0to1[4][19] = 0.729058503479305;
   fWeightMatrix0to1[5][19] = 0.212148468329206;
   fWeightMatrix0to1[6][19] = -0.180687491652187;
   fWeightMatrix0to1[7][19] = -0.665270245356108;
   fWeightMatrix0to1[8][19] = 0.387101263726295;
   fWeightMatrix0to1[9][19] = -2.1960534157488;
   fWeightMatrix0to1[10][19] = -0.115908582846462;
   fWeightMatrix0to1[11][19] = -0.0821587240768658;
   fWeightMatrix0to1[12][19] = 0.680920603947115;
   fWeightMatrix0to1[13][19] = 0.0566035067635801;
   fWeightMatrix0to1[14][19] = 0.357374740503617;
   fWeightMatrix0to1[15][19] = -1.83686667020821;
   fWeightMatrix0to1[16][19] = -0.462435045467454;
   fWeightMatrix0to1[17][19] = 0.662008940580366;
   fWeightMatrix0to1[18][19] = -0.402440709353072;
   fWeightMatrix0to1[19][19] = 0.178305656762309;
   fWeightMatrix0to1[20][19] = -1.58285165677836;
   fWeightMatrix0to1[21][19] = 1.12525705456369;
   fWeightMatrix0to1[22][19] = -0.567490600751562;
   fWeightMatrix0to1[23][19] = 0.822910818401396;
   fWeightMatrix0to1[24][19] = -1.44622797205861;
   fWeightMatrix0to1[25][19] = -0.9075779510787;
   fWeightMatrix0to1[26][19] = 1.95914866110504;
   fWeightMatrix0to1[27][19] = -1.86100436809779;
   fWeightMatrix0to1[28][19] = -0.903951757252571;
   fWeightMatrix0to1[29][19] = -0.734804083265224;
   fWeightMatrix0to1[0][20] = -0.413744011605044;
   fWeightMatrix0to1[1][20] = 3.60964882641421;
   fWeightMatrix0to1[2][20] = 0.483682060895472;
   fWeightMatrix0to1[3][20] = -1.53856676973016;
   fWeightMatrix0to1[4][20] = 1.01176982940663;
   fWeightMatrix0to1[5][20] = -6.08994067649098;
   fWeightMatrix0to1[6][20] = 0.975895687289214;
   fWeightMatrix0to1[7][20] = -1.85624769747294;
   fWeightMatrix0to1[8][20] = -0.661983176993515;
   fWeightMatrix0to1[9][20] = 0.15515916704218;
   fWeightMatrix0to1[10][20] = 1.86523526715075;
   fWeightMatrix0to1[11][20] = 1.53009095097965;
   fWeightMatrix0to1[12][20] = -0.244328487676804;
   fWeightMatrix0to1[13][20] = 0.195005050254441;
   fWeightMatrix0to1[14][20] = -1.30042471592953;
   fWeightMatrix0to1[15][20] = 1.410873127202;
   fWeightMatrix0to1[16][20] = -0.987442515199519;
   fWeightMatrix0to1[17][20] = 1.82076818221968;
   fWeightMatrix0to1[18][20] = -1.52529140280935;
   fWeightMatrix0to1[19][20] = -3.73887522328102;
   fWeightMatrix0to1[20][20] = 1.44658077499301;
   fWeightMatrix0to1[21][20] = -0.157199651140764;
   fWeightMatrix0to1[22][20] = 1.30953473839951;
   fWeightMatrix0to1[23][20] = 0.190345383304337;
   fWeightMatrix0to1[24][20] = -1.09322404596651;
   fWeightMatrix0to1[25][20] = -0.7250718876648;
   fWeightMatrix0to1[26][20] = -1.33250354733727;
   fWeightMatrix0to1[27][20] = 0.190078825055973;
   fWeightMatrix0to1[28][20] = -0.965180351733393;
   fWeightMatrix0to1[29][20] = -0.119419617357623;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.448782718432598;
   fWeightMatrix1to2[0][1] = -0.222349926254143;
   fWeightMatrix1to2[0][2] = 0.121095911804871;
   fWeightMatrix1to2[0][3] = 0.138357078356955;
   fWeightMatrix1to2[0][4] = -0.0807324015838499;
   fWeightMatrix1to2[0][5] = 0.470669702012477;
   fWeightMatrix1to2[0][6] = -0.177334790817716;
   fWeightMatrix1to2[0][7] = 0.173384234780338;
   fWeightMatrix1to2[0][8] = 0.0874074222941221;
   fWeightMatrix1to2[0][9] = -0.10716190981094;
   fWeightMatrix1to2[0][10] = 0.401877166528127;
   fWeightMatrix1to2[0][11] = -1.15192783936987;
   fWeightMatrix1to2[0][12] = -0.161386641912568;
   fWeightMatrix1to2[0][13] = -0.188611250902134;
   fWeightMatrix1to2[0][14] = -1.24969994531487;
   fWeightMatrix1to2[0][15] = -0.399106512354949;
   fWeightMatrix1to2[0][16] = -0.246490515697521;
   fWeightMatrix1to2[0][17] = 0.629018474337629;
   fWeightMatrix1to2[0][18] = 0.183802359176686;
   fWeightMatrix1to2[0][19] = 0.254903752266882;
   fWeightMatrix1to2[0][20] = 0.0818684740379615;
   fWeightMatrix1to2[0][21] = -1.28224312204875;
   fWeightMatrix1to2[0][22] = 0.0676142413561761;
   fWeightMatrix1to2[0][23] = -0.298049779842881;
   fWeightMatrix1to2[0][24] = -0.101883846453732;
   fWeightMatrix1to2[0][25] = 0.273952408414737;
   fWeightMatrix1to2[0][26] = -0.124149855450089;
   fWeightMatrix1to2[0][27] = -0.696919260355286;
   fWeightMatrix1to2[0][28] = 0.0406302449641515;
   fWeightMatrix1to2[0][29] = 0.48687352071329;
   fWeightMatrix1to2[0][30] = -1.15457262098782;
}

inline double ReadMLPTuned::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPTuned::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPTuned::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPTuned::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPTuned::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 10;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 10;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 10;
   fMin_1[0][1] = 2;
   fMax_1[0][1] = 5;
   fMin_1[1][1] = 2;
   fMax_1[1][1] = 6;
   fMin_1[2][1] = 2;
   fMax_1[2][1] = 6;
   fMin_1[0][2] = 20.3061256409;
   fMax_1[0][2] = 724.193359375;
   fMin_1[1][2] = 20.345867157;
   fMax_1[1][2] = 1141.5065918;
   fMin_1[2][2] = 20.3061256409;
   fMax_1[2][2] = 1141.5065918;
   fMin_1[0][3] = 20.0002479553;
   fMax_1[0][3] = 483.819000244;
   fMin_1[1][3] = 20.0014019012;
   fMax_1[1][3] = 730.360351562;
   fMin_1[2][3] = 20.0002479553;
   fMax_1[2][3] = 730.360351562;
   fMin_1[0][4] = 30.6644649506;
   fMax_1[0][4] = 1190.31469727;
   fMin_1[1][4] = 31.1506328583;
   fMax_1[1][4] = 1017.54333496;
   fMin_1[2][4] = 30.6644649506;
   fMax_1[2][4] = 1190.31469727;
   fMin_1[0][5] = 30.001663208;
   fMax_1[0][5] = 613.805419922;
   fMin_1[1][5] = 30.0022945404;
   fMax_1[1][5] = 379.353942871;
   fMin_1[2][5] = 30.001663208;
   fMax_1[2][5] = 613.805419922;
   fMin_1[0][6] = 20.0035400391;
   fMax_1[0][6] = 729.446044922;
   fMin_1[1][6] = 20.0020217896;
   fMax_1[1][6] = 743.405090332;
   fMin_1[2][6] = 20.0020217896;
   fMax_1[2][6] = 743.405090332;
   fMin_1[0][7] = 20.0082492828;
   fMax_1[0][7] = 660.794494629;
   fMin_1[1][7] = 20.003408432;
   fMax_1[1][7] = 855.639770508;
   fMin_1[2][7] = 20.003408432;
   fMax_1[2][7] = 855.639770508;
   fMin_1[0][8] = 0.260792672634;
   fMax_1[0][8] = 4.59489059448;
   fMin_1[1][8] = 0.299051195383;
   fMax_1[1][8] = 5.09150838852;
   fMin_1[2][8] = 0.260792672634;
   fMax_1[2][8] = 5.09150838852;
   fMin_1[0][9] = 0.354219049215;
   fMax_1[0][9] = 5.93411493301;
   fMin_1[1][9] = 0.460506469011;
   fMax_1[1][9] = 6.81951332092;
   fMin_1[2][9] = 0.354219049215;
   fMax_1[2][9] = 6.81951332092;
   fMin_1[0][10] = 0.63454002142;
   fMax_1[0][10] = 5.7385263443;
   fMin_1[1][10] = 0.514531254768;
   fMax_1[1][10] = 5.80796384811;
   fMin_1[2][10] = 0.514531254768;
   fMax_1[2][10] = 5.80796384811;
   fMin_1[0][11] = 0.335011512041;
   fMax_1[0][11] = 4.68913269043;
   fMin_1[1][11] = 0.331118583679;
   fMax_1[1][11] = 4.59567117691;
   fMin_1[2][11] = 0.331118583679;
   fMax_1[2][11] = 4.68913269043;
   fMin_1[0][12] = 0.293443262577;
   fMax_1[0][12] = 5.23438882828;
   fMin_1[1][12] = 0.318634212017;
   fMax_1[1][12] = 5.25155687332;
   fMin_1[2][12] = 0.293443262577;
   fMax_1[2][12] = 5.25155687332;
   fMin_1[0][13] = 0.0118044847623;
   fMax_1[0][13] = 6.96633148193;
   fMin_1[1][13] = 0.0341882109642;
   fMax_1[1][13] = 7.40591907501;
   fMin_1[2][13] = 0.0118044847623;
   fMax_1[2][13] = 7.40591907501;
   fMin_1[0][14] = 0.000293850898743;
   fMax_1[0][14] = 6.25128030777;
   fMin_1[1][14] = 2.95639038086e-05;
   fMax_1[1][14] = 6.28109359741;
   fMin_1[2][14] = 2.95639038086e-05;
   fMax_1[2][14] = 6.28109359741;
   fMin_1[0][15] = 8.52508640289;
   fMax_1[0][15] = 2569.79931641;
   fMin_1[1][15] = 11.2259721756;
   fMax_1[1][15] = 3205.42749023;
   fMin_1[2][15] = 8.52508640289;
   fMax_1[2][15] = 3205.42749023;
   fMin_1[0][16] = 35.0392456055;
   fMax_1[0][16] = 3031.91503906;
   fMin_1[1][16] = 38.9231910706;
   fMax_1[1][16] = 3575.52978516;
   fMin_1[2][16] = 35.0392456055;
   fMax_1[2][16] = 3575.52978516;
   fMin_1[0][17] = 87.2694320679;
   fMax_1[0][17] = 2969.04516602;
   fMin_1[1][17] = 83.4304733276;
   fMax_1[1][17] = 2481.73486328;
   fMin_1[2][17] = 83.4304733276;
   fMax_1[2][17] = 2969.04516602;
   fMin_1[0][18] = 0.0205432064831;
   fMax_1[0][18] = 460.327148438;
   fMin_1[1][18] = 0.00157363095786;
   fMax_1[1][18] = 421.905700684;
   fMin_1[2][18] = 0.00157363095786;
   fMax_1[2][18] = 460.327148438;
   fMin_1[0][19] = 0.000356347154593;
   fMax_1[0][19] = 1282.00231934;
   fMin_1[1][19] = 0.000171629610122;
   fMax_1[1][19] = 1665.87695312;
   fMin_1[2][19] = 0.000171629610122;
   fMax_1[2][19] = 1665.87695312;
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 20;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesGet.push_back( 14);
   indicesGet.push_back( 15);
   indicesGet.push_back( 16);
   indicesGet.push_back( 17);
   indicesGet.push_back( 18);
   indicesGet.push_back( 19);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);
   indicesPut.push_back( 14);
   indicesPut.push_back( 15);
   indicesPut.push_back( 16);
   indicesPut.push_back( 17);
   indicesPut.push_back( 18);
   indicesPut.push_back( 19);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<20;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
