// Class: ReadMLPTuned
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPTuned
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : ineuteli
Date           : Thu Nov 19 12:57:39 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.11.2.el6.x86_64 #1 SMP Wed Mar 26 09:39:43 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/ineuteli/phase2/CMSSW_5_3_24/src/Delphes/plots
Training events: 31170
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
HiddenLayers: "N+10" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
NCycles: "500" [Number of training cycles]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
jet1Pt                        jet1Pt                        jet1Pt                        jet1Pt                                                          'F'    [20.0105838776,1141.5065918]
jet2Pt                        jet2Pt                        jet2Pt                        jet2Pt                                                          'F'    [20.0018119812,779.356506348]
bjet1Pt                       bjet1Pt                       bjet1Pt                       bjet1Pt                                                         'F'    [22.5726528168,948.211181641]
bjet2Pt                       bjet2Pt                       bjet2Pt                       bjet2Pt                                                         'F'    [9.35392189026,503.708984375]
leptonPt                      leptonPt                      leptonPt                      leptonPt                                                        'F'    [0.185397148132,743.405090332]
MET                           MET                           MET                           MET                                                             'F'    [0.0101556777954,855.639770508]
DeltaPhi_METl                 DeltaPhi_METl                 DeltaPhi_METl                 DeltaPhi_METl                                                   'F'    [2.95639038086e-05,6.28109359741]
DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                                                      'F'    [0.284361332655,5.96390295029]
DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                                                      'F'    [0.429002255201,457.230957031]
DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                                                      'F'    [0.322578668594,4.48389148712]
DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                                                      'F'    [0.560641825199,1511.38464355]
DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                                                      'F'    [0.331655144691,5.43578577042]
M_bb_closest                  M_bb_closest                  M_bb_closest                  M_bb_closest                                                    'F'    [11.8016901016,2381.72802734]
MT_lnu                        MT_lnu                        MT_lnu                        MT_lnu                                                          'F'    [0.00157363095786,535.521972656]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPTuned : public IClassifierReader {

 public:

   // constructor
   ReadMLPTuned( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPTuned" ),
        fNvars( 14 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "jet1Pt", "jet2Pt", "bjet1Pt", "bjet2Pt", "leptonPt", "MET", "DeltaPhi_METl", "DeltaR_j1l", "DeltaR_j2l", "DeltaR_b1l", "DeltaR_b2l", "DeltaR_bb1", "M_bb_closest", "MT_lnu" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 0.99999988079071;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPTuned() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][14];
   double fMax_1[3][14];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[25][15];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][25];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPTuned::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 15; fWeights[0] = new double[15]; 
   fLayerSize[1] = 25; fWeights[1] = new double[25]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.332501233433927;
   fWeightMatrix0to1[1][0] = 2.39156006932776;
   fWeightMatrix0to1[2][0] = 0.249047797653199;
   fWeightMatrix0to1[3][0] = 1.75937960986428;
   fWeightMatrix0to1[4][0] = -1.96757297979022;
   fWeightMatrix0to1[5][0] = -1.42222918467095;
   fWeightMatrix0to1[6][0] = -0.729274607369254;
   fWeightMatrix0to1[7][0] = 1.19545211897649;
   fWeightMatrix0to1[8][0] = -0.946904009932456;
   fWeightMatrix0to1[9][0] = -1.03887534427617;
   fWeightMatrix0to1[10][0] = -2.67856040309097;
   fWeightMatrix0to1[11][0] = -0.413532020684041;
   fWeightMatrix0to1[12][0] = -1.31933414118781;
   fWeightMatrix0to1[13][0] = -0.809872476937968;
   fWeightMatrix0to1[14][0] = -0.821939497921496;
   fWeightMatrix0to1[15][0] = 0.17403179874783;
   fWeightMatrix0to1[16][0] = -0.703827623786074;
   fWeightMatrix0to1[17][0] = 1.2626063165828;
   fWeightMatrix0to1[18][0] = -0.294798628046494;
   fWeightMatrix0to1[19][0] = 1.09127409056906;
   fWeightMatrix0to1[20][0] = 0.356577760528142;
   fWeightMatrix0to1[21][0] = -0.749881696718097;
   fWeightMatrix0to1[22][0] = 1.13128003971493;
   fWeightMatrix0to1[23][0] = 0.298986090223567;
   fWeightMatrix0to1[0][1] = -1.25957804127471;
   fWeightMatrix0to1[1][1] = 0.207017994087987;
   fWeightMatrix0to1[2][1] = 1.25146464724675;
   fWeightMatrix0to1[3][1] = -0.580316131744293;
   fWeightMatrix0to1[4][1] = -1.83947861862106;
   fWeightMatrix0to1[5][1] = 0.907822422061784;
   fWeightMatrix0to1[6][1] = 0.657161752790727;
   fWeightMatrix0to1[7][1] = 2.55453033398197;
   fWeightMatrix0to1[8][1] = -0.682812092006762;
   fWeightMatrix0to1[9][1] = 1.44999642016467;
   fWeightMatrix0to1[10][1] = -1.93814540006778;
   fWeightMatrix0to1[11][1] = -0.277063793792029;
   fWeightMatrix0to1[12][1] = -1.67920638453583;
   fWeightMatrix0to1[13][1] = 0.826485912209049;
   fWeightMatrix0to1[14][1] = -1.85583700835469;
   fWeightMatrix0to1[15][1] = 0.449435856462469;
   fWeightMatrix0to1[16][1] = 0.401264283446236;
   fWeightMatrix0to1[17][1] = 0.444627942375244;
   fWeightMatrix0to1[18][1] = -0.271052980383779;
   fWeightMatrix0to1[19][1] = 0.579380401472121;
   fWeightMatrix0to1[20][1] = 0.0502154078881133;
   fWeightMatrix0to1[21][1] = -1.63920813163208;
   fWeightMatrix0to1[22][1] = 0.034216505648391;
   fWeightMatrix0to1[23][1] = 0.0728033989967056;
   fWeightMatrix0to1[0][2] = 1.36416337357209;
   fWeightMatrix0to1[1][2] = 1.50572409933112;
   fWeightMatrix0to1[2][2] = 0.458417364859394;
   fWeightMatrix0to1[3][2] = 1.67469213915805;
   fWeightMatrix0to1[4][2] = -1.76823481856341;
   fWeightMatrix0to1[5][2] = -1.20898293637706;
   fWeightMatrix0to1[6][2] = -1.15340246778947;
   fWeightMatrix0to1[7][2] = -1.47010754615753;
   fWeightMatrix0to1[8][2] = -0.728487097486182;
   fWeightMatrix0to1[9][2] = -6.24997820207311;
   fWeightMatrix0to1[10][2] = 5.05603602247437;
   fWeightMatrix0to1[11][2] = 0.682544701189424;
   fWeightMatrix0to1[12][2] = -1.59958314025078;
   fWeightMatrix0to1[13][2] = -0.878289498643039;
   fWeightMatrix0to1[14][2] = -0.792815180994826;
   fWeightMatrix0to1[15][2] = 0.937267520584065;
   fWeightMatrix0to1[16][2] = 2.58672384874103;
   fWeightMatrix0to1[17][2] = 0.125403561496868;
   fWeightMatrix0to1[18][2] = -1.16163899525964;
   fWeightMatrix0to1[19][2] = -0.876664797436277;
   fWeightMatrix0to1[20][2] = -0.674859435925318;
   fWeightMatrix0to1[21][2] = -0.835728159470535;
   fWeightMatrix0to1[22][2] = 0.914017753606968;
   fWeightMatrix0to1[23][2] = -1.33191789314864;
   fWeightMatrix0to1[0][3] = 0.592277242941076;
   fWeightMatrix0to1[1][3] = -0.123357378888823;
   fWeightMatrix0to1[2][3] = 1.11062251059233;
   fWeightMatrix0to1[3][3] = 0.109748868173121;
   fWeightMatrix0to1[4][3] = -1.97880504705815;
   fWeightMatrix0to1[5][3] = -2.28960771940884;
   fWeightMatrix0to1[6][3] = 0.443623461179881;
   fWeightMatrix0to1[7][3] = 0.896791480453495;
   fWeightMatrix0to1[8][3] = 3.52339915174784;
   fWeightMatrix0to1[9][3] = -4.03383552616227;
   fWeightMatrix0to1[10][3] = 0.850076703561312;
   fWeightMatrix0to1[11][3] = -0.805662742577797;
   fWeightMatrix0to1[12][3] = -1.09685224362822;
   fWeightMatrix0to1[13][3] = -0.936236777758423;
   fWeightMatrix0to1[14][3] = 1.15468817997715;
   fWeightMatrix0to1[15][3] = -0.686268977551493;
   fWeightMatrix0to1[16][3] = -1.44402604389246;
   fWeightMatrix0to1[17][3] = -0.860003059201866;
   fWeightMatrix0to1[18][3] = -2.87695255864435;
   fWeightMatrix0to1[19][3] = -0.141190780276325;
   fWeightMatrix0to1[20][3] = 2.10691781603746;
   fWeightMatrix0to1[21][3] = -1.60818435002057;
   fWeightMatrix0to1[22][3] = -1.27201568210573;
   fWeightMatrix0to1[23][3] = 0.973508384624407;
   fWeightMatrix0to1[0][4] = -0.799338186670197;
   fWeightMatrix0to1[1][4] = -1.68031853715682;
   fWeightMatrix0to1[2][4] = -0.467460882665675;
   fWeightMatrix0to1[3][4] = 0.515264493988733;
   fWeightMatrix0to1[4][4] = -1.86591104101045;
   fWeightMatrix0to1[5][4] = -0.583909340901601;
   fWeightMatrix0to1[6][4] = 0.0485715398760401;
   fWeightMatrix0to1[7][4] = 2.96785914915211;
   fWeightMatrix0to1[8][4] = -0.241691453162632;
   fWeightMatrix0to1[9][4] = 0.460279416333272;
   fWeightMatrix0to1[10][4] = -0.0407147509512968;
   fWeightMatrix0to1[11][4] = -0.804052543602152;
   fWeightMatrix0to1[12][4] = -0.374779260683038;
   fWeightMatrix0to1[13][4] = 0.767551770953387;
   fWeightMatrix0to1[14][4] = 0.0766121817353455;
   fWeightMatrix0to1[15][4] = 0.14944863320651;
   fWeightMatrix0to1[16][4] = 0.192070609701393;
   fWeightMatrix0to1[17][4] = 0.229789200057751;
   fWeightMatrix0to1[18][4] = -0.164588854885986;
   fWeightMatrix0to1[19][4] = 1.64064310130268;
   fWeightMatrix0to1[20][4] = -0.276767239186055;
   fWeightMatrix0to1[21][4] = -0.963982021915267;
   fWeightMatrix0to1[22][4] = 0.740287125161146;
   fWeightMatrix0to1[23][4] = -1.07728864492097;
   fWeightMatrix0to1[0][5] = -1.73591568003233;
   fWeightMatrix0to1[1][5] = -0.545985185219162;
   fWeightMatrix0to1[2][5] = 0.027746166786239;
   fWeightMatrix0to1[3][5] = 1.90832464399817;
   fWeightMatrix0to1[4][5] = 0.713881394945745;
   fWeightMatrix0to1[5][5] = 1.04689149652961;
   fWeightMatrix0to1[6][5] = -0.193327189874433;
   fWeightMatrix0to1[7][5] = -0.352165417596103;
   fWeightMatrix0to1[8][5] = -1.64097535568449;
   fWeightMatrix0to1[9][5] = -0.697409025921685;
   fWeightMatrix0to1[10][5] = -0.299520490149271;
   fWeightMatrix0to1[11][5] = -1.8185034692311;
   fWeightMatrix0to1[12][5] = 0.377924433737922;
   fWeightMatrix0to1[13][5] = -1.04156131439579;
   fWeightMatrix0to1[14][5] = -0.298582841278521;
   fWeightMatrix0to1[15][5] = 0.630828028095787;
   fWeightMatrix0to1[16][5] = 1.46899450970402;
   fWeightMatrix0to1[17][5] = -1.38392119907839;
   fWeightMatrix0to1[18][5] = 0.0695205600656959;
   fWeightMatrix0to1[19][5] = 0.622370052501144;
   fWeightMatrix0to1[20][5] = 1.38104003542947;
   fWeightMatrix0to1[21][5] = 0.155542242249389;
   fWeightMatrix0to1[22][5] = -0.565786055239477;
   fWeightMatrix0to1[23][5] = -0.138180987403181;
   fWeightMatrix0to1[0][6] = -1.3501620905819;
   fWeightMatrix0to1[1][6] = -0.0437079504550098;
   fWeightMatrix0to1[2][6] = 0.267270475805058;
   fWeightMatrix0to1[3][6] = -0.0748686629349204;
   fWeightMatrix0to1[4][6] = -0.409631259295893;
   fWeightMatrix0to1[5][6] = 0.146930884935468;
   fWeightMatrix0to1[6][6] = -0.122534605276899;
   fWeightMatrix0to1[7][6] = -0.210161610736229;
   fWeightMatrix0to1[8][6] = 0.00923503076330697;
   fWeightMatrix0to1[9][6] = -0.139418054303722;
   fWeightMatrix0to1[10][6] = 0.136539419321537;
   fWeightMatrix0to1[11][6] = 0.284233694850927;
   fWeightMatrix0to1[12][6] = 0.75413387674;
   fWeightMatrix0to1[13][6] = -0.518675812617689;
   fWeightMatrix0to1[14][6] = 0.177901642734783;
   fWeightMatrix0to1[15][6] = -0.142763639345783;
   fWeightMatrix0to1[16][6] = -0.0217906815529876;
   fWeightMatrix0to1[17][6] = -0.111896410884004;
   fWeightMatrix0to1[18][6] = 0.039963909262097;
   fWeightMatrix0to1[19][6] = 0.344645874041034;
   fWeightMatrix0to1[20][6] = 0.268690660839363;
   fWeightMatrix0to1[21][6] = -0.588967429363461;
   fWeightMatrix0to1[22][6] = -0.187513847947403;
   fWeightMatrix0to1[23][6] = -0.318464197705626;
   fWeightMatrix0to1[0][7] = -0.976400809538712;
   fWeightMatrix0to1[1][7] = -0.835365309163859;
   fWeightMatrix0to1[2][7] = 2.09069130229386;
   fWeightMatrix0to1[3][7] = 1.29997003493495;
   fWeightMatrix0to1[4][7] = -0.399081313188866;
   fWeightMatrix0to1[5][7] = 2.63941488252432;
   fWeightMatrix0to1[6][7] = 1.68525417925268;
   fWeightMatrix0to1[7][7] = -1.90282041076216;
   fWeightMatrix0to1[8][7] = 0.165684897028216;
   fWeightMatrix0to1[9][7] = 0.864079410913104;
   fWeightMatrix0to1[10][7] = -0.662913622546873;
   fWeightMatrix0to1[11][7] = -1.70489804494909;
   fWeightMatrix0to1[12][7] = -1.68196778191062;
   fWeightMatrix0to1[13][7] = 1.66876112471477;
   fWeightMatrix0to1[14][7] = 2.69520783302544;
   fWeightMatrix0to1[15][7] = -0.342067850164118;
   fWeightMatrix0to1[16][7] = -0.497062262238044;
   fWeightMatrix0to1[17][7] = -0.072654508590489;
   fWeightMatrix0to1[18][7] = -0.121262662242343;
   fWeightMatrix0to1[19][7] = 0.228099207011431;
   fWeightMatrix0to1[20][7] = 0.453618691224036;
   fWeightMatrix0to1[21][7] = -0.487717911292834;
   fWeightMatrix0to1[22][7] = -1.17126010688028;
   fWeightMatrix0to1[23][7] = 1.01359628513814;
   fWeightMatrix0to1[0][8] = 1.4493490357067;
   fWeightMatrix0to1[1][8] = 0.552792305774604;
   fWeightMatrix0to1[2][8] = -0.247686436989596;
   fWeightMatrix0to1[3][8] = -0.195865920065144;
   fWeightMatrix0to1[4][8] = -2.05212591272241;
   fWeightMatrix0to1[5][8] = 0.276715282819017;
   fWeightMatrix0to1[6][8] = 0.288826510204175;
   fWeightMatrix0to1[7][8] = -2.62402036317757;
   fWeightMatrix0to1[8][8] = -1.35262868968243;
   fWeightMatrix0to1[9][8] = 1.80506571104532;
   fWeightMatrix0to1[10][8] = 1.54496736863002;
   fWeightMatrix0to1[11][8] = -1.96401927569817;
   fWeightMatrix0to1[12][8] = 1.14169740260499;
   fWeightMatrix0to1[13][8] = 0.705979190544334;
   fWeightMatrix0to1[14][8] = -1.58145655233744;
   fWeightMatrix0to1[15][8] = 0.442477062202657;
   fWeightMatrix0to1[16][8] = 1.72894119845686;
   fWeightMatrix0to1[17][8] = 1.12416033193153;
   fWeightMatrix0to1[18][8] = 4.3402242456198;
   fWeightMatrix0to1[19][8] = -0.170995906784228;
   fWeightMatrix0to1[20][8] = -2.48125014007258;
   fWeightMatrix0to1[21][8] = -0.934677270249064;
   fWeightMatrix0to1[22][8] = 1.28552732314617;
   fWeightMatrix0to1[23][8] = 1.56609602170401;
   fWeightMatrix0to1[0][9] = 0.764233663741359;
   fWeightMatrix0to1[1][9] = -0.00462695090331086;
   fWeightMatrix0to1[2][9] = 0.577390409466777;
   fWeightMatrix0to1[3][9] = -1.16895781057359;
   fWeightMatrix0to1[4][9] = -1.29752513498689;
   fWeightMatrix0to1[5][9] = -3.06416436025946;
   fWeightMatrix0to1[6][9] = -1.50691182743835;
   fWeightMatrix0to1[7][9] = 0.987570389764258;
   fWeightMatrix0to1[8][9] = -0.0388983554565663;
   fWeightMatrix0to1[9][9] = -0.823304503959049;
   fWeightMatrix0to1[10][9] = 0.568371318214516;
   fWeightMatrix0to1[11][9] = -0.142403469455542;
   fWeightMatrix0to1[12][9] = -1.66084179429621;
   fWeightMatrix0to1[13][9] = -0.593456167054867;
   fWeightMatrix0to1[14][9] = 1.12785096418611;
   fWeightMatrix0to1[15][9] = 0.129393711890194;
   fWeightMatrix0to1[16][9] = 0.534038990653873;
   fWeightMatrix0to1[17][9] = -0.0222778212550812;
   fWeightMatrix0to1[18][9] = 0.722817003823676;
   fWeightMatrix0to1[19][9] = -0.306640503088161;
   fWeightMatrix0to1[20][9] = -0.456684215035929;
   fWeightMatrix0to1[21][9] = 0.0722475151426517;
   fWeightMatrix0to1[22][9] = -1.30505852807862;
   fWeightMatrix0to1[23][9] = -0.633422673242454;
   fWeightMatrix0to1[0][10] = -1.92970369639464;
   fWeightMatrix0to1[1][10] = -0.9089275882643;
   fWeightMatrix0to1[2][10] = -2.04430439285709;
   fWeightMatrix0to1[3][10] = -0.968793104900233;
   fWeightMatrix0to1[4][10] = -1.89284940041489;
   fWeightMatrix0to1[5][10] = 1.06228580859545;
   fWeightMatrix0to1[6][10] = -1.06449409096409;
   fWeightMatrix0to1[7][10] = -2.18727420937822;
   fWeightMatrix0to1[8][10] = 2.13566214513056;
   fWeightMatrix0to1[9][10] = 3.28378037722562;
   fWeightMatrix0to1[10][10] = -0.484997233205924;
   fWeightMatrix0to1[11][10] = -1.07266566858793;
   fWeightMatrix0to1[12][10] = -0.149258703742394;
   fWeightMatrix0to1[13][10] = 1.90196046197778;
   fWeightMatrix0to1[14][10] = -0.144346968528582;
   fWeightMatrix0to1[15][10] = -0.57055858831473;
   fWeightMatrix0to1[16][10] = -1.89395078814777;
   fWeightMatrix0to1[17][10] = -1.08310602559251;
   fWeightMatrix0to1[18][10] = 0.979780839033573;
   fWeightMatrix0to1[19][10] = -1.31408510664715;
   fWeightMatrix0to1[20][10] = 0.191778526617865;
   fWeightMatrix0to1[21][10] = 0.269541091082784;
   fWeightMatrix0to1[22][10] = 0.950830316693997;
   fWeightMatrix0to1[23][10] = -0.31275541800492;
   fWeightMatrix0to1[0][11] = 0.137975188212505;
   fWeightMatrix0to1[1][11] = -0.327637715168272;
   fWeightMatrix0to1[2][11] = 0.428246023242377;
   fWeightMatrix0to1[3][11] = 1.35646013391651;
   fWeightMatrix0to1[4][11] = 1.18844051635716;
   fWeightMatrix0to1[5][11] = 1.70072502578231;
   fWeightMatrix0to1[6][11] = -1.51996749413533;
   fWeightMatrix0to1[7][11] = 0.0204003936950582;
   fWeightMatrix0to1[8][11] = 1.87915622983728;
   fWeightMatrix0to1[9][11] = -2.7130050682471;
   fWeightMatrix0to1[10][11] = -0.199388203618526;
   fWeightMatrix0to1[11][11] = -0.292211455999846;
   fWeightMatrix0to1[12][11] = 0.983921100701189;
   fWeightMatrix0to1[13][11] = -0.333683765146017;
   fWeightMatrix0to1[14][11] = -0.050186700686872;
   fWeightMatrix0to1[15][11] = -0.0663253883774095;
   fWeightMatrix0to1[16][11] = 0.193316098692128;
   fWeightMatrix0to1[17][11] = 0.063967136945906;
   fWeightMatrix0to1[18][11] = -3.64812960845473;
   fWeightMatrix0to1[19][11] = -0.0399890160081512;
   fWeightMatrix0to1[20][11] = -0.803143332877547;
   fWeightMatrix0to1[21][11] = -1.38326909491232;
   fWeightMatrix0to1[22][11] = -1.96933921402269;
   fWeightMatrix0to1[23][11] = 0.152348174520661;
   fWeightMatrix0to1[0][12] = -1.98279179185724;
   fWeightMatrix0to1[1][12] = 0.848954987364258;
   fWeightMatrix0to1[2][12] = -1.24669870364964;
   fWeightMatrix0to1[3][12] = 1.68618687775836;
   fWeightMatrix0to1[4][12] = -1.15457976784579;
   fWeightMatrix0to1[5][12] = 0.634932571824067;
   fWeightMatrix0to1[6][12] = 0.118428555522871;
   fWeightMatrix0to1[7][12] = -1.33464056433239;
   fWeightMatrix0to1[8][12] = -0.538800018429003;
   fWeightMatrix0to1[9][12] = 1.82132910477053;
   fWeightMatrix0to1[10][12] = -3.25405276006591;
   fWeightMatrix0to1[11][12] = -1.48054358112341;
   fWeightMatrix0to1[12][12] = -2.14084591355573;
   fWeightMatrix0to1[13][12] = -1.84233432334487;
   fWeightMatrix0to1[14][12] = 2.29135166992086;
   fWeightMatrix0to1[15][12] = -0.394038426767188;
   fWeightMatrix0to1[16][12] = -0.438385553899367;
   fWeightMatrix0to1[17][12] = -0.573590972112873;
   fWeightMatrix0to1[18][12] = -5.556971728852;
   fWeightMatrix0to1[19][12] = -2.59867524592221;
   fWeightMatrix0to1[20][12] = -0.369111574742803;
   fWeightMatrix0to1[21][12] = -1.38150309546441;
   fWeightMatrix0to1[22][12] = 1.21129406873584;
   fWeightMatrix0to1[23][12] = -2.02889469441262;
   fWeightMatrix0to1[0][13] = -1.3257259521774;
   fWeightMatrix0to1[1][13] = 0.494302644430262;
   fWeightMatrix0to1[2][13] = 0.470154372086371;
   fWeightMatrix0to1[3][13] = -0.0412867187899353;
   fWeightMatrix0to1[4][13] = 1.8882755790113;
   fWeightMatrix0to1[5][13] = -0.295621161356816;
   fWeightMatrix0to1[6][13] = 0.869763172727124;
   fWeightMatrix0to1[7][13] = 1.19749355353525;
   fWeightMatrix0to1[8][13] = 0.0562168373373749;
   fWeightMatrix0to1[9][13] = 0.148995748811339;
   fWeightMatrix0to1[10][13] = 0.246843467756418;
   fWeightMatrix0to1[11][13] = -1.18240332278683;
   fWeightMatrix0to1[12][13] = 0.133978336373872;
   fWeightMatrix0to1[13][13] = 0.711609806531277;
   fWeightMatrix0to1[14][13] = 1.30392192328469;
   fWeightMatrix0to1[15][13] = 0.981210692774331;
   fWeightMatrix0to1[16][13] = -1.25967425256193;
   fWeightMatrix0to1[17][13] = 0.566434410847488;
   fWeightMatrix0to1[18][13] = -0.12148904380932;
   fWeightMatrix0to1[19][13] = 0.268702844148566;
   fWeightMatrix0to1[20][13] = -1.87888014021595;
   fWeightMatrix0to1[21][13] = -1.84539771924318;
   fWeightMatrix0to1[22][13] = -0.749669326890944;
   fWeightMatrix0to1[23][13] = 0.510532355365236;
   fWeightMatrix0to1[0][14] = 0.59100535465076;
   fWeightMatrix0to1[1][14] = 1.4404498896448;
   fWeightMatrix0to1[2][14] = 0.999028518588279;
   fWeightMatrix0to1[3][14] = -0.782403528185103;
   fWeightMatrix0to1[4][14] = -0.674439201747258;
   fWeightMatrix0to1[5][14] = 1.14627029777367;
   fWeightMatrix0to1[6][14] = 2.15230473235633;
   fWeightMatrix0to1[7][14] = -0.289965682166845;
   fWeightMatrix0to1[8][14] = 0.892373792176959;
   fWeightMatrix0to1[9][14] = -3.12162661196248;
   fWeightMatrix0to1[10][14] = -1.89927414416162;
   fWeightMatrix0to1[11][14] = 0.0348756936100841;
   fWeightMatrix0to1[12][14] = 0.610350393926136;
   fWeightMatrix0to1[13][14] = -1.29183857599602;
   fWeightMatrix0to1[14][14] = 2.30042462572544;
   fWeightMatrix0to1[15][14] = 1.28398577029821;
   fWeightMatrix0to1[16][14] = 0.591352782367724;
   fWeightMatrix0to1[17][14] = -0.215855428783541;
   fWeightMatrix0to1[18][14] = -4.76738122509906;
   fWeightMatrix0to1[19][14] = -1.58241033729925;
   fWeightMatrix0to1[20][14] = -1.09517423684759;
   fWeightMatrix0to1[21][14] = 1.06772132888991;
   fWeightMatrix0to1[22][14] = -0.47792501851742;
   fWeightMatrix0to1[23][14] = -1.12726332935718;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.516564672457599;
   fWeightMatrix1to2[0][1] = 0.171037672659346;
   fWeightMatrix1to2[0][2] = -0.135835026118965;
   fWeightMatrix1to2[0][3] = -0.203652797366355;
   fWeightMatrix1to2[0][4] = 1.16829654901624;
   fWeightMatrix1to2[0][5] = -0.145121957865379;
   fWeightMatrix1to2[0][6] = -0.495583020303242;
   fWeightMatrix1to2[0][7] = -0.176758539083073;
   fWeightMatrix1to2[0][8] = 0.288192573178059;
   fWeightMatrix1to2[0][9] = -0.324535351204008;
   fWeightMatrix1to2[0][10] = 0.167946865978453;
   fWeightMatrix1to2[0][11] = -1.26307535193941;
   fWeightMatrix1to2[0][12] = 0.0519014006248663;
   fWeightMatrix1to2[0][13] = 0.332625545460808;
   fWeightMatrix1to2[0][14] = -0.323134382198477;
   fWeightMatrix1to2[0][15] = -0.126630174216571;
   fWeightMatrix1to2[0][16] = 0.0964662809509504;
   fWeightMatrix1to2[0][17] = -0.0541761585098409;
   fWeightMatrix1to2[0][18] = 0.422408019426403;
   fWeightMatrix1to2[0][19] = 0.288022626270475;
   fWeightMatrix1to2[0][20] = -0.210024502943791;
   fWeightMatrix1to2[0][21] = -0.520657310653179;
   fWeightMatrix1to2[0][22] = -0.352597669193136;
   fWeightMatrix1to2[0][23] = 0.150043343901822;
   fWeightMatrix1to2[0][24] = 1.10424553614666;
}

inline double ReadMLPTuned::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPTuned::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPTuned::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPTuned::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPTuned::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 20.0105838776;
   fMax_1[0][0] = 724.193359375;
   fMin_1[1][0] = 20.0613365173;
   fMax_1[1][0] = 1141.5065918;
   fMin_1[2][0] = 20.0105838776;
   fMax_1[2][0] = 1141.5065918;
   fMin_1[0][1] = 20.0018119812;
   fMax_1[0][1] = 779.356506348;
   fMin_1[1][1] = 20.002363205;
   fMax_1[1][1] = 618.51574707;
   fMin_1[2][1] = 20.0018119812;
   fMax_1[2][1] = 779.356506348;
   fMin_1[0][2] = 22.5726528168;
   fMax_1[0][2] = 825.268127441;
   fMin_1[1][2] = 28.7160816193;
   fMax_1[1][2] = 948.211181641;
   fMin_1[2][2] = 22.5726528168;
   fMax_1[2][2] = 948.211181641;
   fMin_1[0][3] = 9.35392189026;
   fMax_1[0][3] = 383.950286865;
   fMin_1[1][3] = 20.0910205841;
   fMax_1[1][3] = 503.708984375;
   fMin_1[2][3] = 9.35392189026;
   fMax_1[2][3] = 503.708984375;
   fMin_1[0][4] = 0.185397148132;
   fMax_1[0][4] = 454.188110352;
   fMin_1[1][4] = 0.591240763664;
   fMax_1[1][4] = 743.405090332;
   fMin_1[2][4] = 0.185397148132;
   fMax_1[2][4] = 743.405090332;
   fMin_1[0][5] = 0.0101556777954;
   fMax_1[0][5] = 660.794494629;
   fMin_1[1][5] = 0.0342635512352;
   fMax_1[1][5] = 855.639770508;
   fMin_1[2][5] = 0.0101556777954;
   fMax_1[2][5] = 855.639770508;
   fMin_1[0][6] = 0.000127077102661;
   fMax_1[0][6] = 6.25128030777;
   fMin_1[1][6] = 2.95639038086e-05;
   fMax_1[1][6] = 6.28109359741;
   fMin_1[2][6] = 2.95639038086e-05;
   fMax_1[2][6] = 6.28109359741;
   fMin_1[0][7] = 0.284361332655;
   fMax_1[0][7] = 5.96390295029;
   fMin_1[1][7] = 0.31516379118;
   fMax_1[1][7] = 5.02747869492;
   fMin_1[2][7] = 0.284361332655;
   fMax_1[2][7] = 5.96390295029;
   fMin_1[0][8] = 0.429002255201;
   fMax_1[0][8] = 457.230957031;
   fMin_1[1][8] = 0.455825328827;
   fMax_1[1][8] = 419.443969727;
   fMin_1[2][8] = 0.429002255201;
   fMax_1[2][8] = 457.230957031;
   fMin_1[0][9] = 0.353569626808;
   fMax_1[0][9] = 4.39490652084;
   fMin_1[1][9] = 0.322578668594;
   fMax_1[1][9] = 4.48389148712;
   fMin_1[2][9] = 0.322578668594;
   fMax_1[2][9] = 4.48389148712;
   fMin_1[0][10] = 0.63454002142;
   fMax_1[0][10] = 1511.38464355;
   fMin_1[1][10] = 0.560641825199;
   fMax_1[1][10] = 799.379882812;
   fMin_1[2][10] = 0.560641825199;
   fMax_1[2][10] = 1511.38464355;
   fMin_1[0][11] = 0.338914036751;
   fMax_1[0][11] = 5.23438882828;
   fMin_1[1][11] = 0.331655144691;
   fMax_1[1][11] = 5.43578577042;
   fMin_1[2][11] = 0.331655144691;
   fMax_1[2][11] = 5.43578577042;
   fMin_1[0][12] = 13.5097150803;
   fMax_1[0][12] = 1883.72412109;
   fMin_1[1][12] = 11.8016901016;
   fMax_1[1][12] = 2381.72802734;
   fMin_1[2][12] = 11.8016901016;
   fMax_1[2][12] = 2381.72802734;
   fMin_1[0][13] = 0.00800320412964;
   fMax_1[0][13] = 460.327148438;
   fMin_1[1][13] = 0.00157363095786;
   fMax_1[1][13] = 535.521972656;
   fMin_1[2][13] = 0.00157363095786;
   fMax_1[2][13] = 535.521972656;
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 14;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<14;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
