// Class: ReadMLPTuned
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPTuned
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : ineuteli
Date           : Thu Nov 26 21:49:17 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.11.2.el6.x86_64 #1 SMP Wed Mar 26 09:39:43 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/ineuteli/phase2/CMSSW_5_3_24/src/Delphes/plots
Training events: 20731
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
HiddenLayers: "N+10" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
NCycles: "500" [Number of training cycles]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 20
Njets20                       Njets20                       Njets20                       Njets20                                                         'F'    [4,10]
Nbjets30                      Nbjets30                      Nbjets30                      Nbjets30                                                        'F'    [2,5]
jet1Pt                        jet1Pt                        jet1Pt                        jet1Pt                                                          'F'    [20.345867157,989.239624023]
jet2Pt                        jet2Pt                        jet2Pt                        jet2Pt                                                          'F'    [20.0002479553,699.98260498]
bjet1Pt                       bjet1Pt                       bjet1Pt                       bjet1Pt                                                         'F'    [30.8286094666,904.02545166]
bjet2Pt                       bjet2Pt                       bjet2Pt                       bjet2Pt                                                         'F'    [30.0086250305,280.001068115]
leptonPt                      leptonPt                      leptonPt                      leptonPt                                                        'F'    [20.0040016174,480.95715332]
MET                           MET                           MET                           MET                                                             'F'    [20.003408432,660.794494629]
DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                                                      'F'    [0.267349809408,5.96390295029]
DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                                                      'F'    [0.411826014519,6.17678260803]
DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                                                      'F'    [0.514531254768,5.3588013649]
DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                                                      'F'    [0.331118583679,4.68913269043]
DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                                                      'F'    [0.383479446173,3.09936523438]
DeltaR_jjl_leading            DeltaR_jjl_leading            DeltaR_jjl_leading            DeltaR_jjl_leading                                              'F'    [0.0128494994715,7.59379291534]
DeltaPhi_METl                 DeltaPhi_METl                 DeltaPhi_METl                 DeltaPhi_METl                                                   'F'    [9.36985015869e-05,6.23410224915]
M_bb_closest                  M_bb_closest                  M_bb_closest                  M_bb_closest                                                    'F'    [60.0008811951,159.999816895]
M_jjb_leading                 M_jjb_leading                 M_jjb_leading                 M_jjb_leading                                                   'F'    [35.0392456055,3519.41210938]
M_blnu                        M_blnu                        M_blnu                        M_blnu                                                          'F'    [87.2848510742,4438.00146484]
MT_lnu                        MT_lnu                        MT_lnu                        MT_lnu                                                          'F'    [0.00475058425218,535.521972656]
MT_jjlnu                      MT_jjlnu                      MT_jjlnu                      MT_jjlnu                                                        'F'    [0.000171629610122,1580.10388184]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPTuned : public IClassifierReader {

 public:

   // constructor
   ReadMLPTuned( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPTuned" ),
        fNvars( 20 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Njets20", "Nbjets30", "jet1Pt", "jet2Pt", "bjet1Pt", "bjet2Pt", "leptonPt", "MET", "DeltaR_j1l", "DeltaR_j2l", "DeltaR_b1l", "DeltaR_b2l", "DeltaR_bb1", "DeltaR_jjl_leading", "DeltaPhi_METl", "M_bb_closest", "M_jjb_leading", "M_blnu", "MT_lnu", "MT_jjlnu" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 0.99999988079071;
      fVmin[15] = -1;
      fVmax[15] = 1;
      fVmin[16] = -1;
      fVmax[16] = 1;
      fVmin[17] = -1;
      fVmax[17] = 1;
      fVmin[18] = -1;
      fVmax[18] = 1;
      fVmin[19] = -1;
      fVmax[19] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPTuned() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][20];
   double fMax_1[3][20];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[20];
   double fVmax[20];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[20];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[31][21];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][31];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPTuned::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 21; fWeights[0] = new double[21]; 
   fLayerSize[1] = 31; fWeights[1] = new double[31]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.579478177282816;
   fWeightMatrix0to1[1][0] = -0.289406368268596;
   fWeightMatrix0to1[2][0] = -0.51304093638381;
   fWeightMatrix0to1[3][0] = 1.49699305722598;
   fWeightMatrix0to1[4][0] = -1.49301124300401;
   fWeightMatrix0to1[5][0] = -0.333276246823266;
   fWeightMatrix0to1[6][0] = -0.117051330267996;
   fWeightMatrix0to1[7][0] = 1.04343866971679;
   fWeightMatrix0to1[8][0] = -1.29407858362754;
   fWeightMatrix0to1[9][0] = -1.03256696209929;
   fWeightMatrix0to1[10][0] = -0.709150414881343;
   fWeightMatrix0to1[11][0] = 0.17945081689993;
   fWeightMatrix0to1[12][0] = -1.25228304177101;
   fWeightMatrix0to1[13][0] = 0.587968511073512;
   fWeightMatrix0to1[14][0] = -0.126856540795092;
   fWeightMatrix0to1[15][0] = 0.507549146896483;
   fWeightMatrix0to1[16][0] = -0.601695029615181;
   fWeightMatrix0to1[17][0] = 0.282962679219074;
   fWeightMatrix0to1[18][0] = 0.00419456362342059;
   fWeightMatrix0to1[19][0] = 0.409606179455979;
   fWeightMatrix0to1[20][0] = -0.338299462842792;
   fWeightMatrix0to1[21][0] = -0.550500007821803;
   fWeightMatrix0to1[22][0] = 1.73603110157198;
   fWeightMatrix0to1[23][0] = 0.137981127406722;
   fWeightMatrix0to1[24][0] = 0.0136752928284655;
   fWeightMatrix0to1[25][0] = -0.324343757907274;
   fWeightMatrix0to1[26][0] = 1.62068132618048;
   fWeightMatrix0to1[27][0] = -0.471481533629829;
   fWeightMatrix0to1[28][0] = -1.07858808902678;
   fWeightMatrix0to1[29][0] = 0.125792087298677;
   fWeightMatrix0to1[0][1] = -0.554302913345515;
   fWeightMatrix0to1[1][1] = 2.20556641473685;
   fWeightMatrix0to1[2][1] = -0.420063099470721;
   fWeightMatrix0to1[3][1] = 0.197699377061812;
   fWeightMatrix0to1[4][1] = 0.695941322223152;
   fWeightMatrix0to1[5][1] = -1.09003608016276;
   fWeightMatrix0to1[6][1] = -1.23285379976123;
   fWeightMatrix0to1[7][1] = 0.878291445597023;
   fWeightMatrix0to1[8][1] = -0.931924332900005;
   fWeightMatrix0to1[9][1] = 0.955008284346419;
   fWeightMatrix0to1[10][1] = 0.650708934574808;
   fWeightMatrix0to1[11][1] = 0.703556005431003;
   fWeightMatrix0to1[12][1] = 0.955940262794838;
   fWeightMatrix0to1[13][1] = 1.41631234015851;
   fWeightMatrix0to1[14][1] = -0.486271830247877;
   fWeightMatrix0to1[15][1] = -1.90031133848964;
   fWeightMatrix0to1[16][1] = 0.218500585589818;
   fWeightMatrix0to1[17][1] = 0.258428641574659;
   fWeightMatrix0to1[18][1] = 1.13752237865945;
   fWeightMatrix0to1[19][1] = 1.05195463982969;
   fWeightMatrix0to1[20][1] = 0.0304389479484475;
   fWeightMatrix0to1[21][1] = 1.41347438289346;
   fWeightMatrix0to1[22][1] = -0.530688662283172;
   fWeightMatrix0to1[23][1] = 0.528352933472349;
   fWeightMatrix0to1[24][1] = -1.05495939497452;
   fWeightMatrix0to1[25][1] = -0.448232038101839;
   fWeightMatrix0to1[26][1] = -1.20298922533207;
   fWeightMatrix0to1[27][1] = -1.08127773355973;
   fWeightMatrix0to1[28][1] = 1.58518431147279;
   fWeightMatrix0to1[29][1] = 0.694389855891274;
   fWeightMatrix0to1[0][2] = -2.01973253878863;
   fWeightMatrix0to1[1][2] = 0.372118444713713;
   fWeightMatrix0to1[2][2] = -0.69712554757655;
   fWeightMatrix0to1[3][2] = 1.6283019576197;
   fWeightMatrix0to1[4][2] = 1.96223897461401;
   fWeightMatrix0to1[5][2] = -0.907171111133095;
   fWeightMatrix0to1[6][2] = 0.720244891155514;
   fWeightMatrix0to1[7][2] = -1.2531002333764;
   fWeightMatrix0to1[8][2] = 0.951566258021356;
   fWeightMatrix0to1[9][2] = -0.840354178450343;
   fWeightMatrix0to1[10][2] = -0.762722817741083;
   fWeightMatrix0to1[11][2] = -1.53183729158325;
   fWeightMatrix0to1[12][2] = 0.379262591290129;
   fWeightMatrix0to1[13][2] = 2.62980673254521;
   fWeightMatrix0to1[14][2] = 1.63023503662138;
   fWeightMatrix0to1[15][2] = -0.300321137000262;
   fWeightMatrix0to1[16][2] = -1.86112026981272;
   fWeightMatrix0to1[17][2] = -2.04712450186659;
   fWeightMatrix0to1[18][2] = 1.02674188781859;
   fWeightMatrix0to1[19][2] = 0.305959254118001;
   fWeightMatrix0to1[20][2] = 2.39247338569006;
   fWeightMatrix0to1[21][2] = 0.660117612130762;
   fWeightMatrix0to1[22][2] = 1.70665518499249;
   fWeightMatrix0to1[23][2] = -0.605829135814871;
   fWeightMatrix0to1[24][2] = -0.552076241282956;
   fWeightMatrix0to1[25][2] = -0.0365340082757321;
   fWeightMatrix0to1[26][2] = 0.790013261707119;
   fWeightMatrix0to1[27][2] = -1.34356327643496;
   fWeightMatrix0to1[28][2] = -1.74417779090755;
   fWeightMatrix0to1[29][2] = -1.71976408758455;
   fWeightMatrix0to1[0][3] = -0.196834310703519;
   fWeightMatrix0to1[1][3] = 0.586853480784634;
   fWeightMatrix0to1[2][3] = 1.7617042140595;
   fWeightMatrix0to1[3][3] = -0.458757044525137;
   fWeightMatrix0to1[4][3] = -0.56696608696814;
   fWeightMatrix0to1[5][3] = -0.118183342068575;
   fWeightMatrix0to1[6][3] = -0.415266199627757;
   fWeightMatrix0to1[7][3] = -1.50573088957804;
   fWeightMatrix0to1[8][3] = -1.27863436349745;
   fWeightMatrix0to1[9][3] = -0.403165609440832;
   fWeightMatrix0to1[10][3] = -2.02752343695412;
   fWeightMatrix0to1[11][3] = -1.73233836296268;
   fWeightMatrix0to1[12][3] = 0.181317933413137;
   fWeightMatrix0to1[13][3] = 2.15639690725346;
   fWeightMatrix0to1[14][3] = -0.963023178917053;
   fWeightMatrix0to1[15][3] = 1.54041880074879;
   fWeightMatrix0to1[16][3] = -1.19259301812589;
   fWeightMatrix0to1[17][3] = -0.883290968576728;
   fWeightMatrix0to1[18][3] = 0.064284951554891;
   fWeightMatrix0to1[19][3] = 0.883880633234641;
   fWeightMatrix0to1[20][3] = -1.50510757371164;
   fWeightMatrix0to1[21][3] = 0.428425915037738;
   fWeightMatrix0to1[22][3] = 0.830443493737729;
   fWeightMatrix0to1[23][3] = 0.541515940649895;
   fWeightMatrix0to1[24][3] = -1.17326400350358;
   fWeightMatrix0to1[25][3] = 1.87171593783707;
   fWeightMatrix0to1[26][3] = 0.168772556723292;
   fWeightMatrix0to1[27][3] = -1.35923282568649;
   fWeightMatrix0to1[28][3] = 0.87603855799584;
   fWeightMatrix0to1[29][3] = -1.08354234088626;
   fWeightMatrix0to1[0][4] = -1.61391072954726;
   fWeightMatrix0to1[1][4] = -0.0664901442913822;
   fWeightMatrix0to1[2][4] = 0.360787612086155;
   fWeightMatrix0to1[3][4] = 2.12683781937152;
   fWeightMatrix0to1[4][4] = 1.08354679443829;
   fWeightMatrix0to1[5][4] = 1.41929961701328;
   fWeightMatrix0to1[6][4] = -0.676372624712187;
   fWeightMatrix0to1[7][4] = 0.205461117141925;
   fWeightMatrix0to1[8][4] = -1.46843448652299;
   fWeightMatrix0to1[9][4] = 0.74388903176672;
   fWeightMatrix0to1[10][4] = 1.18639292085862;
   fWeightMatrix0to1[11][4] = -1.83742143777735;
   fWeightMatrix0to1[12][4] = 0.158753084252735;
   fWeightMatrix0to1[13][4] = -3.68402077708038;
   fWeightMatrix0to1[14][4] = 0.256499754553282;
   fWeightMatrix0to1[15][4] = 1.07785551471008;
   fWeightMatrix0to1[16][4] = 1.31799398328001;
   fWeightMatrix0to1[17][4] = -1.19919959736658;
   fWeightMatrix0to1[18][4] = 0.154809416176023;
   fWeightMatrix0to1[19][4] = 1.80567829025631;
   fWeightMatrix0to1[20][4] = 2.73865987958329;
   fWeightMatrix0to1[21][4] = 0.248856928243328;
   fWeightMatrix0to1[22][4] = -0.898007258720464;
   fWeightMatrix0to1[23][4] = -0.385160982852973;
   fWeightMatrix0to1[24][4] = -1.2235810394471;
   fWeightMatrix0to1[25][4] = 1.78673212203228;
   fWeightMatrix0to1[26][4] = 1.17869987558048;
   fWeightMatrix0to1[27][4] = -0.298125784375893;
   fWeightMatrix0to1[28][4] = -0.456813443859179;
   fWeightMatrix0to1[29][4] = 0.163649497833023;
   fWeightMatrix0to1[0][5] = 0.150668102551793;
   fWeightMatrix0to1[1][5] = -0.626580609563905;
   fWeightMatrix0to1[2][5] = 1.45166504874382;
   fWeightMatrix0to1[3][5] = -0.393630326727839;
   fWeightMatrix0to1[4][5] = -0.0961304074308344;
   fWeightMatrix0to1[5][5] = 0.246019281775174;
   fWeightMatrix0to1[6][5] = 0.872384451338023;
   fWeightMatrix0to1[7][5] = 0.787866008617731;
   fWeightMatrix0to1[8][5] = 1.06353811478691;
   fWeightMatrix0to1[9][5] = -1.63578187188862;
   fWeightMatrix0to1[10][5] = 0.347927219948703;
   fWeightMatrix0to1[11][5] = 0.905317189252028;
   fWeightMatrix0to1[12][5] = 0.263480931116467;
   fWeightMatrix0to1[13][5] = -0.577101041751001;
   fWeightMatrix0to1[14][5] = 1.12625025262803;
   fWeightMatrix0to1[15][5] = -0.743119971465018;
   fWeightMatrix0to1[16][5] = -0.954825175777878;
   fWeightMatrix0to1[17][5] = 1.58799866211754;
   fWeightMatrix0to1[18][5] = -0.696063535014556;
   fWeightMatrix0to1[19][5] = -0.0378377912745133;
   fWeightMatrix0to1[20][5] = 1.10145994955005;
   fWeightMatrix0to1[21][5] = 0.911944146582933;
   fWeightMatrix0to1[22][5] = -0.0145159402578722;
   fWeightMatrix0to1[23][5] = 1.11576134064672;
   fWeightMatrix0to1[24][5] = 1.87985098364337;
   fWeightMatrix0to1[25][5] = -1.25257901984263;
   fWeightMatrix0to1[26][5] = 0.706755393927464;
   fWeightMatrix0to1[27][5] = -0.739124083083354;
   fWeightMatrix0to1[28][5] = 0.843002470197566;
   fWeightMatrix0to1[29][5] = -1.69555828499185;
   fWeightMatrix0to1[0][6] = -0.256750844423634;
   fWeightMatrix0to1[1][6] = 0.70556183550471;
   fWeightMatrix0to1[2][6] = 1.65888555535299;
   fWeightMatrix0to1[3][6] = -0.683218043235514;
   fWeightMatrix0to1[4][6] = 0.547309377674954;
   fWeightMatrix0to1[5][6] = -0.116631724023925;
   fWeightMatrix0to1[6][6] = 0.499040343867733;
   fWeightMatrix0to1[7][6] = 1.56920072422688;
   fWeightMatrix0to1[8][6] = -0.26914855679106;
   fWeightMatrix0to1[9][6] = -0.479203952040724;
   fWeightMatrix0to1[10][6] = 0.407637332291179;
   fWeightMatrix0to1[11][6] = 1.2131262554297;
   fWeightMatrix0to1[12][6] = 1.01706389547264;
   fWeightMatrix0to1[13][6] = 0.247092468915448;
   fWeightMatrix0to1[14][6] = 0.51013098236336;
   fWeightMatrix0to1[15][6] = -0.871064305844803;
   fWeightMatrix0to1[16][6] = -2.17301206457379;
   fWeightMatrix0to1[17][6] = 0.871877971749951;
   fWeightMatrix0to1[18][6] = 0.340656244230891;
   fWeightMatrix0to1[19][6] = -2.01440173869431;
   fWeightMatrix0to1[20][6] = 0.265525625773643;
   fWeightMatrix0to1[21][6] = 0.531715780941247;
   fWeightMatrix0to1[22][6] = 0.670796805116363;
   fWeightMatrix0to1[23][6] = -1.53703884290447;
   fWeightMatrix0to1[24][6] = 1.34014236173158;
   fWeightMatrix0to1[25][6] = 0.72347120741761;
   fWeightMatrix0to1[26][6] = -0.566115275195996;
   fWeightMatrix0to1[27][6] = 0.156848165033691;
   fWeightMatrix0to1[28][6] = 1.93957738685801;
   fWeightMatrix0to1[29][6] = 1.06728335532704;
   fWeightMatrix0to1[0][7] = -0.391135888434544;
   fWeightMatrix0to1[1][7] = 0.58101357973045;
   fWeightMatrix0to1[2][7] = -1.17626650135252;
   fWeightMatrix0to1[3][7] = -0.574107027532803;
   fWeightMatrix0to1[4][7] = 2.02847643154208;
   fWeightMatrix0to1[5][7] = 0.21853076978881;
   fWeightMatrix0to1[6][7] = 0.635277381221447;
   fWeightMatrix0to1[7][7] = 0.251603562160824;
   fWeightMatrix0to1[8][7] = 2.01654638257011;
   fWeightMatrix0to1[9][7] = -2.00790832582717;
   fWeightMatrix0to1[10][7] = -1.33098131245192;
   fWeightMatrix0to1[11][7] = -0.363495842219787;
   fWeightMatrix0to1[12][7] = -1.87859092556147;
   fWeightMatrix0to1[13][7] = 0.576978376787048;
   fWeightMatrix0to1[14][7] = 1.77089867984263;
   fWeightMatrix0to1[15][7] = -1.13178304875309;
   fWeightMatrix0to1[16][7] = 0.461532134523295;
   fWeightMatrix0to1[17][7] = 0.505754664906043;
   fWeightMatrix0to1[18][7] = -0.252098467777148;
   fWeightMatrix0to1[19][7] = -0.208710508946875;
   fWeightMatrix0to1[20][7] = 0.946522078531789;
   fWeightMatrix0to1[21][7] = 0.392770598898591;
   fWeightMatrix0to1[22][7] = 1.16667237214308;
   fWeightMatrix0to1[23][7] = -0.941771567858573;
   fWeightMatrix0to1[24][7] = 1.59666737234542;
   fWeightMatrix0to1[25][7] = -1.28967149746975;
   fWeightMatrix0to1[26][7] = 1.00717918132556;
   fWeightMatrix0to1[27][7] = -0.330244939959933;
   fWeightMatrix0to1[28][7] = -1.21532802848617;
   fWeightMatrix0to1[29][7] = -1.29943693463989;
   fWeightMatrix0to1[0][8] = -0.777055204083069;
   fWeightMatrix0to1[1][8] = 1.0424087084439;
   fWeightMatrix0to1[2][8] = -3.22750257834712;
   fWeightMatrix0to1[3][8] = -0.752534524937817;
   fWeightMatrix0to1[4][8] = -1.30231166261471;
   fWeightMatrix0to1[5][8] = -0.674053467779566;
   fWeightMatrix0to1[6][8] = -1.22147884845239;
   fWeightMatrix0to1[7][8] = -1.36173644664619;
   fWeightMatrix0to1[8][8] = 1.50966834605729;
   fWeightMatrix0to1[9][8] = -0.91101473004211;
   fWeightMatrix0to1[10][8] = 1.45281602747088;
   fWeightMatrix0to1[11][8] = -1.00439459925859;
   fWeightMatrix0to1[12][8] = 0.27589892841761;
   fWeightMatrix0to1[13][8] = 1.62863514380991;
   fWeightMatrix0to1[14][8] = 1.44664792110463;
   fWeightMatrix0to1[15][8] = -0.869963869982767;
   fWeightMatrix0to1[16][8] = -1.79248944891091;
   fWeightMatrix0to1[17][8] = -1.35153822785657;
   fWeightMatrix0to1[18][8] = -3.08082832064269;
   fWeightMatrix0to1[19][8] = -0.92643218221083;
   fWeightMatrix0to1[20][8] = -0.714212304506813;
   fWeightMatrix0to1[21][8] = 0.616168064388479;
   fWeightMatrix0to1[22][8] = 2.32761691456877;
   fWeightMatrix0to1[23][8] = 0.00352822740012307;
   fWeightMatrix0to1[24][8] = -0.113087562289089;
   fWeightMatrix0to1[25][8] = -0.0969163551170433;
   fWeightMatrix0to1[26][8] = -1.94019894420584;
   fWeightMatrix0to1[27][8] = 1.09190518402229;
   fWeightMatrix0to1[28][8] = 0.599718452130388;
   fWeightMatrix0to1[29][8] = -0.83481004794639;
   fWeightMatrix0to1[0][9] = -0.791952831399665;
   fWeightMatrix0to1[1][9] = -0.0107180014801381;
   fWeightMatrix0to1[2][9] = 0.341251042076451;
   fWeightMatrix0to1[3][9] = 0.767539268459966;
   fWeightMatrix0to1[4][9] = -0.255865100634429;
   fWeightMatrix0to1[5][9] = -0.307293660533429;
   fWeightMatrix0to1[6][9] = 1.27932960628147;
   fWeightMatrix0to1[7][9] = 1.14470678934457;
   fWeightMatrix0to1[8][9] = 1.04379696455338;
   fWeightMatrix0to1[9][9] = -0.292768628722624;
   fWeightMatrix0to1[10][9] = 0.154436313106642;
   fWeightMatrix0to1[11][9] = -0.482411182827706;
   fWeightMatrix0to1[12][9] = -1.32865605359545;
   fWeightMatrix0to1[13][9] = 0.78714035687259;
   fWeightMatrix0to1[14][9] = -1.77216257434094;
   fWeightMatrix0to1[15][9] = -1.25099808267486;
   fWeightMatrix0to1[16][9] = -1.64314897049586;
   fWeightMatrix0to1[17][9] = 1.32495937296281;
   fWeightMatrix0to1[18][9] = -1.54141878520856;
   fWeightMatrix0to1[19][9] = 1.21679781813097;
   fWeightMatrix0to1[20][9] = -0.275590626803673;
   fWeightMatrix0to1[21][9] = 1.23552815817037;
   fWeightMatrix0to1[22][9] = -0.726224292034107;
   fWeightMatrix0to1[23][9] = 1.26877602610007;
   fWeightMatrix0to1[24][9] = 0.150274486503755;
   fWeightMatrix0to1[25][9] = -1.00533642087236;
   fWeightMatrix0to1[26][9] = 0.314989279822524;
   fWeightMatrix0to1[27][9] = 0.110129884606456;
   fWeightMatrix0to1[28][9] = -1.60514677767449;
   fWeightMatrix0to1[29][9] = -1.47290652050339;
   fWeightMatrix0to1[0][10] = -1.10634075769021;
   fWeightMatrix0to1[1][10] = -0.696537379853307;
   fWeightMatrix0to1[2][10] = 1.14445920731703;
   fWeightMatrix0to1[3][10] = -0.809476623969778;
   fWeightMatrix0to1[4][10] = 0.292852930172245;
   fWeightMatrix0to1[5][10] = -0.00583338871304164;
   fWeightMatrix0to1[6][10] = -0.583687211427428;
   fWeightMatrix0to1[7][10] = -1.78685218339152;
   fWeightMatrix0to1[8][10] = -0.878279695455286;
   fWeightMatrix0to1[9][10] = -1.28628418103508;
   fWeightMatrix0to1[10][10] = -0.185229389711406;
   fWeightMatrix0to1[11][10] = -1.44577360562655;
   fWeightMatrix0to1[12][10] = -1.20878187443493;
   fWeightMatrix0to1[13][10] = -0.107318899044594;
   fWeightMatrix0to1[14][10] = 0.293136767558717;
   fWeightMatrix0to1[15][10] = -0.483664449675203;
   fWeightMatrix0to1[16][10] = 1.54535899562721;
   fWeightMatrix0to1[17][10] = -1.65544153791889;
   fWeightMatrix0to1[18][10] = 0.307774991815453;
   fWeightMatrix0to1[19][10] = 0.0682433215622242;
   fWeightMatrix0to1[20][10] = -0.933530043008031;
   fWeightMatrix0to1[21][10] = -0.795094412682411;
   fWeightMatrix0to1[22][10] = 0.0299146549909256;
   fWeightMatrix0to1[23][10] = -0.262204653372705;
   fWeightMatrix0to1[24][10] = 0.493653310099065;
   fWeightMatrix0to1[25][10] = 1.66762518257634;
   fWeightMatrix0to1[26][10] = 1.32474630289658;
   fWeightMatrix0to1[27][10] = 1.36160481393461;
   fWeightMatrix0to1[28][10] = -1.02797415138905;
   fWeightMatrix0to1[29][10] = 1.0477264659028;
   fWeightMatrix0to1[0][11] = -0.237964214677094;
   fWeightMatrix0to1[1][11] = -0.68607070112399;
   fWeightMatrix0to1[2][11] = -0.369555222620636;
   fWeightMatrix0to1[3][11] = -1.8808386807459;
   fWeightMatrix0to1[4][11] = 0.178954971479498;
   fWeightMatrix0to1[5][11] = 0.784200638323896;
   fWeightMatrix0to1[6][11] = 0.602383433031674;
   fWeightMatrix0to1[7][11] = 0.465836988915844;
   fWeightMatrix0to1[8][11] = 0.484626494275701;
   fWeightMatrix0to1[9][11] = -0.0787980560345532;
   fWeightMatrix0to1[10][11] = -0.322375424406736;
   fWeightMatrix0to1[11][11] = 0.367883808472384;
   fWeightMatrix0to1[12][11] = 1.46243592724716;
   fWeightMatrix0to1[13][11] = -1.06649672922021;
   fWeightMatrix0to1[14][11] = 0.365792803114166;
   fWeightMatrix0to1[15][11] = -1.44363888517679;
   fWeightMatrix0to1[16][11] = -0.942314760656001;
   fWeightMatrix0to1[17][11] = 0.350193820884603;
   fWeightMatrix0to1[18][11] = -0.0400135481840676;
   fWeightMatrix0to1[19][11] = -1.04370698157287;
   fWeightMatrix0to1[20][11] = 1.39885626306639;
   fWeightMatrix0to1[21][11] = 1.6347373353117;
   fWeightMatrix0to1[22][11] = 0.346270131494453;
   fWeightMatrix0to1[23][11] = 0.202667479781443;
   fWeightMatrix0to1[24][11] = -0.428875283592821;
   fWeightMatrix0to1[25][11] = -0.953729032536929;
   fWeightMatrix0to1[26][11] = -1.85122642762594;
   fWeightMatrix0to1[27][11] = 0.959606770194901;
   fWeightMatrix0to1[28][11] = -0.121991177017861;
   fWeightMatrix0to1[29][11] = -1.13743405543449;
   fWeightMatrix0to1[0][12] = 0.875250599700601;
   fWeightMatrix0to1[1][12] = 0.141499404121864;
   fWeightMatrix0to1[2][12] = 0.757156291552541;
   fWeightMatrix0to1[3][12] = -0.935798303229023;
   fWeightMatrix0to1[4][12] = 1.34236870923636;
   fWeightMatrix0to1[5][12] = -1.46541693196724;
   fWeightMatrix0to1[6][12] = -1.1380861186091;
   fWeightMatrix0to1[7][12] = 0.263953073489448;
   fWeightMatrix0to1[8][12] = -0.998112399365916;
   fWeightMatrix0to1[9][12] = -1.72163827980713;
   fWeightMatrix0to1[10][12] = 0.753120971036296;
   fWeightMatrix0to1[11][12] = -1.57415348631275;
   fWeightMatrix0to1[12][12] = -1.14057350048803;
   fWeightMatrix0to1[13][12] = 0.831956883248363;
   fWeightMatrix0to1[14][12] = 0.486122128228537;
   fWeightMatrix0to1[15][12] = 0.34865272971331;
   fWeightMatrix0to1[16][12] = 0.153289055484203;
   fWeightMatrix0to1[17][12] = 0.691495658210493;
   fWeightMatrix0to1[18][12] = 0.964229823473399;
   fWeightMatrix0to1[19][12] = 0.281472925842777;
   fWeightMatrix0to1[20][12] = -0.570585998112852;
   fWeightMatrix0to1[21][12] = -0.252568196977325;
   fWeightMatrix0to1[22][12] = -0.943776119654911;
   fWeightMatrix0to1[23][12] = 0.247471582806814;
   fWeightMatrix0to1[24][12] = 0.0396579631184973;
   fWeightMatrix0to1[25][12] = -0.301464448722032;
   fWeightMatrix0to1[26][12] = 1.42124412045514;
   fWeightMatrix0to1[27][12] = 0.83046549060033;
   fWeightMatrix0to1[28][12] = 0.796229163149796;
   fWeightMatrix0to1[29][12] = -1.34335223994568;
   fWeightMatrix0to1[0][13] = 1.53321350543749;
   fWeightMatrix0to1[1][13] = 0.145269863541071;
   fWeightMatrix0to1[2][13] = -1.64181160932515;
   fWeightMatrix0to1[3][13] = 0.133623208007348;
   fWeightMatrix0to1[4][13] = -0.693895283708644;
   fWeightMatrix0to1[5][13] = 0.679178411992833;
   fWeightMatrix0to1[6][13] = 0.308102400906891;
   fWeightMatrix0to1[7][13] = 0.942388053794314;
   fWeightMatrix0to1[8][13] = 1.85191277219892;
   fWeightMatrix0to1[9][13] = -0.487263350203476;
   fWeightMatrix0to1[10][13] = 0.805039108153033;
   fWeightMatrix0to1[11][13] = 1.60259820646537;
   fWeightMatrix0to1[12][13] = 0.495453362776346;
   fWeightMatrix0to1[13][13] = -0.0226711446802424;
   fWeightMatrix0to1[14][13] = 1.61517087850989;
   fWeightMatrix0to1[15][13] = -1.93539324717203;
   fWeightMatrix0to1[16][13] = 0.50855063046977;
   fWeightMatrix0to1[17][13] = 0.777038145903346;
   fWeightMatrix0to1[18][13] = 0.67634846205395;
   fWeightMatrix0to1[19][13] = -1.01846727374723;
   fWeightMatrix0to1[20][13] = 0.298199851504466;
   fWeightMatrix0to1[21][13] = -1.13649127020668;
   fWeightMatrix0to1[22][13] = 0.661868696664753;
   fWeightMatrix0to1[23][13] = -0.940521923246047;
   fWeightMatrix0to1[24][13] = -0.0629636565840201;
   fWeightMatrix0to1[25][13] = 0.123060283808962;
   fWeightMatrix0to1[26][13] = 1.84366125003571;
   fWeightMatrix0to1[27][13] = 1.36599372731597;
   fWeightMatrix0to1[28][13] = 1.16325065145889;
   fWeightMatrix0to1[29][13] = -0.519889902459497;
   fWeightMatrix0to1[0][14] = 0.248472537287109;
   fWeightMatrix0to1[1][14] = -0.163179293042427;
   fWeightMatrix0to1[2][14] = 0.137507263300673;
   fWeightMatrix0to1[3][14] = -0.806436392017157;
   fWeightMatrix0to1[4][14] = -1.07718007496616;
   fWeightMatrix0to1[5][14] = -0.0259362413489318;
   fWeightMatrix0to1[6][14] = -0.276069835379189;
   fWeightMatrix0to1[7][14] = -0.402063178799205;
   fWeightMatrix0to1[8][14] = -1.28731393541849;
   fWeightMatrix0to1[9][14] = 0.449777223117116;
   fWeightMatrix0to1[10][14] = -0.204917243970192;
   fWeightMatrix0to1[11][14] = -1.8754851905441;
   fWeightMatrix0to1[12][14] = -0.622129302884164;
   fWeightMatrix0to1[13][14] = -0.0836950209160954;
   fWeightMatrix0to1[14][14] = 1.33370102079619;
   fWeightMatrix0to1[15][14] = 1.74363594644548;
   fWeightMatrix0to1[16][14] = 0.850014630036642;
   fWeightMatrix0to1[17][14] = -0.291562604778084;
   fWeightMatrix0to1[18][14] = -1.0102092867383;
   fWeightMatrix0to1[19][14] = -0.204824403309091;
   fWeightMatrix0to1[20][14] = -0.24735130387362;
   fWeightMatrix0to1[21][14] = -1.2998547385958;
   fWeightMatrix0to1[22][14] = 0.0641835247342658;
   fWeightMatrix0to1[23][14] = -0.193792844705406;
   fWeightMatrix0to1[24][14] = -0.400734846360895;
   fWeightMatrix0to1[25][14] = 0.142595386467603;
   fWeightMatrix0to1[26][14] = 0.95142148151201;
   fWeightMatrix0to1[27][14] = 0.642433086120773;
   fWeightMatrix0to1[28][14] = -0.456891908591285;
   fWeightMatrix0to1[29][14] = -0.883634558122734;
   fWeightMatrix0to1[0][15] = 0.184164922795491;
   fWeightMatrix0to1[1][15] = -2.08462575769967;
   fWeightMatrix0to1[2][15] = -0.242811195860342;
   fWeightMatrix0to1[3][15] = 1.3737074386811;
   fWeightMatrix0to1[4][15] = 1.24473231695;
   fWeightMatrix0to1[5][15] = -2.38498079244264;
   fWeightMatrix0to1[6][15] = 0.437561205709603;
   fWeightMatrix0to1[7][15] = -0.984499398932908;
   fWeightMatrix0to1[8][15] = 1.40210767011791;
   fWeightMatrix0to1[9][15] = 1.7054369134655;
   fWeightMatrix0to1[10][15] = -0.431075516351116;
   fWeightMatrix0to1[11][15] = -0.751467382742853;
   fWeightMatrix0to1[12][15] = 0.891805431790391;
   fWeightMatrix0to1[13][15] = 0.194127487305509;
   fWeightMatrix0to1[14][15] = 1.13307838132314;
   fWeightMatrix0to1[15][15] = 0.318465954478661;
   fWeightMatrix0to1[16][15] = -0.612612962464789;
   fWeightMatrix0to1[17][15] = -1.09100386842229;
   fWeightMatrix0to1[18][15] = -0.818070168172462;
   fWeightMatrix0to1[19][15] = -0.113857770135492;
   fWeightMatrix0to1[20][15] = 1.08497349210896;
   fWeightMatrix0to1[21][15] = -0.766692476274859;
   fWeightMatrix0to1[22][15] = -1.45279313646757;
   fWeightMatrix0to1[23][15] = 2.59825131236399;
   fWeightMatrix0to1[24][15] = -0.175897569040862;
   fWeightMatrix0to1[25][15] = -0.0935577441365025;
   fWeightMatrix0to1[26][15] = -0.245961107823855;
   fWeightMatrix0to1[27][15] = -1.01514254460273;
   fWeightMatrix0to1[28][15] = 0.310031014066048;
   fWeightMatrix0to1[29][15] = 1.44847945703588;
   fWeightMatrix0to1[0][16] = -1.06129078900339;
   fWeightMatrix0to1[1][16] = -0.715030319602535;
   fWeightMatrix0to1[2][16] = 1.45155364032768;
   fWeightMatrix0to1[3][16] = 1.90631520607568;
   fWeightMatrix0to1[4][16] = 0.626169108759422;
   fWeightMatrix0to1[5][16] = 0.40453412110392;
   fWeightMatrix0to1[6][16] = -0.848503452922145;
   fWeightMatrix0to1[7][16] = -1.2301576493067;
   fWeightMatrix0to1[8][16] = 1.2946762109501;
   fWeightMatrix0to1[9][16] = -0.32122901978666;
   fWeightMatrix0to1[10][16] = 0.952627772413919;
   fWeightMatrix0to1[11][16] = -1.64362292832913;
   fWeightMatrix0to1[12][16] = -2.07314151773767;
   fWeightMatrix0to1[13][16] = -3.42104145498917;
   fWeightMatrix0to1[14][16] = -0.202151845357261;
   fWeightMatrix0to1[15][16] = -1.87007314956776;
   fWeightMatrix0to1[16][16] = 0.437279199982321;
   fWeightMatrix0to1[17][16] = -0.40521849849473;
   fWeightMatrix0to1[18][16] = 0.655472953690165;
   fWeightMatrix0to1[19][16] = 0.312349707863684;
   fWeightMatrix0to1[20][16] = -1.28506098735496;
   fWeightMatrix0to1[21][16] = 1.53973045453846;
   fWeightMatrix0to1[22][16] = 2.2719842203396;
   fWeightMatrix0to1[23][16] = 1.47403341924689;
   fWeightMatrix0to1[24][16] = -0.267232474754163;
   fWeightMatrix0to1[25][16] = -0.767670093882001;
   fWeightMatrix0to1[26][16] = 1.5806749878397;
   fWeightMatrix0to1[27][16] = -1.96378443835603;
   fWeightMatrix0to1[28][16] = 0.2675092775526;
   fWeightMatrix0to1[29][16] = -1.38532589595313;
   fWeightMatrix0to1[0][17] = 2.29377906367557;
   fWeightMatrix0to1[1][17] = -0.937267881145493;
   fWeightMatrix0to1[2][17] = 0.912130353004818;
   fWeightMatrix0to1[3][17] = 0.492232655519267;
   fWeightMatrix0to1[4][17] = 1.20015331760689;
   fWeightMatrix0to1[5][17] = 0.155390164575549;
   fWeightMatrix0to1[6][17] = -0.65074854610886;
   fWeightMatrix0to1[7][17] = 0.826546513592603;
   fWeightMatrix0to1[8][17] = 0.585499772970427;
   fWeightMatrix0to1[9][17] = 0.477349446510435;
   fWeightMatrix0to1[10][17] = 0.216777612886108;
   fWeightMatrix0to1[11][17] = -1.63104429750361;
   fWeightMatrix0to1[12][17] = 1.04826172791409;
   fWeightMatrix0to1[13][17] = -1.94487979537898;
   fWeightMatrix0to1[14][17] = 1.29643271786446;
   fWeightMatrix0to1[15][17] = 1.09536146700205;
   fWeightMatrix0to1[16][17] = 0.212393677447409;
   fWeightMatrix0to1[17][17] = 2.0125207813783;
   fWeightMatrix0to1[18][17] = 1.09064312736526;
   fWeightMatrix0to1[19][17] = -1.51064897159847;
   fWeightMatrix0to1[20][17] = -1.12607520375362;
   fWeightMatrix0to1[21][17] = -0.610066861438495;
   fWeightMatrix0to1[22][17] = 1.24202311540789;
   fWeightMatrix0to1[23][17] = 0.658333972943035;
   fWeightMatrix0to1[24][17] = -0.196060438994514;
   fWeightMatrix0to1[25][17] = -0.421994284787316;
   fWeightMatrix0to1[26][17] = -0.406228116510954;
   fWeightMatrix0to1[27][17] = -1.27776526004877;
   fWeightMatrix0to1[28][17] = 0.00252653236235228;
   fWeightMatrix0to1[29][17] = -1.8962333496829;
   fWeightMatrix0to1[0][18] = 0.188409690958324;
   fWeightMatrix0to1[1][18] = 0.0353555447407586;
   fWeightMatrix0to1[2][18] = -1.11082764958635;
   fWeightMatrix0to1[3][18] = -0.638234932978643;
   fWeightMatrix0to1[4][18] = 1.05623472813549;
   fWeightMatrix0to1[5][18] = -0.518469867944104;
   fWeightMatrix0to1[6][18] = 0.151562931071694;
   fWeightMatrix0to1[7][18] = -1.08186428246382;
   fWeightMatrix0to1[8][18] = 2.01982801727061;
   fWeightMatrix0to1[9][18] = -0.629970839491735;
   fWeightMatrix0to1[10][18] = 0.29381359347199;
   fWeightMatrix0to1[11][18] = 0.701945681425364;
   fWeightMatrix0to1[12][18] = -1.05248342971885;
   fWeightMatrix0to1[13][18] = 0.411646246562676;
   fWeightMatrix0to1[14][18] = -0.0748209235505654;
   fWeightMatrix0to1[15][18] = -2.05527095729241;
   fWeightMatrix0to1[16][18] = -1.20476335594056;
   fWeightMatrix0to1[17][18] = -0.988435614182457;
   fWeightMatrix0to1[18][18] = 0.849099398652851;
   fWeightMatrix0to1[19][18] = -2.18460349228471;
   fWeightMatrix0to1[20][18] = 1.02316083779955;
   fWeightMatrix0to1[21][18] = 1.97264722537391;
   fWeightMatrix0to1[22][18] = 1.82072415041943;
   fWeightMatrix0to1[23][18] = 1.3460890966021;
   fWeightMatrix0to1[24][18] = 0.667273234198669;
   fWeightMatrix0to1[25][18] = -0.172911263771759;
   fWeightMatrix0to1[26][18] = -1.13263363056184;
   fWeightMatrix0to1[27][18] = -2.02846618438473;
   fWeightMatrix0to1[28][18] = -0.580511134228225;
   fWeightMatrix0to1[29][18] = -0.796997071075706;
   fWeightMatrix0to1[0][19] = 1.45594035967345;
   fWeightMatrix0to1[1][19] = -0.323711970708841;
   fWeightMatrix0to1[2][19] = 0.265996691705003;
   fWeightMatrix0to1[3][19] = 2.02962872608168;
   fWeightMatrix0to1[4][19] = 1.6639870710445;
   fWeightMatrix0to1[5][19] = -0.599036792929485;
   fWeightMatrix0to1[6][19] = 0.506546874285477;
   fWeightMatrix0to1[7][19] = -1.56308397258807;
   fWeightMatrix0to1[8][19] = 1.00391394175393;
   fWeightMatrix0to1[9][19] = -2.16616141013489;
   fWeightMatrix0to1[10][19] = 0.845012002296076;
   fWeightMatrix0to1[11][19] = -0.243029208662143;
   fWeightMatrix0to1[12][19] = 0.615292965004861;
   fWeightMatrix0to1[13][19] = 0.539864290942803;
   fWeightMatrix0to1[14][19] = 0.514548177457317;
   fWeightMatrix0to1[15][19] = -1.66370857829742;
   fWeightMatrix0to1[16][19] = -0.337305975855156;
   fWeightMatrix0to1[17][19] = 1.56349174279037;
   fWeightMatrix0to1[18][19] = 0.150269988572974;
   fWeightMatrix0to1[19][19] = 0.926923585202599;
   fWeightMatrix0to1[20][19] = -1.58680344093002;
   fWeightMatrix0to1[21][19] = 1.3399354601349;
   fWeightMatrix0to1[22][19] = 0.0238691154029011;
   fWeightMatrix0to1[23][19] = 1.20489174353032;
   fWeightMatrix0to1[24][19] = -1.51414674642838;
   fWeightMatrix0to1[25][19] = -0.898707962962885;
   fWeightMatrix0to1[26][19] = 1.86383262343968;
   fWeightMatrix0to1[27][19] = -1.98424119876865;
   fWeightMatrix0to1[28][19] = -1.65607754157421;
   fWeightMatrix0to1[29][19] = -0.869334154022621;
   fWeightMatrix0to1[0][20] = 0.159727757972715;
   fWeightMatrix0to1[1][20] = 0.952731272759678;
   fWeightMatrix0to1[2][20] = 0.778280580913838;
   fWeightMatrix0to1[3][20] = -2.66765400699757;
   fWeightMatrix0to1[4][20] = 0.0264486516802206;
   fWeightMatrix0to1[5][20] = -0.0202214926322463;
   fWeightMatrix0to1[6][20] = 0.191392656651079;
   fWeightMatrix0to1[7][20] = -1.27364021601946;
   fWeightMatrix0to1[8][20] = -1.6464565068248;
   fWeightMatrix0to1[9][20] = 0.441397670513784;
   fWeightMatrix0to1[10][20] = 0.294117606311039;
   fWeightMatrix0to1[11][20] = 1.50583073520158;
   fWeightMatrix0to1[12][20] = -0.108503842980916;
   fWeightMatrix0to1[13][20] = -0.0259935899741631;
   fWeightMatrix0to1[14][20] = -1.34680536589533;
   fWeightMatrix0to1[15][20] = 1.4837734584092;
   fWeightMatrix0to1[16][20] = 0.953557258529328;
   fWeightMatrix0to1[17][20] = 0.939335125688503;
   fWeightMatrix0to1[18][20] = -0.79197960507265;
   fWeightMatrix0to1[19][20] = -1.99310661140974;
   fWeightMatrix0to1[20][20] = 2.03906259598846;
   fWeightMatrix0to1[21][20] = -0.285045352474607;
   fWeightMatrix0to1[22][20] = 0.848652819651489;
   fWeightMatrix0to1[23][20] = -0.628722270220387;
   fWeightMatrix0to1[24][20] = -0.98895060342395;
   fWeightMatrix0to1[25][20] = -1.20151934882623;
   fWeightMatrix0to1[26][20] = -1.62801840724483;
   fWeightMatrix0to1[27][20] = -0.112475897590811;
   fWeightMatrix0to1[28][20] = -1.47981866003902;
   fWeightMatrix0to1[29][20] = -0.0898419978424164;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.254011245046181;
   fWeightMatrix1to2[0][1] = -0.189577701756016;
   fWeightMatrix1to2[0][2] = 0.120886315074596;
   fWeightMatrix1to2[0][3] = -0.286258106546989;
   fWeightMatrix1to2[0][4] = -0.234193980640671;
   fWeightMatrix1to2[0][5] = 0.240911875239361;
   fWeightMatrix1to2[0][6] = -0.131989031541401;
   fWeightMatrix1to2[0][7] = 0.0487420508781549;
   fWeightMatrix1to2[0][8] = -0.229266199282834;
   fWeightMatrix1to2[0][9] = -0.746407721949685;
   fWeightMatrix1to2[0][10] = 0.308479678491546;
   fWeightMatrix1to2[0][11] = -0.811781695550735;
   fWeightMatrix1to2[0][12] = -0.0665497236972472;
   fWeightMatrix1to2[0][13] = -0.201063760812864;
   fWeightMatrix1to2[0][14] = -1.10807653600628;
   fWeightMatrix1to2[0][15] = -0.263019249189693;
   fWeightMatrix1to2[0][16] = -0.265275052443316;
   fWeightMatrix1to2[0][17] = -0.0850186598528573;
   fWeightMatrix1to2[0][18] = 0.200039609710527;
   fWeightMatrix1to2[0][19] = 0.164855261341211;
   fWeightMatrix1to2[0][20] = 0.188638390294849;
   fWeightMatrix1to2[0][21] = -0.973234908033954;
   fWeightMatrix1to2[0][22] = -0.889222728354994;
   fWeightMatrix1to2[0][23] = -0.278772564737385;
   fWeightMatrix1to2[0][24] = 0.0119671856945947;
   fWeightMatrix1to2[0][25] = -0.00991194620333197;
   fWeightMatrix1to2[0][26] = 0.0644085679263433;
   fWeightMatrix1to2[0][27] = -0.497420635854106;
   fWeightMatrix1to2[0][28] = -0.103216832463699;
   fWeightMatrix1to2[0][29] = 0.36242614490119;
   fWeightMatrix1to2[0][30] = -1.122921383065;
}

inline double ReadMLPTuned::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPTuned::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPTuned::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPTuned::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPTuned::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 10;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 10;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 10;
   fMin_1[0][1] = 2;
   fMax_1[0][1] = 5;
   fMin_1[1][1] = 2;
   fMax_1[1][1] = 5;
   fMin_1[2][1] = 2;
   fMax_1[2][1] = 5;
   fMin_1[0][2] = 20.5274581909;
   fMax_1[0][2] = 779.356506348;
   fMin_1[1][2] = 20.345867157;
   fMax_1[1][2] = 989.239624023;
   fMin_1[2][2] = 20.345867157;
   fMax_1[2][2] = 989.239624023;
   fMin_1[0][3] = 20.0002479553;
   fMax_1[0][3] = 557.967102051;
   fMin_1[1][3] = 20.0051765442;
   fMax_1[1][3] = 699.98260498;
   fMin_1[2][3] = 20.0002479553;
   fMax_1[2][3] = 699.98260498;
   fMin_1[0][4] = 30.8286094666;
   fMax_1[0][4] = 904.02545166;
   fMin_1[1][4] = 31.4223308563;
   fMax_1[1][4] = 686.358764648;
   fMin_1[2][4] = 30.8286094666;
   fMax_1[2][4] = 904.02545166;
   fMin_1[0][5] = 30.0086250305;
   fMax_1[0][5] = 280.001068115;
   fMin_1[1][5] = 30.0258865356;
   fMax_1[1][5] = 239.681365967;
   fMin_1[2][5] = 30.0086250305;
   fMax_1[2][5] = 280.001068115;
   fMin_1[0][6] = 20.0059547424;
   fMax_1[0][6] = 438.634124756;
   fMin_1[1][6] = 20.0040016174;
   fMax_1[1][6] = 480.95715332;
   fMin_1[2][6] = 20.0040016174;
   fMax_1[2][6] = 480.95715332;
   fMin_1[0][7] = 20.0082492828;
   fMax_1[0][7] = 660.794494629;
   fMin_1[1][7] = 20.003408432;
   fMax_1[1][7] = 625.883056641;
   fMin_1[2][7] = 20.003408432;
   fMax_1[2][7] = 660.794494629;
   fMin_1[0][8] = 0.267349809408;
   fMax_1[0][8] = 5.96390295029;
   fMin_1[1][8] = 0.32699367404;
   fMax_1[1][8] = 4.57333946228;
   fMin_1[2][8] = 0.267349809408;
   fMax_1[2][8] = 5.96390295029;
   fMin_1[0][9] = 0.411826014519;
   fMax_1[0][9] = 6.17678260803;
   fMin_1[1][9] = 0.517152249813;
   fMax_1[1][9] = 5.48278474808;
   fMin_1[2][9] = 0.411826014519;
   fMax_1[2][9] = 6.17678260803;
   fMin_1[0][10] = 0.548147320747;
   fMax_1[0][10] = 5.12846136093;
   fMin_1[1][10] = 0.514531254768;
   fMax_1[1][10] = 5.3588013649;
   fMin_1[2][10] = 0.514531254768;
   fMax_1[2][10] = 5.3588013649;
   fMin_1[0][11] = 0.345456838608;
   fMax_1[0][11] = 4.68913269043;
   fMin_1[1][11] = 0.331118583679;
   fMax_1[1][11] = 4.59567117691;
   fMin_1[2][11] = 0.331118583679;
   fMax_1[2][11] = 4.68913269043;
   fMin_1[0][12] = 0.389083296061;
   fMax_1[0][12] = 3.09887003899;
   fMin_1[1][12] = 0.383479446173;
   fMax_1[1][12] = 3.09936523438;
   fMin_1[2][12] = 0.383479446173;
   fMax_1[2][12] = 3.09936523438;
   fMin_1[0][13] = 0.0128494994715;
   fMax_1[0][13] = 6.85796403885;
   fMin_1[1][13] = 0.0341882109642;
   fMax_1[1][13] = 7.59379291534;
   fMin_1[2][13] = 0.0128494994715;
   fMax_1[2][13] = 7.59379291534;
   fMin_1[0][14] = 0.00020170211792;
   fMax_1[0][14] = 6.22917413712;
   fMin_1[1][14] = 9.36985015869e-05;
   fMax_1[1][14] = 6.23410224915;
   fMin_1[2][14] = 9.36985015869e-05;
   fMax_1[2][14] = 6.23410224915;
   fMin_1[0][15] = 60.0008811951;
   fMax_1[0][15] = 159.889877319;
   fMin_1[1][15] = 60.0244789124;
   fMax_1[1][15] = 159.999816895;
   fMin_1[2][15] = 60.0008811951;
   fMax_1[2][15] = 159.999816895;
   fMin_1[0][16] = 35.0392456055;
   fMax_1[0][16] = 3031.91503906;
   fMin_1[1][16] = 40.3004264832;
   fMax_1[1][16] = 3519.41210938;
   fMin_1[2][16] = 35.0392456055;
   fMax_1[2][16] = 3519.41210938;
   fMin_1[0][17] = 87.2848510742;
   fMax_1[0][17] = 1635.71276855;
   fMin_1[1][17] = 89.7603530884;
   fMax_1[1][17] = 4438.00146484;
   fMin_1[2][17] = 87.2848510742;
   fMax_1[2][17] = 4438.00146484;
   fMin_1[0][18] = 0.0075534847565;
   fMax_1[0][18] = 460.327148438;
   fMin_1[1][18] = 0.00475058425218;
   fMax_1[1][18] = 535.521972656;
   fMin_1[2][18] = 0.00475058425218;
   fMax_1[2][18] = 535.521972656;
   fMin_1[0][19] = 0.0112428609282;
   fMax_1[0][19] = 1282.00231934;
   fMin_1[1][19] = 0.000171629610122;
   fMax_1[1][19] = 1580.10388184;
   fMin_1[2][19] = 0.000171629610122;
   fMax_1[2][19] = 1580.10388184;
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 20;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesGet.push_back( 14);
   indicesGet.push_back( 15);
   indicesGet.push_back( 16);
   indicesGet.push_back( 17);
   indicesGet.push_back( 18);
   indicesGet.push_back( 19);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);
   indicesPut.push_back( 14);
   indicesPut.push_back( 15);
   indicesPut.push_back( 16);
   indicesPut.push_back( 17);
   indicesPut.push_back( 18);
   indicesPut.push_back( 19);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<20;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
