// Class: ReadMLPTunedSigmoid
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPTunedSigmoid
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : ineuteli
Date           : Sun Nov 29 23:37:34 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.11.2.el6.x86_64 #1 SMP Wed Mar 26 09:39:43 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/ineuteli/phase2/CMSSW_5_3_24/src/Delphes/plots
Training events: 20732
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
NCycles: "500" [Number of training cycles]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 23
Njets20                       Njets20                       Njets20                       Njets20                                                         'F'    [4,14]
Nbjets30                      Nbjets30                      Nbjets30                      Nbjets30                                                        'F'    [2,6]
jet1Pt                        jet1Pt                        jet1Pt                        jet1Pt                                                          'F'    [20.3211650848,1187.93493652]
jet2Pt                        jet2Pt                        jet2Pt                        jet2Pt                                                          'F'    [20.0031757355,699.98260498]
bjet1Pt                       bjet1Pt                       bjet1Pt                       bjet1Pt                                                         'F'    [31.4223308563,904.02545166]
bjet2Pt                       bjet2Pt                       bjet2Pt                       bjet2Pt                                                         'F'    [30.001663208,298.117797852]
leptonPt                      leptonPt                      leptonPt                      leptonPt                                                        'F'    [20.0059547424,480.95715332]
MET                           MET                           MET                           MET                                                             'F'    [20.003408432,625.883056641]
DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                                                      'F'    [0.267349809408,5.02747869492]
DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                                                      'F'    [0.410064458847,6.81951332092]
DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                                                      'F'    [0.548147320747,5.80796384811]
DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                                                      'F'    [0.331118583679,4.68913269043]
DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                                                      'F'    [0.382231384516,3.09979128838]
DeltaR_jj                     DeltaR_jj                     DeltaR_jj                     DeltaR_jj                                                       'F'    [0.304761111736,5.83795309067]
DeltaR_jjl                    DeltaR_jjl                    DeltaR_jjl                    DeltaR_jjl                                                      'F'    [0.0245936494321,7.59379291534]
DeltaR_jjb                    DeltaR_jjb                    DeltaR_jjb                    DeltaR_jjb                                                      'F'    [0.0183821171522,7.17004442215]
DeltaPhi_lMET                 DeltaPhi_lMET                 DeltaPhi_lMET                 DeltaPhi_lMET                                                   'F'    [9.36985015869e-05,6.25128030777]
M_bb_closest                  M_bb_closest                  M_bb_closest                  M_bb_closest                                                    'F'    [60.0013084412,159.999816895]
M_jjlnu                       M_jjlnu                       M_jjlnu                       M_jjlnu                                                         'F'    [104.987121582,4475.03857422]
M_jjb                         M_jjb                         M_jjb                         M_jjb                                                           'F'    [42.1632194519,3519.41210938]
M_blnu                        M_blnu                        M_blnu                        M_blnu                                                          'F'    [86.4190216064,4438.00146484]
MT_lnu                        MT_lnu                        MT_lnu                        MT_lnu                                                          'F'    [0.00475058425218,535.521972656]
MT_jjlnu                      MT_jjlnu                      MT_jjlnu                      MT_jjlnu                                                        'F'    [0.00143084453885,1580.10388184]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPTunedSigmoid : public IClassifierReader {

 public:

   // constructor
   ReadMLPTunedSigmoid( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPTunedSigmoid" ),
        fNvars( 23 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Njets20", "Nbjets30", "jet1Pt", "jet2Pt", "bjet1Pt", "bjet2Pt", "leptonPt", "MET", "DeltaR_j1l", "DeltaR_j2l", "DeltaR_b1l", "DeltaR_b2l", "DeltaR_bb1", "DeltaR_jj", "DeltaR_jjl", "DeltaR_jjb", "DeltaPhi_lMET", "M_bb_closest", "M_jjlnu", "M_jjb", "M_blnu", "MT_lnu", "MT_jjlnu" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 0.99999988079071;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 0.99999988079071;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 0.99999988079071;
      fVmin[16] = -1;
      fVmax[16] = 0.99999988079071;
      fVmin[17] = -1;
      fVmax[17] = 1;
      fVmin[18] = -1;
      fVmax[18] = 1;
      fVmin[19] = -1;
      fVmax[19] = 1;
      fVmin[20] = -1;
      fVmax[20] = 1;
      fVmin[21] = -1;
      fVmax[21] = 1;
      fVmin[22] = -1;
      fVmax[22] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPTunedSigmoid() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][23];
   double fMax_1[3][23];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[23];
   double fVmax[23];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[23];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[29][24];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][29];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPTunedSigmoid::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 24; fWeights[0] = new double[24]; 
   fLayerSize[1] = 29; fWeights[1] = new double[29]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.134866755067018;
   fWeightMatrix0to1[1][0] = 1.77594078282424;
   fWeightMatrix0to1[2][0] = 1.18288384469062;
   fWeightMatrix0to1[3][0] = 1.03544316066824;
   fWeightMatrix0to1[4][0] = -0.302233892214068;
   fWeightMatrix0to1[5][0] = -0.872973771590258;
   fWeightMatrix0to1[6][0] = -0.0794788026678076;
   fWeightMatrix0to1[7][0] = 1.98825790121374;
   fWeightMatrix0to1[8][0] = -1.00371541348964;
   fWeightMatrix0to1[9][0] = -0.557549812582832;
   fWeightMatrix0to1[10][0] = -1.11750549542255;
   fWeightMatrix0to1[11][0] = -0.700862546909995;
   fWeightMatrix0to1[12][0] = -0.468093298531456;
   fWeightMatrix0to1[13][0] = -0.138272704306168;
   fWeightMatrix0to1[14][0] = -0.402516267486955;
   fWeightMatrix0to1[15][0] = 0.425324918972947;
   fWeightMatrix0to1[16][0] = -0.10858705855788;
   fWeightMatrix0to1[17][0] = 1.62139468465865;
   fWeightMatrix0to1[18][0] = 0.519888973291405;
   fWeightMatrix0to1[19][0] = 0.357711152413376;
   fWeightMatrix0to1[20][0] = 0.385385116039952;
   fWeightMatrix0to1[21][0] = -0.571257824158504;
   fWeightMatrix0to1[22][0] = 1.02491847449738;
   fWeightMatrix0to1[23][0] = 0.589077968886589;
   fWeightMatrix0to1[24][0] = -1.44442813720482;
   fWeightMatrix0to1[25][0] = 0.243869346399434;
   fWeightMatrix0to1[26][0] = 0.842181937868331;
   fWeightMatrix0to1[27][0] = -1.18569869865708;
   fWeightMatrix0to1[0][1] = -1.67135462395363;
   fWeightMatrix0to1[1][1] = 0.23471516272294;
   fWeightMatrix0to1[2][1] = 0.92875928509338;
   fWeightMatrix0to1[3][1] = 2.34216911474766;
   fWeightMatrix0to1[4][1] = 0.158274856201319;
   fWeightMatrix0to1[5][1] = -0.48041226725606;
   fWeightMatrix0to1[6][1] = 1.35273171118741;
   fWeightMatrix0to1[7][1] = -0.47815243982135;
   fWeightMatrix0to1[8][1] = -0.82815828806813;
   fWeightMatrix0to1[9][1] = 2.26328371148822;
   fWeightMatrix0to1[10][1] = -1.44375335365916;
   fWeightMatrix0to1[11][1] = 0.576119714200932;
   fWeightMatrix0to1[12][1] = 1.6565926859257;
   fWeightMatrix0to1[13][1] = 1.40636593296623;
   fWeightMatrix0to1[14][1] = 1.13017345379633;
   fWeightMatrix0to1[15][1] = 1.3934627896379;
   fWeightMatrix0to1[16][1] = -0.0104494228494674;
   fWeightMatrix0to1[17][1] = -1.87641209848133;
   fWeightMatrix0to1[18][1] = 0.856097580998258;
   fWeightMatrix0to1[19][1] = -0.486407235690762;
   fWeightMatrix0to1[20][1] = 1.74789077110004;
   fWeightMatrix0to1[21][1] = 1.41673355171686;
   fWeightMatrix0to1[22][1] = 1.55029517599787;
   fWeightMatrix0to1[23][1] = 1.88164845778027;
   fWeightMatrix0to1[24][1] = -1.14935794538636;
   fWeightMatrix0to1[25][1] = 1.4086624624711;
   fWeightMatrix0to1[26][1] = -0.892442550550833;
   fWeightMatrix0to1[27][1] = -2.4078927344397;
   fWeightMatrix0to1[0][2] = -1.87281313533543;
   fWeightMatrix0to1[1][2] = -1.68816016828225;
   fWeightMatrix0to1[2][2] = 1.42858547794936;
   fWeightMatrix0to1[3][2] = 0.923186102505868;
   fWeightMatrix0to1[4][2] = -1.92083256899005;
   fWeightMatrix0to1[5][2] = 0.668745474458434;
   fWeightMatrix0to1[6][2] = -1.19662136744743;
   fWeightMatrix0to1[7][2] = 0.61732984663995;
   fWeightMatrix0to1[8][2] = 1.98658433828474;
   fWeightMatrix0to1[9][2] = 0.168766305642453;
   fWeightMatrix0to1[10][2] = -0.0137129712335406;
   fWeightMatrix0to1[11][2] = -1.19347040158522;
   fWeightMatrix0to1[12][2] = 0.739834954854157;
   fWeightMatrix0to1[13][2] = -0.37358663828943;
   fWeightMatrix0to1[14][2] = 0.6905887783683;
   fWeightMatrix0to1[15][2] = -0.704972551385368;
   fWeightMatrix0to1[16][2] = 1.32328486239195;
   fWeightMatrix0to1[17][2] = 0.757323243418021;
   fWeightMatrix0to1[18][2] = 1.27155634168906;
   fWeightMatrix0to1[19][2] = -0.349729948905129;
   fWeightMatrix0to1[20][2] = -1.57214009666737;
   fWeightMatrix0to1[21][2] = -1.54888602576183;
   fWeightMatrix0to1[22][2] = 0.957043727926068;
   fWeightMatrix0to1[23][2] = 1.97515184434989;
   fWeightMatrix0to1[24][2] = 2.20908486455023;
   fWeightMatrix0to1[25][2] = 0.923493582999294;
   fWeightMatrix0to1[26][2] = 2.29621538899626;
   fWeightMatrix0to1[27][2] = -1.1168642641576;
   fWeightMatrix0to1[0][3] = -2.44142084782695;
   fWeightMatrix0to1[1][3] = -0.103212924355615;
   fWeightMatrix0to1[2][3] = 1.25920307914675;
   fWeightMatrix0to1[3][3] = -0.470407799696107;
   fWeightMatrix0to1[4][3] = -1.90089572533671;
   fWeightMatrix0to1[5][3] = -0.649256568886388;
   fWeightMatrix0to1[6][3] = 0.111280336213041;
   fWeightMatrix0to1[7][3] = -0.231429068639762;
   fWeightMatrix0to1[8][3] = 1.4033551982591;
   fWeightMatrix0to1[9][3] = -1.08040386378325;
   fWeightMatrix0to1[10][3] = -0.657857517342999;
   fWeightMatrix0to1[11][3] = 1.81255890463366;
   fWeightMatrix0to1[12][3] = -0.786529511801974;
   fWeightMatrix0to1[13][3] = -0.837216327615003;
   fWeightMatrix0to1[14][3] = -1.3517371958294;
   fWeightMatrix0to1[15][3] = 1.67070924376283;
   fWeightMatrix0to1[16][3] = -1.25288816475064;
   fWeightMatrix0to1[17][3] = -2.01308470288096;
   fWeightMatrix0to1[18][3] = 1.24957239798281;
   fWeightMatrix0to1[19][3] = 1.06600661337841;
   fWeightMatrix0to1[20][3] = -0.871864938671171;
   fWeightMatrix0to1[21][3] = 1.82331822352352;
   fWeightMatrix0to1[22][3] = -0.505485394740095;
   fWeightMatrix0to1[23][3] = 0.246013998637593;
   fWeightMatrix0to1[24][3] = -0.260020923943695;
   fWeightMatrix0to1[25][3] = 0.631433251008078;
   fWeightMatrix0to1[26][3] = -1.34840406650084;
   fWeightMatrix0to1[27][3] = -0.535238382288684;
   fWeightMatrix0to1[0][4] = 2.76042720220964;
   fWeightMatrix0to1[1][4] = 0.40551351502562;
   fWeightMatrix0to1[2][4] = -1.2830732059911;
   fWeightMatrix0to1[3][4] = 1.60839690959105;
   fWeightMatrix0to1[4][4] = 0.358550412788128;
   fWeightMatrix0to1[5][4] = -1.29382598355457;
   fWeightMatrix0to1[6][4] = -0.7672084148783;
   fWeightMatrix0to1[7][4] = -1.23439372664458;
   fWeightMatrix0to1[8][4] = -1.25890368546041;
   fWeightMatrix0to1[9][4] = 0.655293293898583;
   fWeightMatrix0to1[10][4] = -0.545907270444956;
   fWeightMatrix0to1[11][4] = 1.41623804281999;
   fWeightMatrix0to1[12][4] = 0.936187033043141;
   fWeightMatrix0to1[13][4] = -0.915788026474378;
   fWeightMatrix0to1[14][4] = 1.30479485022065;
   fWeightMatrix0to1[15][4] = -0.63879883741836;
   fWeightMatrix0to1[16][4] = -1.40042910359906;
   fWeightMatrix0to1[17][4] = 0.862362776628502;
   fWeightMatrix0to1[18][4] = -0.429431694940409;
   fWeightMatrix0to1[19][4] = -1.13971194177768;
   fWeightMatrix0to1[20][4] = 1.0936327570521;
   fWeightMatrix0to1[21][4] = -1.31807571138566;
   fWeightMatrix0to1[22][4] = 0.0614030873409751;
   fWeightMatrix0to1[23][4] = 2.42831814685364;
   fWeightMatrix0to1[24][4] = 1.99718605397666;
   fWeightMatrix0to1[25][4] = -2.32109109222856;
   fWeightMatrix0to1[26][4] = 0.508895166346208;
   fWeightMatrix0to1[27][4] = 4.32623536730481;
   fWeightMatrix0to1[0][5] = 1.25026077896186;
   fWeightMatrix0to1[1][5] = 0.27583801258394;
   fWeightMatrix0to1[2][5] = -1.4637491804756;
   fWeightMatrix0to1[3][5] = 0.411952818224331;
   fWeightMatrix0to1[4][5] = 0.0382967028069525;
   fWeightMatrix0to1[5][5] = 1.34491019620903;
   fWeightMatrix0to1[6][5] = 0.974208016636815;
   fWeightMatrix0to1[7][5] = -0.558752027776682;
   fWeightMatrix0to1[8][5] = -0.125060234089556;
   fWeightMatrix0to1[9][5] = 0.594874900849311;
   fWeightMatrix0to1[10][5] = -1.16837544408204;
   fWeightMatrix0to1[11][5] = 0.576355504876109;
   fWeightMatrix0to1[12][5] = 1.23112595955451;
   fWeightMatrix0to1[13][5] = -0.571046162452135;
   fWeightMatrix0to1[14][5] = -1.20105713460699;
   fWeightMatrix0to1[15][5] = 0.542760643131777;
   fWeightMatrix0to1[16][5] = 1.30917046158677;
   fWeightMatrix0to1[17][5] = 0.538548644085342;
   fWeightMatrix0to1[18][5] = 1.34489376970158;
   fWeightMatrix0to1[19][5] = -1.02897151935272;
   fWeightMatrix0to1[20][5] = 1.7963966965172;
   fWeightMatrix0to1[21][5] = 0.650213560451046;
   fWeightMatrix0to1[22][5] = 0.646763294830101;
   fWeightMatrix0to1[23][5] = 0.633579337921071;
   fWeightMatrix0to1[24][5] = 0.801542045590895;
   fWeightMatrix0to1[25][5] = -0.461952281334389;
   fWeightMatrix0to1[26][5] = -0.450022851693168;
   fWeightMatrix0to1[27][5] = 1.17334540477356;
   fWeightMatrix0to1[0][6] = -0.263819407752863;
   fWeightMatrix0to1[1][6] = -0.395064430651036;
   fWeightMatrix0to1[2][6] = 1.39865016037844;
   fWeightMatrix0to1[3][6] = 1.42911767787598;
   fWeightMatrix0to1[4][6] = -0.416324722620113;
   fWeightMatrix0to1[5][6] = 2.34034654071692;
   fWeightMatrix0to1[6][6] = 1.96142413750987;
   fWeightMatrix0to1[7][6] = -1.81995661162463;
   fWeightMatrix0to1[8][6] = 1.40792555899419;
   fWeightMatrix0to1[9][6] = 0.440737216015079;
   fWeightMatrix0to1[10][6] = -0.140505461362338;
   fWeightMatrix0to1[11][6] = -1.64022807381477;
   fWeightMatrix0to1[12][6] = -1.70601890955708;
   fWeightMatrix0to1[13][6] = 0.896537414524755;
   fWeightMatrix0to1[14][6] = 2.42013285642906;
   fWeightMatrix0to1[15][6] = 0.656840829441917;
   fWeightMatrix0to1[16][6] = 0.3239740033969;
   fWeightMatrix0to1[17][6] = -0.589550304413944;
   fWeightMatrix0to1[18][6] = -0.218053078536778;
   fWeightMatrix0to1[19][6] = 1.48044293250379;
   fWeightMatrix0to1[20][6] = -0.122389851109297;
   fWeightMatrix0to1[21][6] = -0.297450783827736;
   fWeightMatrix0to1[22][6] = -1.14385343616394;
   fWeightMatrix0to1[23][6] = 1.11684277201471;
   fWeightMatrix0to1[24][6] = 1.73097764975861;
   fWeightMatrix0to1[25][6] = 1.27849622945952;
   fWeightMatrix0to1[26][6] = 0.384774721739365;
   fWeightMatrix0to1[27][6] = 0.11574154505254;
   fWeightMatrix0to1[0][7] = -1.01653344738608;
   fWeightMatrix0to1[1][7] = 1.31744659451891;
   fWeightMatrix0to1[2][7] = 0.643808642564207;
   fWeightMatrix0to1[3][7] = 0.155241499466275;
   fWeightMatrix0to1[4][7] = -0.397924287929117;
   fWeightMatrix0to1[5][7] = 0.459625420433216;
   fWeightMatrix0to1[6][7] = 1.00168133371491;
   fWeightMatrix0to1[7][7] = -1.97520585750458;
   fWeightMatrix0to1[8][7] = 0.768852371462838;
   fWeightMatrix0to1[9][7] = 1.17589123547142;
   fWeightMatrix0to1[10][7] = -1.0330918792537;
   fWeightMatrix0to1[11][7] = -0.108091115886416;
   fWeightMatrix0to1[12][7] = 1.63072875187145;
   fWeightMatrix0to1[13][7] = 1.3843822254671;
   fWeightMatrix0to1[14][7] = -0.725736983698597;
   fWeightMatrix0to1[15][7] = 0.150721957532187;
   fWeightMatrix0to1[16][7] = -1.33302092261275;
   fWeightMatrix0to1[17][7] = -1.28414700469227;
   fWeightMatrix0to1[18][7] = 0.973693918306018;
   fWeightMatrix0to1[19][7] = 0.702592169665992;
   fWeightMatrix0to1[20][7] = 0.750606728239183;
   fWeightMatrix0to1[21][7] = 0.393094714591055;
   fWeightMatrix0to1[22][7] = 1.97921602639176;
   fWeightMatrix0to1[23][7] = -0.498267507215174;
   fWeightMatrix0to1[24][7] = -1.60578875540817;
   fWeightMatrix0to1[25][7] = -0.801901089277838;
   fWeightMatrix0to1[26][7] = -0.937885852269257;
   fWeightMatrix0to1[27][7] = -0.473718832456364;
   fWeightMatrix0to1[0][8] = 1.42562035869354;
   fWeightMatrix0to1[1][8] = -0.827680612523137;
   fWeightMatrix0to1[2][8] = 0.923443100413696;
   fWeightMatrix0to1[3][8] = 0.68575822908963;
   fWeightMatrix0to1[4][8] = -1.65790456384333;
   fWeightMatrix0to1[5][8] = -1.21174608480434;
   fWeightMatrix0to1[6][8] = 0.55372024385572;
   fWeightMatrix0to1[7][8] = -0.163281578789619;
   fWeightMatrix0to1[8][8] = 1.35979228767198;
   fWeightMatrix0to1[9][8] = -0.866963229768234;
   fWeightMatrix0to1[10][8] = 0.957872601452678;
   fWeightMatrix0to1[11][8] = -2.3312544972528;
   fWeightMatrix0to1[12][8] = 1.20583816505857;
   fWeightMatrix0to1[13][8] = 0.369138631588529;
   fWeightMatrix0to1[14][8] = -3.24943252023616;
   fWeightMatrix0to1[15][8] = 0.823594478312065;
   fWeightMatrix0to1[16][8] = -1.16836493676659;
   fWeightMatrix0to1[17][8] = -0.364311359925356;
   fWeightMatrix0to1[18][8] = -3.33009717422305;
   fWeightMatrix0to1[19][8] = -0.864012040108902;
   fWeightMatrix0to1[20][8] = -1.88871264864371;
   fWeightMatrix0to1[21][8] = -0.162333673862379;
   fWeightMatrix0to1[22][8] = -1.13298390404827;
   fWeightMatrix0to1[23][8] = -0.796629489288098;
   fWeightMatrix0to1[24][8] = 1.11105410221201;
   fWeightMatrix0to1[25][8] = -1.32584860361008;
   fWeightMatrix0to1[26][8] = 0.279065872622363;
   fWeightMatrix0to1[27][8] = -2.08224744203303;
   fWeightMatrix0to1[0][9] = 0.438112768395778;
   fWeightMatrix0to1[1][9] = 2.00428979504372;
   fWeightMatrix0to1[2][9] = 1.45801495624617;
   fWeightMatrix0to1[3][9] = -0.197818963290197;
   fWeightMatrix0to1[4][9] = -0.568315513328901;
   fWeightMatrix0to1[5][9] = -1.48702088165635;
   fWeightMatrix0to1[6][9] = -0.842829675223469;
   fWeightMatrix0to1[7][9] = -1.84194505148611;
   fWeightMatrix0to1[8][9] = 0.30359052580508;
   fWeightMatrix0to1[9][9] = 0.572764510592303;
   fWeightMatrix0to1[10][9] = 1.28310197137488;
   fWeightMatrix0to1[11][9] = -0.383366441875738;
   fWeightMatrix0to1[12][9] = -0.695136477506205;
   fWeightMatrix0to1[13][9] = -0.768852463961868;
   fWeightMatrix0to1[14][9] = -0.416629692811194;
   fWeightMatrix0to1[15][9] = 0.369222975615395;
   fWeightMatrix0to1[16][9] = 1.56467568073838;
   fWeightMatrix0to1[17][9] = -0.867501277722249;
   fWeightMatrix0to1[18][9] = -2.1258959806278;
   fWeightMatrix0to1[19][9] = 0.942052279761996;
   fWeightMatrix0to1[20][9] = 1.28191937159694;
   fWeightMatrix0to1[21][9] = 0.487751592334524;
   fWeightMatrix0to1[22][9] = -0.532491246595559;
   fWeightMatrix0to1[23][9] = -0.59418964759361;
   fWeightMatrix0to1[24][9] = 1.67796973111967;
   fWeightMatrix0to1[25][9] = 1.20935017990372;
   fWeightMatrix0to1[26][9] = 1.05918107884899;
   fWeightMatrix0to1[27][9] = -1.10501479008267;
   fWeightMatrix0to1[0][10] = 0.847326528690629;
   fWeightMatrix0to1[1][10] = -0.472646225548342;
   fWeightMatrix0to1[2][10] = -1.1004508848018;
   fWeightMatrix0to1[3][10] = -0.827094276373087;
   fWeightMatrix0to1[4][10] = -1.73592117116712;
   fWeightMatrix0to1[5][10] = -1.39551437478658;
   fWeightMatrix0to1[6][10] = -1.19538161984524;
   fWeightMatrix0to1[7][10] = 1.73011886662941;
   fWeightMatrix0to1[8][10] = -1.29806788184929;
   fWeightMatrix0to1[9][10] = 1.79932098147836;
   fWeightMatrix0to1[10][10] = -1.87232911530541;
   fWeightMatrix0to1[11][10] = 0.585724203481162;
   fWeightMatrix0to1[12][10] = -1.1665975717958;
   fWeightMatrix0to1[13][10] = 0.677042051220977;
   fWeightMatrix0to1[14][10] = 1.35102864737317;
   fWeightMatrix0to1[15][10] = -1.66694226303048;
   fWeightMatrix0to1[16][10] = -0.00510837675505413;
   fWeightMatrix0to1[17][10] = 0.490869796385726;
   fWeightMatrix0to1[18][10] = -0.805851843551275;
   fWeightMatrix0to1[19][10] = -1.32407530691214;
   fWeightMatrix0to1[20][10] = -1.45098612777218;
   fWeightMatrix0to1[21][10] = -0.767284697789205;
   fWeightMatrix0to1[22][10] = 1.66856791240405;
   fWeightMatrix0to1[23][10] = -0.972934229481774;
   fWeightMatrix0to1[24][10] = 0.577768070747281;
   fWeightMatrix0to1[25][10] = -1.08166363141424;
   fWeightMatrix0to1[26][10] = -2.16381686829336;
   fWeightMatrix0to1[27][10] = 0.18593451878915;
   fWeightMatrix0to1[0][11] = 0.773851978249674;
   fWeightMatrix0to1[1][11] = -1.40356007483205;
   fWeightMatrix0to1[2][11] = 1.22156818464245;
   fWeightMatrix0to1[3][11] = -0.946633623294674;
   fWeightMatrix0to1[4][11] = -0.558262205190142;
   fWeightMatrix0to1[5][11] = 1.55365130150158;
   fWeightMatrix0to1[6][11] = -0.621427918475759;
   fWeightMatrix0to1[7][11] = -0.559127644872432;
   fWeightMatrix0to1[8][11] = 2.44543543105702;
   fWeightMatrix0to1[9][11] = -1.70973171029018;
   fWeightMatrix0to1[10][11] = 0.768030451904279;
   fWeightMatrix0to1[11][11] = 0.135523962521561;
   fWeightMatrix0to1[12][11] = -1.00066291019754;
   fWeightMatrix0to1[13][11] = -0.737537585532196;
   fWeightMatrix0to1[14][11] = -0.935476887591832;
   fWeightMatrix0to1[15][11] = -1.8222974187721;
   fWeightMatrix0to1[16][11] = 0.526575238235052;
   fWeightMatrix0to1[17][11] = 1.95000267496328;
   fWeightMatrix0to1[18][11] = 0.893366579409487;
   fWeightMatrix0to1[19][11] = 1.99567773198168;
   fWeightMatrix0to1[20][11] = -1.30634907377354;
   fWeightMatrix0to1[21][11] = 1.02780636990052;
   fWeightMatrix0to1[22][11] = -2.34470710973719;
   fWeightMatrix0to1[23][11] = 0.369890804181164;
   fWeightMatrix0to1[24][11] = -1.31640042722906;
   fWeightMatrix0to1[25][11] = -2.13182930827843;
   fWeightMatrix0to1[26][11] = -0.604655263821409;
   fWeightMatrix0to1[27][11] = 1.58220665854092;
   fWeightMatrix0to1[0][12] = 1.14928533871398;
   fWeightMatrix0to1[1][12] = 0.672395364876043;
   fWeightMatrix0to1[2][12] = 0.320987623697183;
   fWeightMatrix0to1[3][12] = -0.796407335176481;
   fWeightMatrix0to1[4][12] = 0.444157057761435;
   fWeightMatrix0to1[5][12] = -0.0250760231871653;
   fWeightMatrix0to1[6][12] = 3.01077665258462;
   fWeightMatrix0to1[7][12] = -1.66351226961175;
   fWeightMatrix0to1[8][12] = -0.25328585314005;
   fWeightMatrix0to1[9][12] = -1.21900031189484;
   fWeightMatrix0to1[10][12] = -0.621132717352987;
   fWeightMatrix0to1[11][12] = 0.423392148956559;
   fWeightMatrix0to1[12][12] = 0.881915312697729;
   fWeightMatrix0to1[13][12] = 0.31145674648371;
   fWeightMatrix0to1[14][12] = 2.49883598249994;
   fWeightMatrix0to1[15][12] = 0.702302594785815;
   fWeightMatrix0to1[16][12] = 0.474261009690453;
   fWeightMatrix0to1[17][12] = -0.0103199120132707;
   fWeightMatrix0to1[18][12] = 0.77860139608968;
   fWeightMatrix0to1[19][12] = -3.04610680338373;
   fWeightMatrix0to1[20][12] = -1.22310071812775;
   fWeightMatrix0to1[21][12] = 0.891892176121012;
   fWeightMatrix0to1[22][12] = -0.476884983043609;
   fWeightMatrix0to1[23][12] = -1.87170192691858;
   fWeightMatrix0to1[24][12] = 0.822218890292892;
   fWeightMatrix0to1[25][12] = 0.442584342160943;
   fWeightMatrix0to1[26][12] = -0.966800759373388;
   fWeightMatrix0to1[27][12] = -2.27577533623881;
   fWeightMatrix0to1[0][13] = 0.185346462972376;
   fWeightMatrix0to1[1][13] = -1.26262107836078;
   fWeightMatrix0to1[2][13] = -1.87543846415864;
   fWeightMatrix0to1[3][13] = -0.0455238749757199;
   fWeightMatrix0to1[4][13] = -0.63157014952503;
   fWeightMatrix0to1[5][13] = -0.895068253087488;
   fWeightMatrix0to1[6][13] = 0.231655062326592;
   fWeightMatrix0to1[7][13] = -1.3646562761799;
   fWeightMatrix0to1[8][13] = -0.987518050397573;
   fWeightMatrix0to1[9][13] = 1.7466527734762;
   fWeightMatrix0to1[10][13] = 0.392558037169626;
   fWeightMatrix0to1[11][13] = 0.891870972351209;
   fWeightMatrix0to1[12][13] = -0.158814275853027;
   fWeightMatrix0to1[13][13] = 1.6970652195167;
   fWeightMatrix0to1[14][13] = 0.156544652749444;
   fWeightMatrix0to1[15][13] = 0.135467709472565;
   fWeightMatrix0to1[16][13] = -0.509005803925604;
   fWeightMatrix0to1[17][13] = -0.639308512501906;
   fWeightMatrix0to1[18][13] = -0.311790788228434;
   fWeightMatrix0to1[19][13] = 0.363744203172186;
   fWeightMatrix0to1[20][13] = 1.10013780132535;
   fWeightMatrix0to1[21][13] = 0.315496193002039;
   fWeightMatrix0to1[22][13] = 1.1705499318973;
   fWeightMatrix0to1[23][13] = 0.399328775515978;
   fWeightMatrix0to1[24][13] = 1.56888984755206;
   fWeightMatrix0to1[25][13] = -0.248510791040094;
   fWeightMatrix0to1[26][13] = 1.09153121952818;
   fWeightMatrix0to1[27][13] = 0.221848397460082;
   fWeightMatrix0to1[0][14] = -1.7754864946488;
   fWeightMatrix0to1[1][14] = -0.204638884736618;
   fWeightMatrix0to1[2][14] = -1.14317900698432;
   fWeightMatrix0to1[3][14] = 0.630403498562349;
   fWeightMatrix0to1[4][14] = 1.44765932996342;
   fWeightMatrix0to1[5][14] = 0.846741104252273;
   fWeightMatrix0to1[6][14] = -0.0336389083795015;
   fWeightMatrix0to1[7][14] = -0.447698161223559;
   fWeightMatrix0to1[8][14] = 1.60861972072822;
   fWeightMatrix0to1[9][14] = 1.95700442743948;
   fWeightMatrix0to1[10][14] = 0.0434106126408193;
   fWeightMatrix0to1[11][14] = -1.2969090033759;
   fWeightMatrix0to1[12][14] = 1.34847584882668;
   fWeightMatrix0to1[13][14] = -1.54345461996804;
   fWeightMatrix0to1[14][14] = 0.56510423606162;
   fWeightMatrix0to1[15][14] = 0.961794931580856;
   fWeightMatrix0to1[16][14] = -0.223587972193101;
   fWeightMatrix0to1[17][14] = -0.910266612255329;
   fWeightMatrix0to1[18][14] = -0.654460696442165;
   fWeightMatrix0to1[19][14] = -0.317440417654137;
   fWeightMatrix0to1[20][14] = 0.691803103578737;
   fWeightMatrix0to1[21][14] = -1.90195335282906;
   fWeightMatrix0to1[22][14] = 0.371842894103662;
   fWeightMatrix0to1[23][14] = -0.422879054792392;
   fWeightMatrix0to1[24][14] = 1.72186581431932;
   fWeightMatrix0to1[25][14] = 1.2873460703251;
   fWeightMatrix0to1[26][14] = 1.41645306324813;
   fWeightMatrix0to1[27][14] = -0.144605431929612;
   fWeightMatrix0to1[0][15] = 0.0506056736064921;
   fWeightMatrix0to1[1][15] = 0.322694417570298;
   fWeightMatrix0to1[2][15] = 1.95335564545203;
   fWeightMatrix0to1[3][15] = -2.07225756230551;
   fWeightMatrix0to1[4][15] = -1.42944241608258;
   fWeightMatrix0to1[5][15] = -0.812444431985277;
   fWeightMatrix0to1[6][15] = -1.14083675889512;
   fWeightMatrix0to1[7][15] = -1.79428960566752;
   fWeightMatrix0to1[8][15] = -1.87856706831064;
   fWeightMatrix0to1[9][15] = 0.962846423925697;
   fWeightMatrix0to1[10][15] = -0.116169881094335;
   fWeightMatrix0to1[11][15] = -1.70309049431643;
   fWeightMatrix0to1[12][15] = -1.26840083738139;
   fWeightMatrix0to1[13][15] = 0.00117498980646347;
   fWeightMatrix0to1[14][15] = 0.567861573225062;
   fWeightMatrix0to1[15][15] = 0.509664660207236;
   fWeightMatrix0to1[16][15] = 1.27886413925365;
   fWeightMatrix0to1[17][15] = -0.769771440852761;
   fWeightMatrix0to1[18][15] = -1.00391185803922;
   fWeightMatrix0to1[19][15] = 0.0281816385176198;
   fWeightMatrix0to1[20][15] = -0.902397267055344;
   fWeightMatrix0to1[21][15] = -1.45579355095814;
   fWeightMatrix0to1[22][15] = -0.450779866105626;
   fWeightMatrix0to1[23][15] = 0.319978507678078;
   fWeightMatrix0to1[24][15] = -1.53499179331665;
   fWeightMatrix0to1[25][15] = 1.14705783835777;
   fWeightMatrix0to1[26][15] = 1.40076215336855;
   fWeightMatrix0to1[27][15] = 0.646893519007586;
   fWeightMatrix0to1[0][16] = 0.4694421532084;
   fWeightMatrix0to1[1][16] = -0.820101895822065;
   fWeightMatrix0to1[2][16] = 1.7088050719263;
   fWeightMatrix0to1[3][16] = -1.10573334368271;
   fWeightMatrix0to1[4][16] = -0.208162796151537;
   fWeightMatrix0to1[5][16] = 0.947814144381939;
   fWeightMatrix0to1[6][16] = 0.124465118520726;
   fWeightMatrix0to1[7][16] = -1.15068661874911;
   fWeightMatrix0to1[8][16] = 0.18948279362673;
   fWeightMatrix0to1[9][16] = -1.38402762449762;
   fWeightMatrix0to1[10][16] = 1.03517173660956;
   fWeightMatrix0to1[11][16] = 1.20990106472295;
   fWeightMatrix0to1[12][16] = 1.06602779752069;
   fWeightMatrix0to1[13][16] = -0.0435575298533537;
   fWeightMatrix0to1[14][16] = 0.211889419922864;
   fWeightMatrix0to1[15][16] = -0.24136498799448;
   fWeightMatrix0to1[16][16] = 0.961148984022212;
   fWeightMatrix0to1[17][16] = 0.391408994062557;
   fWeightMatrix0to1[18][16] = -0.586235717501918;
   fWeightMatrix0to1[19][16] = -0.445284847980899;
   fWeightMatrix0to1[20][16] = 0.653797464881245;
   fWeightMatrix0to1[21][16] = 1.4285041138242;
   fWeightMatrix0to1[22][16] = 0.405051359541353;
   fWeightMatrix0to1[23][16] = -0.546610169306699;
   fWeightMatrix0to1[24][16] = -1.70086074484951;
   fWeightMatrix0to1[25][16] = 1.28203715946449;
   fWeightMatrix0to1[26][16] = -0.192464215712934;
   fWeightMatrix0to1[27][16] = 0.246901337495446;
   fWeightMatrix0to1[0][17] = -0.0246775620177654;
   fWeightMatrix0to1[1][17] = -1.35879769642395;
   fWeightMatrix0to1[2][17] = 1.07541010575752;
   fWeightMatrix0to1[3][17] = 1.20915071708803;
   fWeightMatrix0to1[4][17] = -0.76857575032744;
   fWeightMatrix0to1[5][17] = -0.357243504408792;
   fWeightMatrix0to1[6][17] = 3.14592288512204;
   fWeightMatrix0to1[7][17] = 1.43464706562893;
   fWeightMatrix0to1[8][17] = 0.186964365759068;
   fWeightMatrix0to1[9][17] = 0.128246710255927;
   fWeightMatrix0to1[10][17] = -1.79616194958785;
   fWeightMatrix0to1[11][17] = -0.821142689956169;
   fWeightMatrix0to1[12][17] = -0.284184480071273;
   fWeightMatrix0to1[13][17] = 0.666405930612455;
   fWeightMatrix0to1[14][17] = -0.755525813497709;
   fWeightMatrix0to1[15][17] = -4.2105603219619;
   fWeightMatrix0to1[16][17] = -2.08191636267845;
   fWeightMatrix0to1[17][17] = -1.75494519404826;
   fWeightMatrix0to1[18][17] = -0.637217636558287;
   fWeightMatrix0to1[19][17] = -3.13349550936279;
   fWeightMatrix0to1[20][17] = 0.596440067603559;
   fWeightMatrix0to1[21][17] = -0.338324097176829;
   fWeightMatrix0to1[22][17] = 1.38862627154725;
   fWeightMatrix0to1[23][17] = 0.168196835057685;
   fWeightMatrix0to1[24][17] = -1.57752860412874;
   fWeightMatrix0to1[25][17] = 1.43379192208887;
   fWeightMatrix0to1[26][17] = 1.93001213742881;
   fWeightMatrix0to1[27][17] = 0.665084177116693;
   fWeightMatrix0to1[0][18] = -0.60382737525552;
   fWeightMatrix0to1[1][18] = -0.882730045562579;
   fWeightMatrix0to1[2][18] = 1.48642876070171;
   fWeightMatrix0to1[3][18] = -1.40492164943455;
   fWeightMatrix0to1[4][18] = 0.464220885354735;
   fWeightMatrix0to1[5][18] = -0.792294696072909;
   fWeightMatrix0to1[6][18] = 0.824753828030036;
   fWeightMatrix0to1[7][18] = -0.718522535510778;
   fWeightMatrix0to1[8][18] = 0.317786236853649;
   fWeightMatrix0to1[9][18] = 0.207576580286322;
   fWeightMatrix0to1[10][18] = 0.220920942447457;
   fWeightMatrix0to1[11][18] = -0.495277946041008;
   fWeightMatrix0to1[12][18] = -0.863106181903932;
   fWeightMatrix0to1[13][18] = 0.920946223277758;
   fWeightMatrix0to1[14][18] = 0.547239897641641;
   fWeightMatrix0to1[15][18] = 1.13909335519563;
   fWeightMatrix0to1[16][18] = 1.70839866399435;
   fWeightMatrix0to1[17][18] = -1.46656038957929;
   fWeightMatrix0to1[18][18] = 1.2142586036059;
   fWeightMatrix0to1[19][18] = -1.91651848217494;
   fWeightMatrix0to1[20][18] = 1.44270192131246;
   fWeightMatrix0to1[21][18] = 1.61381761090882;
   fWeightMatrix0to1[22][18] = 0.558657102487574;
   fWeightMatrix0to1[23][18] = 2.07782100959252;
   fWeightMatrix0to1[24][18] = 1.50554883311902;
   fWeightMatrix0to1[25][18] = -1.74534231694192;
   fWeightMatrix0to1[26][18] = -0.16440811570699;
   fWeightMatrix0to1[27][18] = -0.603517044512285;
   fWeightMatrix0to1[0][19] = 1.57496969372177;
   fWeightMatrix0to1[1][19] = -0.1695855428519;
   fWeightMatrix0to1[2][19] = -0.241823257852447;
   fWeightMatrix0to1[3][19] = -0.901485057670257;
   fWeightMatrix0to1[4][19] = 0.150433362196989;
   fWeightMatrix0to1[5][19] = -1.54162377494429;
   fWeightMatrix0to1[6][19] = -1.4307972417156;
   fWeightMatrix0to1[7][19] = -2.00634553100628;
   fWeightMatrix0to1[8][19] = -0.119167773554784;
   fWeightMatrix0to1[9][19] = 0.69006392445034;
   fWeightMatrix0to1[10][19] = -0.69080458760229;
   fWeightMatrix0to1[11][19] = -1.46213860088295;
   fWeightMatrix0to1[12][19] = 0.877798886415558;
   fWeightMatrix0to1[13][19] = 0.0285062304719252;
   fWeightMatrix0to1[14][19] = 0.820399921503656;
   fWeightMatrix0to1[15][19] = -2.42260461761131;
   fWeightMatrix0to1[16][19] = 2.23320297677199;
   fWeightMatrix0to1[17][19] = -0.497105468230528;
   fWeightMatrix0to1[18][19] = 1.02997599925417;
   fWeightMatrix0to1[19][19] = 0.953492140058982;
   fWeightMatrix0to1[20][19] = -0.500290874226478;
   fWeightMatrix0to1[21][19] = -0.891004645971181;
   fWeightMatrix0to1[22][19] = -0.228450122007003;
   fWeightMatrix0to1[23][19] = -1.24556629422063;
   fWeightMatrix0to1[24][19] = -0.473308201090928;
   fWeightMatrix0to1[25][19] = -0.871777271736228;
   fWeightMatrix0to1[26][19] = 1.52508483572607;
   fWeightMatrix0to1[27][19] = 0.61051271081324;
   fWeightMatrix0to1[0][20] = 1.71676783391666;
   fWeightMatrix0to1[1][20] = 1.83167125096939;
   fWeightMatrix0to1[2][20] = 1.35586733591109;
   fWeightMatrix0to1[3][20] = 1.51823470130106;
   fWeightMatrix0to1[4][20] = 0.837408188525056;
   fWeightMatrix0to1[5][20] = 0.429721250255021;
   fWeightMatrix0to1[6][20] = -0.825408050559001;
   fWeightMatrix0to1[7][20] = -1.58199810406938;
   fWeightMatrix0to1[8][20] = -0.896574136607171;
   fWeightMatrix0to1[9][20] = -0.20963195125855;
   fWeightMatrix0to1[10][20] = 1.00254522167125;
   fWeightMatrix0to1[11][20] = 0.13432185486163;
   fWeightMatrix0to1[12][20] = 0.172283723861559;
   fWeightMatrix0to1[13][20] = 1.36425323778703;
   fWeightMatrix0to1[14][20] = 0.890802909264711;
   fWeightMatrix0to1[15][20] = -0.868092347929148;
   fWeightMatrix0to1[16][20] = 0.959507621218504;
   fWeightMatrix0to1[17][20] = -1.35308791826365;
   fWeightMatrix0to1[18][20] = 1.02853485551623;
   fWeightMatrix0to1[19][20] = -1.87934872348482;
   fWeightMatrix0to1[20][20] = 0.499789216532373;
   fWeightMatrix0to1[21][20] = 0.254416785489692;
   fWeightMatrix0to1[22][20] = 0.891520676349811;
   fWeightMatrix0to1[23][20] = -1.5248529183832;
   fWeightMatrix0to1[24][20] = 0.151361815887345;
   fWeightMatrix0to1[25][20] = -1.42439193989677;
   fWeightMatrix0to1[26][20] = 0.216104529255206;
   fWeightMatrix0to1[27][20] = 1.69542816200225;
   fWeightMatrix0to1[0][21] = 0.408064617534066;
   fWeightMatrix0to1[1][21] = 0.734494051939048;
   fWeightMatrix0to1[2][21] = -1.84549505252392;
   fWeightMatrix0to1[3][21] = 1.3478093140274;
   fWeightMatrix0to1[4][21] = 0.0874379228791244;
   fWeightMatrix0to1[5][21] = 1.71172610531952;
   fWeightMatrix0to1[6][21] = -0.837553516515655;
   fWeightMatrix0to1[7][21] = -0.788753508105631;
   fWeightMatrix0to1[8][21] = 2.1912720111091;
   fWeightMatrix0to1[9][21] = -1.37420047500573;
   fWeightMatrix0to1[10][21] = -1.94521795129952;
   fWeightMatrix0to1[11][21] = -1.12822457216995;
   fWeightMatrix0to1[12][21] = 0.956703564747092;
   fWeightMatrix0to1[13][21] = 1.1324884689762;
   fWeightMatrix0to1[14][21] = 0.269384715853931;
   fWeightMatrix0to1[15][21] = -0.0966038820663132;
   fWeightMatrix0to1[16][21] = 1.23087862742089;
   fWeightMatrix0to1[17][21] = 0.759383373309428;
   fWeightMatrix0to1[18][21] = 0.0394089782180591;
   fWeightMatrix0to1[19][21] = -1.59149649530039;
   fWeightMatrix0to1[20][21] = -1.02094490511994;
   fWeightMatrix0to1[21][21] = 0.555100809584991;
   fWeightMatrix0to1[22][21] = -0.586363672054137;
   fWeightMatrix0to1[23][21] = 1.01967010743522;
   fWeightMatrix0to1[24][21] = -0.434612403637163;
   fWeightMatrix0to1[25][21] = 0.388782052348531;
   fWeightMatrix0to1[26][21] = -0.887862204186924;
   fWeightMatrix0to1[27][21] = 0.1838185156654;
   fWeightMatrix0to1[0][22] = 0.281007182717311;
   fWeightMatrix0to1[1][22] = 1.53457442757992;
   fWeightMatrix0to1[2][22] = -0.741803515957722;
   fWeightMatrix0to1[3][22] = -1.03213419940801;
   fWeightMatrix0to1[4][22] = 1.94653824745681;
   fWeightMatrix0to1[5][22] = 0.745656180963199;
   fWeightMatrix0to1[6][22] = 1.31328744018715;
   fWeightMatrix0to1[7][22] = -0.175283317263272;
   fWeightMatrix0to1[8][22] = -0.752130008755316;
   fWeightMatrix0to1[9][22] = -0.602335727606638;
   fWeightMatrix0to1[10][22] = -1.83728811745525;
   fWeightMatrix0to1[11][22] = -0.338480920811073;
   fWeightMatrix0to1[12][22] = -0.916035548289191;
   fWeightMatrix0to1[13][22] = 0.0635288345591192;
   fWeightMatrix0to1[14][22] = 0.249955154576064;
   fWeightMatrix0to1[15][22] = 0.000888357322897474;
   fWeightMatrix0to1[16][22] = 1.44638085707627;
   fWeightMatrix0to1[17][22] = -2.2415260375788;
   fWeightMatrix0to1[18][22] = -1.2308874346714;
   fWeightMatrix0to1[19][22] = -0.320976410868006;
   fWeightMatrix0to1[20][22] = -0.649198506249741;
   fWeightMatrix0to1[21][22] = 1.1006620608472;
   fWeightMatrix0to1[22][22] = 1.23952346847516;
   fWeightMatrix0to1[23][22] = -1.26838574498626;
   fWeightMatrix0to1[24][22] = 0.00390670089758732;
   fWeightMatrix0to1[25][22] = -1.18703202657802;
   fWeightMatrix0to1[26][22] = 1.3803839791705;
   fWeightMatrix0to1[27][22] = -1.50671075139963;
   fWeightMatrix0to1[0][23] = -1.18014983432863;
   fWeightMatrix0to1[1][23] = -0.798369911801071;
   fWeightMatrix0to1[2][23] = -1.75630517397912;
   fWeightMatrix0to1[3][23] = 1.33965835596328;
   fWeightMatrix0to1[4][23] = -0.259172470240758;
   fWeightMatrix0to1[5][23] = 0.93874392386776;
   fWeightMatrix0to1[6][23] = -0.0954520906515803;
   fWeightMatrix0to1[7][23] = -0.94428223109968;
   fWeightMatrix0to1[8][23] = -1.57274446993968;
   fWeightMatrix0to1[9][23] = -1.84817282411826;
   fWeightMatrix0to1[10][23] = 0.853672978306418;
   fWeightMatrix0to1[11][23] = 0.783576268078134;
   fWeightMatrix0to1[12][23] = -0.0423029836474769;
   fWeightMatrix0to1[13][23] = -1.24585675111341;
   fWeightMatrix0to1[14][23] = 0.140808375083834;
   fWeightMatrix0to1[15][23] = -0.443246753290055;
   fWeightMatrix0to1[16][23] = -1.95619222190673;
   fWeightMatrix0to1[17][23] = 2.09228662750323;
   fWeightMatrix0to1[18][23] = 0.252917311238857;
   fWeightMatrix0to1[19][23] = -1.32829570780626;
   fWeightMatrix0to1[20][23] = -1.68639503483769;
   fWeightMatrix0to1[21][23] = -1.93670643735863;
   fWeightMatrix0to1[22][23] = -0.0426595436455446;
   fWeightMatrix0to1[23][23] = 1.18809978202861;
   fWeightMatrix0to1[24][23] = 1.17490031834907;
   fWeightMatrix0to1[25][23] = 0.510271388010892;
   fWeightMatrix0to1[26][23] = -2.49835455627649;
   fWeightMatrix0to1[27][23] = -1.23127783008842;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.727228587857727;
   fWeightMatrix1to2[0][1] = 0.149539654847092;
   fWeightMatrix1to2[0][2] = 1.18181998529452;
   fWeightMatrix1to2[0][3] = -0.171385048004521;
   fWeightMatrix1to2[0][4] = 0.789177530357601;
   fWeightMatrix1to2[0][5] = -0.369216569043336;
   fWeightMatrix1to2[0][6] = -0.459220788953652;
   fWeightMatrix1to2[0][7] = -1.42344114556774;
   fWeightMatrix1to2[0][8] = 0.751963071443317;
   fWeightMatrix1to2[0][9] = -0.00391233373009442;
   fWeightMatrix1to2[0][10] = 0.903604846403636;
   fWeightMatrix1to2[0][11] = -0.44985810548454;
   fWeightMatrix1to2[0][12] = 0.607451789935923;
   fWeightMatrix1to2[0][13] = -0.825567693005907;
   fWeightMatrix1to2[0][14] = 0.583221220149184;
   fWeightMatrix1to2[0][15] = -0.479625721966399;
   fWeightMatrix1to2[0][16] = -1.04100105809356;
   fWeightMatrix1to2[0][17] = -1.34559922850717;
   fWeightMatrix1to2[0][18] = 0.595590404195591;
   fWeightMatrix1to2[0][19] = 0.17476501719208;
   fWeightMatrix1to2[0][20] = -0.0123713580338004;
   fWeightMatrix1to2[0][21] = -0.732867143197317;
   fWeightMatrix1to2[0][22] = 0.394868205950584;
   fWeightMatrix1to2[0][23] = -0.385410606842359;
   fWeightMatrix1to2[0][24] = 0.173352617830577;
   fWeightMatrix1to2[0][25] = 0.419051619138261;
   fWeightMatrix1to2[0][26] = -0.864031663429599;
   fWeightMatrix1to2[0][27] = 0.653510358790349;
   fWeightMatrix1to2[0][28] = 1.50235767292999;
}

inline double ReadMLPTunedSigmoid::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPTunedSigmoid::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLPTunedSigmoid::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPTunedSigmoid::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPTunedSigmoid::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPTunedSigmoid::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 14;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 14;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 14;
   fMin_1[0][1] = 2;
   fMax_1[0][1] = 5;
   fMin_1[1][1] = 2;
   fMax_1[1][1] = 6;
   fMin_1[2][1] = 2;
   fMax_1[2][1] = 6;
   fMin_1[0][2] = 20.3211650848;
   fMax_1[0][2] = 779.356506348;
   fMin_1[1][2] = 20.345867157;
   fMax_1[1][2] = 1187.93493652;
   fMin_1[2][2] = 20.3211650848;
   fMax_1[2][2] = 1187.93493652;
   fMin_1[0][3] = 20.0031757355;
   fMax_1[0][3] = 557.967102051;
   fMin_1[1][3] = 20.0051765442;
   fMax_1[1][3] = 699.98260498;
   fMin_1[2][3] = 20.0031757355;
   fMax_1[2][3] = 699.98260498;
   fMin_1[0][4] = 31.5104141235;
   fMax_1[0][4] = 904.02545166;
   fMin_1[1][4] = 31.4223308563;
   fMax_1[1][4] = 686.358764648;
   fMin_1[2][4] = 31.4223308563;
   fMax_1[2][4] = 904.02545166;
   fMin_1[0][5] = 30.001663208;
   fMax_1[0][5] = 298.117797852;
   fMin_1[1][5] = 30.0022945404;
   fMax_1[1][5] = 239.681365967;
   fMin_1[2][5] = 30.001663208;
   fMax_1[2][5] = 298.117797852;
   fMin_1[0][6] = 20.0059547424;
   fMax_1[0][6] = 438.634124756;
   fMin_1[1][6] = 20.0106868744;
   fMax_1[1][6] = 480.95715332;
   fMin_1[2][6] = 20.0059547424;
   fMax_1[2][6] = 480.95715332;
   fMin_1[0][7] = 20.0082492828;
   fMax_1[0][7] = 524.356201172;
   fMin_1[1][7] = 20.003408432;
   fMax_1[1][7] = 625.883056641;
   fMin_1[2][7] = 20.003408432;
   fMax_1[2][7] = 625.883056641;
   fMin_1[0][8] = 0.267349809408;
   fMax_1[0][8] = 4.46294641495;
   fMin_1[1][8] = 0.31856662035;
   fMax_1[1][8] = 5.02747869492;
   fMin_1[2][8] = 0.267349809408;
   fMax_1[2][8] = 5.02747869492;
   fMin_1[0][9] = 0.410064458847;
   fMax_1[0][9] = 6.35713100433;
   fMin_1[1][9] = 0.460506469011;
   fMax_1[1][9] = 6.81951332092;
   fMin_1[2][9] = 0.410064458847;
   fMax_1[2][9] = 6.81951332092;
   fMin_1[0][10] = 0.548147320747;
   fMax_1[0][10] = 5.34395599365;
   fMin_1[1][10] = 0.631489932537;
   fMax_1[1][10] = 5.80796384811;
   fMin_1[2][10] = 0.548147320747;
   fMax_1[2][10] = 5.80796384811;
   fMin_1[0][11] = 0.345456838608;
   fMax_1[0][11] = 4.68913269043;
   fMin_1[1][11] = 0.331118583679;
   fMax_1[1][11] = 4.59567117691;
   fMin_1[2][11] = 0.331118583679;
   fMax_1[2][11] = 4.68913269043;
   fMin_1[0][12] = 0.382231384516;
   fMax_1[0][12] = 3.09887003899;
   fMin_1[1][12] = 0.399987101555;
   fMax_1[1][12] = 3.09979128838;
   fMin_1[2][12] = 0.382231384516;
   fMax_1[2][12] = 3.09979128838;
   fMin_1[0][13] = 0.304761111736;
   fMax_1[0][13] = 5.78525400162;
   fMin_1[1][13] = 0.343616694212;
   fMax_1[1][13] = 5.83795309067;
   fMin_1[2][13] = 0.304761111736;
   fMax_1[2][13] = 5.83795309067;
   fMin_1[0][14] = 0.0245936494321;
   fMax_1[0][14] = 6.85796403885;
   fMin_1[1][14] = 0.0342578701675;
   fMax_1[1][14] = 7.59379291534;
   fMin_1[2][14] = 0.0245936494321;
   fMax_1[2][14] = 7.59379291534;
   fMin_1[0][15] = 0.07235570997;
   fMax_1[0][15] = 7.17004442215;
   fMin_1[1][15] = 0.0183821171522;
   fMax_1[1][15] = 6.23720550537;
   fMin_1[2][15] = 0.0183821171522;
   fMax_1[2][15] = 7.17004442215;
   fMin_1[0][16] = 0.000293850898743;
   fMax_1[0][16] = 6.25128030777;
   fMin_1[1][16] = 9.36985015869e-05;
   fMax_1[1][16] = 6.25079774857;
   fMin_1[2][16] = 9.36985015869e-05;
   fMax_1[2][16] = 6.25128030777;
   fMin_1[0][17] = 60.0013084412;
   fMax_1[0][17] = 159.993743896;
   fMin_1[1][17] = 60.0244789124;
   fMax_1[1][17] = 159.999816895;
   fMin_1[2][17] = 60.0013084412;
   fMax_1[2][17] = 159.999816895;
   fMin_1[0][18] = 104.987121582;
   fMax_1[0][18] = 3156.22827148;
   fMin_1[1][18] = 110.601150513;
   fMax_1[1][18] = 4475.03857422;
   fMin_1[2][18] = 104.987121582;
   fMax_1[2][18] = 4475.03857422;
   fMin_1[0][19] = 42.1632194519;
   fMax_1[0][19] = 3031.91503906;
   fMin_1[1][19] = 44.5250282288;
   fMax_1[1][19] = 3519.41210938;
   fMin_1[2][19] = 42.1632194519;
   fMax_1[2][19] = 3519.41210938;
   fMin_1[0][20] = 86.4190216064;
   fMax_1[0][20] = 2917.90478516;
   fMin_1[1][20] = 88.8523406982;
   fMax_1[1][20] = 4438.00146484;
   fMin_1[2][20] = 86.4190216064;
   fMax_1[2][20] = 4438.00146484;
   fMin_1[0][21] = 0.0299043245614;
   fMax_1[0][21] = 460.327148438;
   fMin_1[1][21] = 0.00475058425218;
   fMax_1[1][21] = 535.521972656;
   fMin_1[2][21] = 0.00475058425218;
   fMax_1[2][21] = 535.521972656;
   fMin_1[0][22] = 0.00143084453885;
   fMax_1[0][22] = 1058.67456055;
   fMin_1[1][22] = 0.0021944725886;
   fMax_1[1][22] = 1580.10388184;
   fMin_1[2][22] = 0.00143084453885;
   fMax_1[2][22] = 1580.10388184;
}

//_______________________________________________________________________
inline void ReadMLPTunedSigmoid::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 23;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesGet.push_back( 14);
   indicesGet.push_back( 15);
   indicesGet.push_back( 16);
   indicesGet.push_back( 17);
   indicesGet.push_back( 18);
   indicesGet.push_back( 19);
   indicesGet.push_back( 20);
   indicesGet.push_back( 21);
   indicesGet.push_back( 22);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);
   indicesPut.push_back( 14);
   indicesPut.push_back( 15);
   indicesPut.push_back( 16);
   indicesPut.push_back( 17);
   indicesPut.push_back( 18);
   indicesPut.push_back( 19);
   indicesPut.push_back( 20);
   indicesPut.push_back( 21);
   indicesPut.push_back( 22);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<23;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPTunedSigmoid::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPTunedSigmoid::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
