// Class: ReadMLPTuned
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPTuned
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : ineuteli
Date           : Sun Nov 29 23:22:18 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.11.2.el6.x86_64 #1 SMP Wed Mar 26 09:39:43 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/ineuteli/phase2/CMSSW_5_3_24/src/Delphes/plots
Training events: 20732
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
NCycles: "500" [Number of training cycles]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 23
Njets20                       Njets20                       Njets20                       Njets20                                                         'F'    [4,14]
Nbjets30                      Nbjets30                      Nbjets30                      Nbjets30                                                        'F'    [2,6]
jet1Pt                        jet1Pt                        jet1Pt                        jet1Pt                                                          'F'    [20.3211650848,1187.93493652]
jet2Pt                        jet2Pt                        jet2Pt                        jet2Pt                                                          'F'    [20.0031757355,699.98260498]
bjet1Pt                       bjet1Pt                       bjet1Pt                       bjet1Pt                                                         'F'    [31.4223308563,904.02545166]
bjet2Pt                       bjet2Pt                       bjet2Pt                       bjet2Pt                                                         'F'    [30.001663208,298.117797852]
leptonPt                      leptonPt                      leptonPt                      leptonPt                                                        'F'    [20.0059547424,480.95715332]
MET                           MET                           MET                           MET                                                             'F'    [20.003408432,625.883056641]
DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                                                      'F'    [0.267349809408,5.02747869492]
DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                                                      'F'    [0.410064458847,6.81951332092]
DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                                                      'F'    [0.548147320747,5.80796384811]
DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                                                      'F'    [0.331118583679,4.68913269043]
DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                                                      'F'    [0.382231384516,3.09979128838]
DeltaR_jj                     DeltaR_jj                     DeltaR_jj                     DeltaR_jj                                                       'F'    [0.304761111736,5.83795309067]
DeltaR_jjl                    DeltaR_jjl                    DeltaR_jjl                    DeltaR_jjl                                                      'F'    [0.0245936494321,7.59379291534]
DeltaR_jjb                    DeltaR_jjb                    DeltaR_jjb                    DeltaR_jjb                                                      'F'    [0.0183821171522,7.17004442215]
DeltaPhi_lMET                 DeltaPhi_lMET                 DeltaPhi_lMET                 DeltaPhi_lMET                                                   'F'    [9.36985015869e-05,6.25128030777]
M_bb_closest                  M_bb_closest                  M_bb_closest                  M_bb_closest                                                    'F'    [60.0013084412,159.999816895]
M_jjlnu                       M_jjlnu                       M_jjlnu                       M_jjlnu                                                         'F'    [104.987121582,4475.03857422]
M_jjb                         M_jjb                         M_jjb                         M_jjb                                                           'F'    [42.1632194519,3519.41210938]
M_blnu                        M_blnu                        M_blnu                        M_blnu                                                          'F'    [86.4190216064,4438.00146484]
MT_lnu                        MT_lnu                        MT_lnu                        MT_lnu                                                          'F'    [0.00475058425218,535.521972656]
MT_jjlnu                      MT_jjlnu                      MT_jjlnu                      MT_jjlnu                                                        'F'    [0.00143084453885,1580.10388184]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPTuned : public IClassifierReader {

 public:

   // constructor
   ReadMLPTuned( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPTuned" ),
        fNvars( 23 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Njets20", "Nbjets30", "jet1Pt", "jet2Pt", "bjet1Pt", "bjet2Pt", "leptonPt", "MET", "DeltaR_j1l", "DeltaR_j2l", "DeltaR_b1l", "DeltaR_b2l", "DeltaR_bb1", "DeltaR_jj", "DeltaR_jjl", "DeltaR_jjb", "DeltaPhi_lMET", "M_bb_closest", "M_jjlnu", "M_jjb", "M_blnu", "MT_lnu", "MT_jjlnu" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 0.99999988079071;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 0.99999988079071;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 0.99999988079071;
      fVmin[16] = -1;
      fVmax[16] = 0.99999988079071;
      fVmin[17] = -1;
      fVmax[17] = 1;
      fVmin[18] = -1;
      fVmax[18] = 1;
      fVmin[19] = -1;
      fVmax[19] = 1;
      fVmin[20] = -1;
      fVmax[20] = 1;
      fVmin[21] = -1;
      fVmax[21] = 1;
      fVmin[22] = -1;
      fVmax[22] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPTuned() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][23];
   double fMax_1[3][23];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[23];
   double fVmax[23];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[23];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[29][24];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][29];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPTuned::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 24; fWeights[0] = new double[24]; 
   fLayerSize[1] = 29; fWeights[1] = new double[29]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.362233085377457;
   fWeightMatrix0to1[1][0] = 0.80031851957866;
   fWeightMatrix0to1[2][0] = 1.26378681682066;
   fWeightMatrix0to1[3][0] = 1.11062716900421;
   fWeightMatrix0to1[4][0] = -1.87674927807842;
   fWeightMatrix0to1[5][0] = -0.738279426002076;
   fWeightMatrix0to1[6][0] = 0.34215160191416;
   fWeightMatrix0to1[7][0] = 2.05477161308731;
   fWeightMatrix0to1[8][0] = -1.16483241134385;
   fWeightMatrix0to1[9][0] = -0.579292126610916;
   fWeightMatrix0to1[10][0] = -1.45917884769535;
   fWeightMatrix0to1[11][0] = -0.472902508959247;
   fWeightMatrix0to1[12][0] = -0.174984107863004;
   fWeightMatrix0to1[13][0] = -0.35827005294139;
   fWeightMatrix0to1[14][0] = -0.270065585222833;
   fWeightMatrix0to1[15][0] = 0.547742563370048;
   fWeightMatrix0to1[16][0] = -0.0100599099299514;
   fWeightMatrix0to1[17][0] = 1.80681223332838;
   fWeightMatrix0to1[18][0] = 0.296348130156709;
   fWeightMatrix0to1[19][0] = 0.0960012988310143;
   fWeightMatrix0to1[20][0] = -0.941694889842615;
   fWeightMatrix0to1[21][0] = -0.453183736390057;
   fWeightMatrix0to1[22][0] = 0.846303974159834;
   fWeightMatrix0to1[23][0] = -0.112561966579628;
   fWeightMatrix0to1[24][0] = -1.2850089418728;
   fWeightMatrix0to1[25][0] = -0.333466051275974;
   fWeightMatrix0to1[26][0] = 1.09486868676857;
   fWeightMatrix0to1[27][0] = -0.734987605328865;
   fWeightMatrix0to1[0][1] = -1.19534695324191;
   fWeightMatrix0to1[1][1] = 0.0396428250630862;
   fWeightMatrix0to1[2][1] = 0.701997950128576;
   fWeightMatrix0to1[3][1] = 1.29497463913818;
   fWeightMatrix0to1[4][1] = -0.162929753107138;
   fWeightMatrix0to1[5][1] = -0.149210934840178;
   fWeightMatrix0to1[6][1] = 1.18013450445828;
   fWeightMatrix0to1[7][1] = -0.26742777443062;
   fWeightMatrix0to1[8][1] = -0.847181650737728;
   fWeightMatrix0to1[9][1] = 1.59828995263812;
   fWeightMatrix0to1[10][1] = -1.46259927938028;
   fWeightMatrix0to1[11][1] = 0.922331353471408;
   fWeightMatrix0to1[12][1] = 0.935529607471533;
   fWeightMatrix0to1[13][1] = 0.636175416733607;
   fWeightMatrix0to1[14][1] = 1.93855240731216;
   fWeightMatrix0to1[15][1] = 2.31799912618319;
   fWeightMatrix0to1[16][1] = -0.31158538116389;
   fWeightMatrix0to1[17][1] = -1.81466425787606;
   fWeightMatrix0to1[18][1] = 0.955015527474268;
   fWeightMatrix0to1[19][1] = 0.21877169633196;
   fWeightMatrix0to1[20][1] = 0.844198469325894;
   fWeightMatrix0to1[21][1] = 0.542715502795354;
   fWeightMatrix0to1[22][1] = 1.66259017068622;
   fWeightMatrix0to1[23][1] = 0.435855478310529;
   fWeightMatrix0to1[24][1] = -1.50008570120201;
   fWeightMatrix0to1[25][1] = 1.00946793258431;
   fWeightMatrix0to1[26][1] = -1.0868558444793;
   fWeightMatrix0to1[27][1] = -1.83640396618337;
   fWeightMatrix0to1[0][2] = -2.66154257008238;
   fWeightMatrix0to1[1][2] = -1.64594279879379;
   fWeightMatrix0to1[2][2] = 1.47829674622946;
   fWeightMatrix0to1[3][2] = 0.269641825149498;
   fWeightMatrix0to1[4][2] = -1.50642854462496;
   fWeightMatrix0to1[5][2] = 0.857848066599957;
   fWeightMatrix0to1[6][2] = -0.518273588169125;
   fWeightMatrix0to1[7][2] = 0.736663443762476;
   fWeightMatrix0to1[8][2] = 1.90026014333933;
   fWeightMatrix0to1[9][2] = -0.183503110002827;
   fWeightMatrix0to1[10][2] = 0.128657240878521;
   fWeightMatrix0to1[11][2] = -1.01475952505288;
   fWeightMatrix0to1[12][2] = 0.0173004229090589;
   fWeightMatrix0to1[13][2] = -0.772057092149787;
   fWeightMatrix0to1[14][2] = -0.281733818667328;
   fWeightMatrix0to1[15][2] = -0.967980154723412;
   fWeightMatrix0to1[16][2] = 1.40192008008556;
   fWeightMatrix0to1[17][2] = 0.885559111498386;
   fWeightMatrix0to1[18][2] = 0.676035318662795;
   fWeightMatrix0to1[19][2] = 0.681715812731979;
   fWeightMatrix0to1[20][2] = -2.42701621923902;
   fWeightMatrix0to1[21][2] = -2.06870861503115;
   fWeightMatrix0to1[22][2] = 0.922577995482762;
   fWeightMatrix0to1[23][2] = 0.0864091819750349;
   fWeightMatrix0to1[24][2] = 1.97232804564196;
   fWeightMatrix0to1[25][2] = 0.726983928544139;
   fWeightMatrix0to1[26][2] = 1.17675926298606;
   fWeightMatrix0to1[27][2] = -1.35614553299022;
   fWeightMatrix0to1[0][3] = -2.20504618469262;
   fWeightMatrix0to1[1][3] = 0.659052740640811;
   fWeightMatrix0to1[2][3] = 1.36705763376414;
   fWeightMatrix0to1[3][3] = -1.60776179626969;
   fWeightMatrix0to1[4][3] = -1.27097292049071;
   fWeightMatrix0to1[5][3] = -1.10538093211786;
   fWeightMatrix0to1[6][3] = 0.607725350772912;
   fWeightMatrix0to1[7][3] = -0.0957561072971417;
   fWeightMatrix0to1[8][3] = 1.72840316858935;
   fWeightMatrix0to1[9][3] = -1.44502671298611;
   fWeightMatrix0to1[10][3] = -0.960045427509248;
   fWeightMatrix0to1[11][3] = 1.85338726160535;
   fWeightMatrix0to1[12][3] = -0.957040111829922;
   fWeightMatrix0to1[13][3] = -1.54974352738955;
   fWeightMatrix0to1[14][3] = -1.0106855003088;
   fWeightMatrix0to1[15][3] = 0.207660193229047;
   fWeightMatrix0to1[16][3] = -1.38486319087876;
   fWeightMatrix0to1[17][3] = -1.95207063708086;
   fWeightMatrix0to1[18][3] = 0.760472872507392;
   fWeightMatrix0to1[19][3] = 1.55598369816722;
   fWeightMatrix0to1[20][3] = -1.30975136610238;
   fWeightMatrix0to1[21][3] = 1.57647641484815;
   fWeightMatrix0to1[22][3] = -0.83680001610465;
   fWeightMatrix0to1[23][3] = -0.2068494278133;
   fWeightMatrix0to1[24][3] = -0.072489340603708;
   fWeightMatrix0to1[25][3] = 0.203795274462602;
   fWeightMatrix0to1[26][3] = -1.05020072176541;
   fWeightMatrix0to1[27][3] = -1.60202782053991;
   fWeightMatrix0to1[0][4] = 2.71808462009328;
   fWeightMatrix0to1[1][4] = -0.932492100950175;
   fWeightMatrix0to1[2][4] = -1.44049534753685;
   fWeightMatrix0to1[3][4] = 1.4013724732128;
   fWeightMatrix0to1[4][4] = 0.266010083239289;
   fWeightMatrix0to1[5][4] = -0.699035367731391;
   fWeightMatrix0to1[6][4] = -0.047329799407904;
   fWeightMatrix0to1[7][4] = -1.05598468928305;
   fWeightMatrix0to1[8][4] = -1.31922219367737;
   fWeightMatrix0to1[9][4] = 0.497288472071387;
   fWeightMatrix0to1[10][4] = -0.774779818710475;
   fWeightMatrix0to1[11][4] = 1.56306211117664;
   fWeightMatrix0to1[12][4] = -0.169787382739208;
   fWeightMatrix0to1[13][4] = -0.653846240688955;
   fWeightMatrix0to1[14][4] = -0.110514137757737;
   fWeightMatrix0to1[15][4] = 1.11918844076898;
   fWeightMatrix0to1[16][4] = -1.50423711400439;
   fWeightMatrix0to1[17][4] = 0.877157647573228;
   fWeightMatrix0to1[18][4] = -0.696509231157345;
   fWeightMatrix0to1[19][4] = -0.175765516534824;
   fWeightMatrix0to1[20][4] = 0.194482151424975;
   fWeightMatrix0to1[21][4] = -1.64712136850519;
   fWeightMatrix0to1[22][4] = 0.0451219829642606;
   fWeightMatrix0to1[23][4] = 0.294958441306307;
   fWeightMatrix0to1[24][4] = 1.80803228115714;
   fWeightMatrix0to1[25][4] = -1.8894165168893;
   fWeightMatrix0to1[26][4] = 0.43747879609333;
   fWeightMatrix0to1[27][4] = 4.26152835654745;
   fWeightMatrix0to1[0][5] = 1.48097135245192;
   fWeightMatrix0to1[1][5] = 0.322801109277639;
   fWeightMatrix0to1[2][5] = -1.57422076330633;
   fWeightMatrix0to1[3][5] = -0.523795042304406;
   fWeightMatrix0to1[4][5] = -1.72874408377158;
   fWeightMatrix0to1[5][5] = 1.63403583871459;
   fWeightMatrix0to1[6][5] = 0.415068335447177;
   fWeightMatrix0to1[7][5] = -0.479046324313114;
   fWeightMatrix0to1[8][5] = -0.394872185394145;
   fWeightMatrix0to1[9][5] = 0.165912108287222;
   fWeightMatrix0to1[10][5] = -1.43916648761352;
   fWeightMatrix0to1[11][5] = 0.685846443863602;
   fWeightMatrix0to1[12][5] = 0.635503738536989;
   fWeightMatrix0to1[13][5] = -0.79600442516212;
   fWeightMatrix0to1[14][5] = -0.380893585752642;
   fWeightMatrix0to1[15][5] = 0.429223503636507;
   fWeightMatrix0to1[16][5] = 1.07520702655198;
   fWeightMatrix0to1[17][5] = 0.583941691491975;
   fWeightMatrix0to1[18][5] = 0.633881532849461;
   fWeightMatrix0to1[19][5] = -0.867446943168809;
   fWeightMatrix0to1[20][5] = 1.56501727543302;
   fWeightMatrix0to1[21][5] = 0.551474403949326;
   fWeightMatrix0to1[22][5] = 0.486391923456713;
   fWeightMatrix0to1[23][5] = 0.242872067003519;
   fWeightMatrix0to1[24][5] = 0.99319655376332;
   fWeightMatrix0to1[25][5] = -0.936936603999229;
   fWeightMatrix0to1[26][5] = -0.619199972488051;
   fWeightMatrix0to1[27][5] = 0.960574222683842;
   fWeightMatrix0to1[0][6] = -0.446965920928606;
   fWeightMatrix0to1[1][6] = -0.114458173284932;
   fWeightMatrix0to1[2][6] = 1.20420332062156;
   fWeightMatrix0to1[3][6] = 0.608191023379196;
   fWeightMatrix0to1[4][6] = -0.311198740725686;
   fWeightMatrix0to1[5][6] = 1.78469099388355;
   fWeightMatrix0to1[6][6] = 1.30788922673558;
   fWeightMatrix0to1[7][6] = -1.88652825564606;
   fWeightMatrix0to1[8][6] = 0.749486887829821;
   fWeightMatrix0to1[9][6] = 0.366539626414506;
   fWeightMatrix0to1[10][6] = 0.170062649213187;
   fWeightMatrix0to1[11][6] = -2.3610923148326;
   fWeightMatrix0to1[12][6] = -2.00341708450968;
   fWeightMatrix0to1[13][6] = 0.449618486760274;
   fWeightMatrix0to1[14][6] = 2.10578417255611;
   fWeightMatrix0to1[15][6] = -1.35314692331663;
   fWeightMatrix0to1[16][6] = 0.00861413694497026;
   fWeightMatrix0to1[17][6] = -0.560368590232818;
   fWeightMatrix0to1[18][6] = -0.561538724519987;
   fWeightMatrix0to1[19][6] = 2.16078971595483;
   fWeightMatrix0to1[20][6] = -0.606673727298675;
   fWeightMatrix0to1[21][6] = -0.590117759705415;
   fWeightMatrix0to1[22][6] = -1.0040962132461;
   fWeightMatrix0to1[23][6] = 1.65389439518279;
   fWeightMatrix0to1[24][6] = 1.68077738123104;
   fWeightMatrix0to1[25][6] = 1.09018008528616;
   fWeightMatrix0to1[26][6] = 0.443439668101942;
   fWeightMatrix0to1[27][6] = 0.127045521122419;
   fWeightMatrix0to1[0][7] = -1.04568448239599;
   fWeightMatrix0to1[1][7] = -0.216449992442079;
   fWeightMatrix0to1[2][7] = 0.488221993957864;
   fWeightMatrix0to1[3][7] = -1.67044034930624;
   fWeightMatrix0to1[4][7] = -0.881763059678074;
   fWeightMatrix0to1[5][7] = 0.512022054761871;
   fWeightMatrix0to1[6][7] = 0.748255102455273;
   fWeightMatrix0to1[7][7] = -1.93216353223262;
   fWeightMatrix0to1[8][7] = 1.48031352902544;
   fWeightMatrix0to1[9][7] = 0.866833328141782;
   fWeightMatrix0to1[10][7] = -0.787621685824274;
   fWeightMatrix0to1[11][7] = -0.213080913969466;
   fWeightMatrix0to1[12][7] = 0.820360353707246;
   fWeightMatrix0to1[13][7] = 0.284451239618262;
   fWeightMatrix0to1[14][7] = 0.733969022250019;
   fWeightMatrix0to1[15][7] = 0.898491433148862;
   fWeightMatrix0to1[16][7] = -1.46007326785994;
   fWeightMatrix0to1[17][7] = -0.956291742066279;
   fWeightMatrix0to1[18][7] = 1.2970223773523;
   fWeightMatrix0to1[19][7] = 0.925432825204545;
   fWeightMatrix0to1[20][7] = 0.641740353601964;
   fWeightMatrix0to1[21][7] = 0.570897153085087;
   fWeightMatrix0to1[22][7] = 2.16394027962863;
   fWeightMatrix0to1[23][7] = -0.98146036426884;
   fWeightMatrix0to1[24][7] = -1.40189206774458;
   fWeightMatrix0to1[25][7] = -0.493050231095669;
   fWeightMatrix0to1[26][7] = -0.840639937595547;
   fWeightMatrix0to1[27][7] = -0.541049989836036;
   fWeightMatrix0to1[0][8] = 0.295160382136585;
   fWeightMatrix0to1[1][8] = 0.0972286611724335;
   fWeightMatrix0to1[2][8] = 0.876273249366013;
   fWeightMatrix0to1[3][8] = -0.532160853841224;
   fWeightMatrix0to1[4][8] = -1.70218535041434;
   fWeightMatrix0to1[5][8] = -0.762638341722969;
   fWeightMatrix0to1[6][8] = 0.829719431442005;
   fWeightMatrix0to1[7][8] = -0.0132619312822399;
   fWeightMatrix0to1[8][8] = 1.13247407209422;
   fWeightMatrix0to1[9][8] = -0.776516771466581;
   fWeightMatrix0to1[10][8] = 1.27349387241755;
   fWeightMatrix0to1[11][8] = -2.45933734837252;
   fWeightMatrix0to1[12][8] = 3.54244715370983;
   fWeightMatrix0to1[13][8] = 0.463753998985093;
   fWeightMatrix0to1[14][8] = -1.40103079806829;
   fWeightMatrix0to1[15][8] = -1.19031673929771;
   fWeightMatrix0to1[16][8] = -1.39058412315153;
   fWeightMatrix0to1[17][8] = -0.309775426231387;
   fWeightMatrix0to1[18][8] = -2.5824086027432;
   fWeightMatrix0to1[19][8] = 0.407000923955753;
   fWeightMatrix0to1[20][8] = -1.26135023747262;
   fWeightMatrix0to1[21][8] = 0.295222256657577;
   fWeightMatrix0to1[22][8] = -1.01009123196796;
   fWeightMatrix0to1[23][8] = -1.17456303657911;
   fWeightMatrix0to1[24][8] = 1.42929531114117;
   fWeightMatrix0to1[25][8] = -1.11496017942956;
   fWeightMatrix0to1[26][8] = 0.552576283662569;
   fWeightMatrix0to1[27][8] = -1.6357725034088;
   fWeightMatrix0to1[0][9] = 0.395854449887935;
   fWeightMatrix0to1[1][9] = 0.465680592098424;
   fWeightMatrix0to1[2][9] = 1.38972494977659;
   fWeightMatrix0to1[3][9] = -0.939153976874042;
   fWeightMatrix0to1[4][9] = -1.56667387214931;
   fWeightMatrix0to1[5][9] = -1.03220077411469;
   fWeightMatrix0to1[6][9] = -0.240629046276846;
   fWeightMatrix0to1[7][9] = -1.72360256220776;
   fWeightMatrix0to1[8][9] = 0.363176739382319;
   fWeightMatrix0to1[9][9] = 0.190301576707056;
   fWeightMatrix0to1[10][9] = 1.54820681212861;
   fWeightMatrix0to1[11][9] = -0.500155670452517;
   fWeightMatrix0to1[12][9] = -0.506628601044827;
   fWeightMatrix0to1[13][9] = -0.241535618657641;
   fWeightMatrix0to1[14][9] = -1.70350364536067;
   fWeightMatrix0to1[15][9] = 0.563130251005279;
   fWeightMatrix0to1[16][9] = 1.72016816372454;
   fWeightMatrix0to1[17][9] = -0.896174381596773;
   fWeightMatrix0to1[18][9] = -1.92779620737123;
   fWeightMatrix0to1[19][9] = -0.208228990037621;
   fWeightMatrix0to1[20][9] = 1.28667756064312;
   fWeightMatrix0to1[21][9] = 0.383879272705889;
   fWeightMatrix0to1[22][9] = -0.45895663525141;
   fWeightMatrix0to1[23][9] = -0.463160208693436;
   fWeightMatrix0to1[24][9] = 1.56432750042204;
   fWeightMatrix0to1[25][9] = 0.89254774132695;
   fWeightMatrix0to1[26][9] = 1.31851580030126;
   fWeightMatrix0to1[27][9] = -0.874328459571963;
   fWeightMatrix0to1[0][10] = 0.131164844912549;
   fWeightMatrix0to1[1][10] = -1.02709076577474;
   fWeightMatrix0to1[2][10] = -1.10088570584916;
   fWeightMatrix0to1[3][10] = -0.800470317654366;
   fWeightMatrix0to1[4][10] = -1.77770414166464;
   fWeightMatrix0to1[5][10] = -1.27982413407911;
   fWeightMatrix0to1[6][10] = -0.923459950639927;
   fWeightMatrix0to1[7][10] = 1.78115868038435;
   fWeightMatrix0to1[8][10] = -1.32367996835081;
   fWeightMatrix0to1[9][10] = 2.03458053709033;
   fWeightMatrix0to1[10][10] = -1.82539983628191;
   fWeightMatrix0to1[11][10] = 0.28384181531036;
   fWeightMatrix0to1[12][10] = -1.06388082303157;
   fWeightMatrix0to1[13][10] = -0.128605910732078;
   fWeightMatrix0to1[14][10] = 0.935345956369965;
   fWeightMatrix0to1[15][10] = -0.828406464359248;
   fWeightMatrix0to1[16][10] = -0.0116058906476847;
   fWeightMatrix0to1[17][10] = 0.521857031382835;
   fWeightMatrix0to1[18][10] = -0.664031376118447;
   fWeightMatrix0to1[19][10] = -0.796360001416371;
   fWeightMatrix0to1[20][10] = -1.8548664204502;
   fWeightMatrix0to1[21][10] = -0.805452217826818;
   fWeightMatrix0to1[22][10] = 1.8671230312222;
   fWeightMatrix0to1[23][10] = -0.360644059181023;
   fWeightMatrix0to1[24][10] = 0.309144338482673;
   fWeightMatrix0to1[25][10] = -0.938137032070365;
   fWeightMatrix0to1[26][10] = -1.64508643330291;
   fWeightMatrix0to1[27][10] = 0.0480381379566518;
   fWeightMatrix0to1[0][11] = 0.521751423889124;
   fWeightMatrix0to1[1][11] = -1.8651600258574;
   fWeightMatrix0to1[2][11] = 1.38687285226024;
   fWeightMatrix0to1[3][11] = -1.4136145444558;
   fWeightMatrix0to1[4][11] = -1.21789650954222;
   fWeightMatrix0to1[5][11] = 1.32236703517928;
   fWeightMatrix0to1[6][11] = -0.573586663812907;
   fWeightMatrix0to1[7][11] = -0.515906584158991;
   fWeightMatrix0to1[8][11] = 2.08748108573126;
   fWeightMatrix0to1[9][11] = -1.54600764228644;
   fWeightMatrix0to1[10][11] = 0.990634125445166;
   fWeightMatrix0to1[11][11] = -0.243214471985293;
   fWeightMatrix0to1[12][11] = 0.252371878652304;
   fWeightMatrix0to1[13][11] = -0.901691445898291;
   fWeightMatrix0to1[14][11] = -0.0954563056475659;
   fWeightMatrix0to1[15][11] = -0.980373873210362;
   fWeightMatrix0to1[16][11] = 0.319371470387206;
   fWeightMatrix0to1[17][11] = 1.9743116591666;
   fWeightMatrix0to1[18][11] = 0.920845832261665;
   fWeightMatrix0to1[19][11] = 1.58902551606714;
   fWeightMatrix0to1[20][11] = -1.4737000004825;
   fWeightMatrix0to1[21][11] = 0.534484088063241;
   fWeightMatrix0to1[22][11] = -1.9521342007657;
   fWeightMatrix0to1[23][11] = 1.26476083634687;
   fWeightMatrix0to1[24][11] = -1.73377569703719;
   fWeightMatrix0to1[25][11] = -1.99312565948135;
   fWeightMatrix0to1[26][11] = -0.470059611410584;
   fWeightMatrix0to1[27][11] = 1.27791742253874;
   fWeightMatrix0to1[0][12] = 0.390106016949385;
   fWeightMatrix0to1[1][12] = 0.680879910917136;
   fWeightMatrix0to1[2][12] = 0.192221990343138;
   fWeightMatrix0to1[3][12] = -0.862244944589533;
   fWeightMatrix0to1[4][12] = -0.582656426882241;
   fWeightMatrix0to1[5][12] = 0.38100392492054;
   fWeightMatrix0to1[6][12] = 1.71373413227424;
   fWeightMatrix0to1[7][12] = -1.64730969541768;
   fWeightMatrix0to1[8][12] = 0.472417359466128;
   fWeightMatrix0to1[9][12] = -1.02170066856741;
   fWeightMatrix0to1[10][12] = -0.536792886288548;
   fWeightMatrix0to1[11][12] = 0.0873131919500864;
   fWeightMatrix0to1[12][12] = -0.549753178954371;
   fWeightMatrix0to1[13][12] = -0.184478845113621;
   fWeightMatrix0to1[14][12] = 1.05879073037211;
   fWeightMatrix0to1[15][12] = 1.6511318540399;
   fWeightMatrix0to1[16][12] = 0.83335992893074;
   fWeightMatrix0to1[17][12] = -0.0272237550443718;
   fWeightMatrix0to1[18][12] = 0.752045162146344;
   fWeightMatrix0to1[19][12] = -1.99755204042246;
   fWeightMatrix0to1[20][12] = -0.839662540352824;
   fWeightMatrix0to1[21][12] = 0.874929985117866;
   fWeightMatrix0to1[22][12] = -0.469627816296062;
   fWeightMatrix0to1[23][12] = -0.544514445517107;
   fWeightMatrix0to1[24][12] = 0.715542473696191;
   fWeightMatrix0to1[25][12] = -1.40856483061251;
   fWeightMatrix0to1[26][12] = -0.802224094124938;
   fWeightMatrix0to1[27][12] = -1.14171822871047;
   fWeightMatrix0to1[0][13] = -0.200112722460206;
   fWeightMatrix0to1[1][13] = -0.191110086074771;
   fWeightMatrix0to1[2][13] = -1.66243924572216;
   fWeightMatrix0to1[3][13] = -0.485959494524466;
   fWeightMatrix0to1[4][13] = -0.880657156135065;
   fWeightMatrix0to1[5][13] = -1.12737283917656;
   fWeightMatrix0to1[6][13] = 0.255234203506353;
   fWeightMatrix0to1[7][13] = -1.39611576807773;
   fWeightMatrix0to1[8][13] = -1.30541292701248;
   fWeightMatrix0to1[9][13] = 0.830655525130843;
   fWeightMatrix0to1[10][13] = 0.468421884892295;
   fWeightMatrix0to1[11][13] = 0.509777499133732;
   fWeightMatrix0to1[12][13] = -0.654415549873993;
   fWeightMatrix0to1[13][13] = 0.455089239307085;
   fWeightMatrix0to1[14][13] = 1.64638279695544;
   fWeightMatrix0to1[15][13] = -0.38552508010719;
   fWeightMatrix0to1[16][13] = -0.796354539026558;
   fWeightMatrix0to1[17][13] = -0.661481946435832;
   fWeightMatrix0to1[18][13] = -0.655819702165041;
   fWeightMatrix0to1[19][13] = 0.486841524788043;
   fWeightMatrix0to1[20][13] = -0.139639138583668;
   fWeightMatrix0to1[21][13] = -0.311299268448576;
   fWeightMatrix0to1[22][13] = 1.03969080857197;
   fWeightMatrix0to1[23][13] = 0.189269024598817;
   fWeightMatrix0to1[24][13] = 1.61262643438499;
   fWeightMatrix0to1[25][13] = -1.06736833819417;
   fWeightMatrix0to1[26][13] = 1.1835433239844;
   fWeightMatrix0to1[27][13] = 0.0159699492958591;
   fWeightMatrix0to1[0][14] = -1.14438432469679;
   fWeightMatrix0to1[1][14] = 0.461712942649897;
   fWeightMatrix0to1[2][14] = -1.39120566215972;
   fWeightMatrix0to1[3][14] = 0.84132868770101;
   fWeightMatrix0to1[4][14] = 0.274476131011937;
   fWeightMatrix0to1[5][14] = 1.03323093185894;
   fWeightMatrix0to1[6][14] = -0.803142702445894;
   fWeightMatrix0to1[7][14] = -0.432999855872923;
   fWeightMatrix0to1[8][14] = 1.67467304863264;
   fWeightMatrix0to1[9][14] = 1.4869658661872;
   fWeightMatrix0to1[10][14] = 0.115471938194362;
   fWeightMatrix0to1[11][14] = -1.31003246313153;
   fWeightMatrix0to1[12][14] = -0.0992051558987048;
   fWeightMatrix0to1[13][14] = -0.85343740192623;
   fWeightMatrix0to1[14][14] = 0.770561824266201;
   fWeightMatrix0to1[15][14] = 0.425411735899935;
   fWeightMatrix0to1[16][14] = -0.179824512227117;
   fWeightMatrix0to1[17][14] = -0.856573254908478;
   fWeightMatrix0to1[18][14] = -0.582006145540175;
   fWeightMatrix0to1[19][14] = -1.30781972960257;
   fWeightMatrix0to1[20][14] = 0.431189407911354;
   fWeightMatrix0to1[21][14] = -1.17490713184331;
   fWeightMatrix0to1[22][14] = 0.290149988910431;
   fWeightMatrix0to1[23][14] = -0.219355309611604;
   fWeightMatrix0to1[24][14] = 1.64429936218585;
   fWeightMatrix0to1[25][14] = 1.32106743194409;
   fWeightMatrix0to1[26][14] = 1.62060720115278;
   fWeightMatrix0to1[27][14] = 0.217976220865581;
   fWeightMatrix0to1[0][15] = 0.153321560527696;
   fWeightMatrix0to1[1][15] = 0.169190791584217;
   fWeightMatrix0to1[2][15] = 1.84524447663129;
   fWeightMatrix0to1[3][15] = -1.99831446752099;
   fWeightMatrix0to1[4][15] = -1.31454486158141;
   fWeightMatrix0to1[5][15] = -0.597560118237808;
   fWeightMatrix0to1[6][15] = 0.261976382475628;
   fWeightMatrix0to1[7][15] = -1.74248456552759;
   fWeightMatrix0to1[8][15] = -1.6783002744456;
   fWeightMatrix0to1[9][15] = 0.581039540335755;
   fWeightMatrix0to1[10][15] = -0.0644959311621314;
   fWeightMatrix0to1[11][15] = -1.60852647262072;
   fWeightMatrix0to1[12][15] = -0.0111762517168359;
   fWeightMatrix0to1[13][15] = -0.269853943804091;
   fWeightMatrix0to1[14][15] = 2.14196383163343;
   fWeightMatrix0to1[15][15] = 1.09297776002364;
   fWeightMatrix0to1[16][15] = 1.26409812905633;
   fWeightMatrix0to1[17][15] = -0.790829187987141;
   fWeightMatrix0to1[18][15] = -0.361684394053384;
   fWeightMatrix0to1[19][15] = 0.81256792892167;
   fWeightMatrix0to1[20][15] = -1.27608190665822;
   fWeightMatrix0to1[21][15] = -1.63020665918201;
   fWeightMatrix0to1[22][15] = -0.639313450669995;
   fWeightMatrix0to1[23][15] = 1.0071213558923;
   fWeightMatrix0to1[24][15] = -1.46599718851306;
   fWeightMatrix0to1[25][15] = 1.37450796056853;
   fWeightMatrix0to1[26][15] = 0.560391742509115;
   fWeightMatrix0to1[27][15] = 0.125628896470481;
   fWeightMatrix0to1[0][16] = 0.274923312589795;
   fWeightMatrix0to1[1][16] = -0.363566976975337;
   fWeightMatrix0to1[2][16] = 1.73373510870303;
   fWeightMatrix0to1[3][16] = -1.23149201679423;
   fWeightMatrix0to1[4][16] = 0.684172490292767;
   fWeightMatrix0to1[5][16] = 0.619179374708083;
   fWeightMatrix0to1[6][16] = 0.106678815861865;
   fWeightMatrix0to1[7][16] = -1.04489877317575;
   fWeightMatrix0to1[8][16] = 0.803335762360911;
   fWeightMatrix0to1[9][16] = -0.582307527468875;
   fWeightMatrix0to1[10][16] = 1.44954960960822;
   fWeightMatrix0to1[11][16] = 1.61644680726518;
   fWeightMatrix0to1[12][16] = 0.120586109774824;
   fWeightMatrix0to1[13][16] = 0.114529843832058;
   fWeightMatrix0to1[14][16] = 0.122666035301742;
   fWeightMatrix0to1[15][16] = -0.273060366306222;
   fWeightMatrix0to1[16][16] = 1.07323730425673;
   fWeightMatrix0to1[17][16] = 0.227401921870936;
   fWeightMatrix0to1[18][16] = 0.013959234638026;
   fWeightMatrix0to1[19][16] = 0.183332766342849;
   fWeightMatrix0to1[20][16] = 0.19910417222671;
   fWeightMatrix0to1[21][16] = 0.361671893594427;
   fWeightMatrix0to1[22][16] = 0.607186539467955;
   fWeightMatrix0to1[23][16] = -0.165562314918066;
   fWeightMatrix0to1[24][16] = -1.63153018660879;
   fWeightMatrix0to1[25][16] = 1.77764143960604;
   fWeightMatrix0to1[26][16] = -0.0461392752051281;
   fWeightMatrix0to1[27][16] = 0.0057614901110752;
   fWeightMatrix0to1[0][17] = -0.168998088459429;
   fWeightMatrix0to1[1][17] = -2.53174262829518;
   fWeightMatrix0to1[2][17] = 1.32035458904333;
   fWeightMatrix0to1[3][17] = 1.04833473782626;
   fWeightMatrix0to1[4][17] = -0.671927827184184;
   fWeightMatrix0to1[5][17] = -0.356430004995164;
   fWeightMatrix0to1[6][17] = 2.64868717372818;
   fWeightMatrix0to1[7][17] = 1.27518032401728;
   fWeightMatrix0to1[8][17] = -0.131883349011796;
   fWeightMatrix0to1[9][17] = 0.23419587186056;
   fWeightMatrix0to1[10][17] = -1.56197752774988;
   fWeightMatrix0to1[11][17] = -0.545913959132472;
   fWeightMatrix0to1[12][17] = 0.435245370607471;
   fWeightMatrix0to1[13][17] = 0.0216685893371907;
   fWeightMatrix0to1[14][17] = 0.193069809019215;
   fWeightMatrix0to1[15][17] = -0.881237003034047;
   fWeightMatrix0to1[16][17] = -1.55532280472776;
   fWeightMatrix0to1[17][17] = -1.95995340278056;
   fWeightMatrix0to1[18][17] = -0.561418646768642;
   fWeightMatrix0to1[19][17] = -0.83371191515918;
   fWeightMatrix0to1[20][17] = 0.340310701358249;
   fWeightMatrix0to1[21][17] = -0.0193004387564604;
   fWeightMatrix0to1[22][17] = 1.38431986198081;
   fWeightMatrix0to1[23][17] = -0.0770168361487848;
   fWeightMatrix0to1[24][17] = -1.93834138695224;
   fWeightMatrix0to1[25][17] = 1.56566451915132;
   fWeightMatrix0to1[26][17] = 2.10425458906211;
   fWeightMatrix0to1[27][17] = 0.145423006111031;
   fWeightMatrix0to1[0][18] = -0.969754447174395;
   fWeightMatrix0to1[1][18] = -0.299477295565746;
   fWeightMatrix0to1[2][18] = 1.77697786493182;
   fWeightMatrix0to1[3][18] = -1.82193620513401;
   fWeightMatrix0to1[4][18] = 0.463498806911708;
   fWeightMatrix0to1[5][18] = -0.894192780337698;
   fWeightMatrix0to1[6][18] = 0.534687000492051;
   fWeightMatrix0to1[7][18] = -1.00818063979514;
   fWeightMatrix0to1[8][18] = 0.320142824183917;
   fWeightMatrix0to1[9][18] = -0.135725326855649;
   fWeightMatrix0to1[10][18] = 0.261064079286351;
   fWeightMatrix0to1[11][18] = -0.601844793452003;
   fWeightMatrix0to1[12][18] = -0.28510644703999;
   fWeightMatrix0to1[13][18] = 0.478836724487703;
   fWeightMatrix0to1[14][18] = 0.736347238899654;
   fWeightMatrix0to1[15][18] = 0.837086131024758;
   fWeightMatrix0to1[16][18] = 1.8209208316495;
   fWeightMatrix0to1[17][18] = -1.52447627946882;
   fWeightMatrix0to1[18][18] = 0.927019838237881;
   fWeightMatrix0to1[19][18] = -1.61008760562937;
   fWeightMatrix0to1[20][18] = 0.532191234670879;
   fWeightMatrix0to1[21][18] = 1.28592351638396;
   fWeightMatrix0to1[22][18] = 0.751371357271133;
   fWeightMatrix0to1[23][18] = 2.1161313166874;
   fWeightMatrix0to1[24][18] = 1.43049220775795;
   fWeightMatrix0to1[25][18] = -1.67435242667594;
   fWeightMatrix0to1[26][18] = -0.122609561749139;
   fWeightMatrix0to1[27][18] = -0.859327844263213;
   fWeightMatrix0to1[0][19] = 1.3309941232999;
   fWeightMatrix0to1[1][19] = -0.678660257623201;
   fWeightMatrix0to1[2][19] = -0.167386803683747;
   fWeightMatrix0to1[3][19] = -0.982544767149003;
   fWeightMatrix0to1[4][19] = -0.382507078731558;
   fWeightMatrix0to1[5][19] = -0.923876192808803;
   fWeightMatrix0to1[6][19] = -1.16799414077431;
   fWeightMatrix0to1[7][19] = -1.88151479827281;
   fWeightMatrix0to1[8][19] = -0.316049559459561;
   fWeightMatrix0to1[9][19] = 0.252884860264658;
   fWeightMatrix0to1[10][19] = -0.858292750242863;
   fWeightMatrix0to1[11][19] = -1.31008193028444;
   fWeightMatrix0to1[12][19] = -0.555455726129308;
   fWeightMatrix0to1[13][19] = 0.029581283045384;
   fWeightMatrix0to1[14][19] = 0.215953546871609;
   fWeightMatrix0to1[15][19] = -0.9564485920118;
   fWeightMatrix0to1[16][19] = 2.32453094563628;
   fWeightMatrix0to1[17][19] = -0.379071396327932;
   fWeightMatrix0to1[18][19] = 1.32370245780872;
   fWeightMatrix0to1[19][19] = 0.88052563629948;
   fWeightMatrix0to1[20][19] = -1.39007895553444;
   fWeightMatrix0to1[21][19] = -1.33930609592947;
   fWeightMatrix0to1[22][19] = -0.317700498666555;
   fWeightMatrix0to1[23][19] = -1.99838584194907;
   fWeightMatrix0to1[24][19] = -0.633373929996391;
   fWeightMatrix0to1[25][19] = -0.746548971593452;
   fWeightMatrix0to1[26][19] = 0.809210535890888;
   fWeightMatrix0to1[27][19] = 2.30915174555125;
   fWeightMatrix0to1[0][20] = 1.85981909161268;
   fWeightMatrix0to1[1][20] = 1.78851243762341;
   fWeightMatrix0to1[2][20] = 1.40068957105344;
   fWeightMatrix0to1[3][20] = 0.648728422537552;
   fWeightMatrix0to1[4][20] = 0.569925930371286;
   fWeightMatrix0to1[5][20] = 0.325170500545931;
   fWeightMatrix0to1[6][20] = -1.48868762798413;
   fWeightMatrix0to1[7][20] = -1.82149299068538;
   fWeightMatrix0to1[8][20] = -0.563485139876115;
   fWeightMatrix0to1[9][20] = -0.49176458896049;
   fWeightMatrix0to1[10][20] = 1.03800291063619;
   fWeightMatrix0to1[11][20] = -0.203245693617096;
   fWeightMatrix0to1[12][20] = -0.187794453873817;
   fWeightMatrix0to1[13][20] = 0.967861565962656;
   fWeightMatrix0to1[14][20] = 1.47931588372571;
   fWeightMatrix0to1[15][20] = -0.855963328506668;
   fWeightMatrix0to1[16][20] = 0.692872560976058;
   fWeightMatrix0to1[17][20] = -1.52913469226192;
   fWeightMatrix0to1[18][20] = 1.10833158807806;
   fWeightMatrix0to1[19][20] = -1.68295460587907;
   fWeightMatrix0to1[20][20] = 0.0794861364877357;
   fWeightMatrix0to1[21][20] = -0.151856008866359;
   fWeightMatrix0to1[22][20] = 1.12678162803245;
   fWeightMatrix0to1[23][20] = -1.32945642060789;
   fWeightMatrix0to1[24][20] = 0.323918256393553;
   fWeightMatrix0to1[25][20] = -1.83981323310975;
   fWeightMatrix0to1[26][20] = 0.357337030684489;
   fWeightMatrix0to1[27][20] = 0.955532058685003;
   fWeightMatrix0to1[0][21] = 0.534222637461955;
   fWeightMatrix0to1[1][21] = -0.424035403694013;
   fWeightMatrix0to1[2][21] = -1.84868779431508;
   fWeightMatrix0to1[3][21] = 0.694906520949121;
   fWeightMatrix0to1[4][21] = -0.499858559976366;
   fWeightMatrix0to1[5][21] = 0.880442861631104;
   fWeightMatrix0to1[6][21] = -0.609134665550059;
   fWeightMatrix0to1[7][21] = -0.976422992659265;
   fWeightMatrix0to1[8][21] = 2.22376602805964;
   fWeightMatrix0to1[9][21] = -1.31204842281602;
   fWeightMatrix0to1[10][21] = -1.53589816816396;
   fWeightMatrix0to1[11][21] = -1.31076999615845;
   fWeightMatrix0to1[12][21] = 0.781246803284203;
   fWeightMatrix0to1[13][21] = 0.968983323236206;
   fWeightMatrix0to1[14][21] = 1.41145772392885;
   fWeightMatrix0to1[15][21] = -1.17394374055113;
   fWeightMatrix0to1[16][21] = 0.883488349914344;
   fWeightMatrix0to1[17][21] = 0.558712420014343;
   fWeightMatrix0to1[18][21] = -0.287444007586758;
   fWeightMatrix0to1[19][21] = -0.877294848575026;
   fWeightMatrix0to1[20][21] = -1.55171243878957;
   fWeightMatrix0to1[21][21] = -0.200427669348712;
   fWeightMatrix0to1[22][21] = -0.145491458117333;
   fWeightMatrix0to1[23][21] = 2.4430137650597;
   fWeightMatrix0to1[24][21] = -0.465465289528965;
   fWeightMatrix0to1[25][21] = -0.131288664516289;
   fWeightMatrix0to1[26][21] = -0.814093911232938;
   fWeightMatrix0to1[27][21] = 0.223671415150915;
   fWeightMatrix0to1[0][22] = -0.0963679072645367;
   fWeightMatrix0to1[1][22] = 1.32823444422058;
   fWeightMatrix0to1[2][22] = -0.836980366054237;
   fWeightMatrix0to1[3][22] = -1.91358985413177;
   fWeightMatrix0to1[4][22] = 1.63281473967578;
   fWeightMatrix0to1[5][22] = 0.431743443033931;
   fWeightMatrix0to1[6][22] = 0.895677778209605;
   fWeightMatrix0to1[7][22] = -0.0882196056691904;
   fWeightMatrix0to1[8][22] = -0.812025484000276;
   fWeightMatrix0to1[9][22] = -0.867782511486817;
   fWeightMatrix0to1[10][22] = -1.53320559968738;
   fWeightMatrix0to1[11][22] = -0.0219661788249696;
   fWeightMatrix0to1[12][22] = -1.01220213345766;
   fWeightMatrix0to1[13][22] = -0.197417850932465;
   fWeightMatrix0to1[14][22] = 0.252829865184476;
   fWeightMatrix0to1[15][22] = -0.0887436599754524;
   fWeightMatrix0to1[16][22] = 1.35371307369422;
   fWeightMatrix0to1[17][22] = -1.9440607295205;
   fWeightMatrix0to1[18][22] = -1.56281256921021;
   fWeightMatrix0to1[19][22] = -0.412541397308997;
   fWeightMatrix0to1[20][22] = -1.28956410587974;
   fWeightMatrix0to1[21][22] = 0.636459869308716;
   fWeightMatrix0to1[22][22] = 1.40298967533323;
   fWeightMatrix0to1[23][22] = -1.24247687554256;
   fWeightMatrix0to1[24][22] = -0.240683187864669;
   fWeightMatrix0to1[25][22] = -1.40013888662721;
   fWeightMatrix0to1[26][22] = 1.0571142148175;
   fWeightMatrix0to1[27][22] = -1.17299616812439;
   fWeightMatrix0to1[0][23] = -1.45261982751623;
   fWeightMatrix0to1[1][23] = -1.05209879316884;
   fWeightMatrix0to1[2][23] = -1.52610913474748;
   fWeightMatrix0to1[3][23] = 2.10476765946437;
   fWeightMatrix0to1[4][23] = 0.0670250189619895;
   fWeightMatrix0to1[5][23] = 0.91733094245463;
   fWeightMatrix0to1[6][23] = 0.525743739964451;
   fWeightMatrix0to1[7][23] = -1.13947745584264;
   fWeightMatrix0to1[8][23] = -1.85591038937084;
   fWeightMatrix0to1[9][23] = -1.3936696036198;
   fWeightMatrix0to1[10][23] = 0.902544028382958;
   fWeightMatrix0to1[11][23] = 0.939517626429054;
   fWeightMatrix0to1[12][23] = 0.970038038852247;
   fWeightMatrix0to1[13][23] = -1.10369989614049;
   fWeightMatrix0to1[14][23] = 0.296365883646667;
   fWeightMatrix0to1[15][23] = -0.501779619988559;
   fWeightMatrix0to1[16][23] = -1.82856762354638;
   fWeightMatrix0to1[17][23] = 2.02059413025083;
   fWeightMatrix0to1[18][23] = -0.0507600603692453;
   fWeightMatrix0to1[19][23] = -1.25842433988739;
   fWeightMatrix0to1[20][23] = -1.11601401981684;
   fWeightMatrix0to1[21][23] = -1.77016587345604;
   fWeightMatrix0to1[22][23] = -0.00887803738633062;
   fWeightMatrix0to1[23][23] = 1.12013757836267;
   fWeightMatrix0to1[24][23] = 1.06990699440214;
   fWeightMatrix0to1[25][23] = 0.988349158106937;
   fWeightMatrix0to1[26][23] = -2.5648252944818;
   fWeightMatrix0to1[27][23] = -0.58983125606648;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.16775941562048;
   fWeightMatrix1to2[0][1] = -0.197880899523829;
   fWeightMatrix1to2[0][2] = 1.09498239828155;
   fWeightMatrix1to2[0][3] = -0.698476171675992;
   fWeightMatrix1to2[0][4] = 1.54998217534626;
   fWeightMatrix1to2[0][5] = -0.0317212246607951;
   fWeightMatrix1to2[0][6] = -0.197907540337581;
   fWeightMatrix1to2[0][7] = -1.79572232481941;
   fWeightMatrix1to2[0][8] = 0.51287243605003;
   fWeightMatrix1to2[0][9] = -0.0564319806152621;
   fWeightMatrix1to2[0][10] = 0.225567058109712;
   fWeightMatrix1to2[0][11] = -0.235067045400764;
   fWeightMatrix1to2[0][12] = -0.185182444644017;
   fWeightMatrix1to2[0][13] = 0.0618361065577788;
   fWeightMatrix1to2[0][14] = -0.293719452382899;
   fWeightMatrix1to2[0][15] = 0.110639225262914;
   fWeightMatrix1to2[0][16] = -1.59592340165605;
   fWeightMatrix1to2[0][17] = -1.57035610578724;
   fWeightMatrix1to2[0][18] = 0.13675508087321;
   fWeightMatrix1to2[0][19] = -0.173461377576404;
   fWeightMatrix1to2[0][20] = 0.349944390360685;
   fWeightMatrix1to2[0][21] = -0.101480385296857;
   fWeightMatrix1to2[0][22] = 0.093459404355339;
   fWeightMatrix1to2[0][23] = -0.13329011700589;
   fWeightMatrix1to2[0][24] = 0.0408528378211009;
   fWeightMatrix1to2[0][25] = 0.940627265041873;
   fWeightMatrix1to2[0][26] = -0.348052208134452;
   fWeightMatrix1to2[0][27] = 0.24560873649457;
   fWeightMatrix1to2[0][28] = 1.28151636303978;
}

inline double ReadMLPTuned::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPTuned::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPTuned::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPTuned::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPTuned::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 14;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 14;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 14;
   fMin_1[0][1] = 2;
   fMax_1[0][1] = 5;
   fMin_1[1][1] = 2;
   fMax_1[1][1] = 6;
   fMin_1[2][1] = 2;
   fMax_1[2][1] = 6;
   fMin_1[0][2] = 20.3211650848;
   fMax_1[0][2] = 779.356506348;
   fMin_1[1][2] = 20.345867157;
   fMax_1[1][2] = 1187.93493652;
   fMin_1[2][2] = 20.3211650848;
   fMax_1[2][2] = 1187.93493652;
   fMin_1[0][3] = 20.0031757355;
   fMax_1[0][3] = 557.967102051;
   fMin_1[1][3] = 20.0051765442;
   fMax_1[1][3] = 699.98260498;
   fMin_1[2][3] = 20.0031757355;
   fMax_1[2][3] = 699.98260498;
   fMin_1[0][4] = 31.5104141235;
   fMax_1[0][4] = 904.02545166;
   fMin_1[1][4] = 31.4223308563;
   fMax_1[1][4] = 686.358764648;
   fMin_1[2][4] = 31.4223308563;
   fMax_1[2][4] = 904.02545166;
   fMin_1[0][5] = 30.001663208;
   fMax_1[0][5] = 298.117797852;
   fMin_1[1][5] = 30.0022945404;
   fMax_1[1][5] = 239.681365967;
   fMin_1[2][5] = 30.001663208;
   fMax_1[2][5] = 298.117797852;
   fMin_1[0][6] = 20.0059547424;
   fMax_1[0][6] = 438.634124756;
   fMin_1[1][6] = 20.0106868744;
   fMax_1[1][6] = 480.95715332;
   fMin_1[2][6] = 20.0059547424;
   fMax_1[2][6] = 480.95715332;
   fMin_1[0][7] = 20.0082492828;
   fMax_1[0][7] = 524.356201172;
   fMin_1[1][7] = 20.003408432;
   fMax_1[1][7] = 625.883056641;
   fMin_1[2][7] = 20.003408432;
   fMax_1[2][7] = 625.883056641;
   fMin_1[0][8] = 0.267349809408;
   fMax_1[0][8] = 4.46294641495;
   fMin_1[1][8] = 0.31856662035;
   fMax_1[1][8] = 5.02747869492;
   fMin_1[2][8] = 0.267349809408;
   fMax_1[2][8] = 5.02747869492;
   fMin_1[0][9] = 0.410064458847;
   fMax_1[0][9] = 6.35713100433;
   fMin_1[1][9] = 0.460506469011;
   fMax_1[1][9] = 6.81951332092;
   fMin_1[2][9] = 0.410064458847;
   fMax_1[2][9] = 6.81951332092;
   fMin_1[0][10] = 0.548147320747;
   fMax_1[0][10] = 5.34395599365;
   fMin_1[1][10] = 0.631489932537;
   fMax_1[1][10] = 5.80796384811;
   fMin_1[2][10] = 0.548147320747;
   fMax_1[2][10] = 5.80796384811;
   fMin_1[0][11] = 0.345456838608;
   fMax_1[0][11] = 4.68913269043;
   fMin_1[1][11] = 0.331118583679;
   fMax_1[1][11] = 4.59567117691;
   fMin_1[2][11] = 0.331118583679;
   fMax_1[2][11] = 4.68913269043;
   fMin_1[0][12] = 0.382231384516;
   fMax_1[0][12] = 3.09887003899;
   fMin_1[1][12] = 0.399987101555;
   fMax_1[1][12] = 3.09979128838;
   fMin_1[2][12] = 0.382231384516;
   fMax_1[2][12] = 3.09979128838;
   fMin_1[0][13] = 0.304761111736;
   fMax_1[0][13] = 5.78525400162;
   fMin_1[1][13] = 0.343616694212;
   fMax_1[1][13] = 5.83795309067;
   fMin_1[2][13] = 0.304761111736;
   fMax_1[2][13] = 5.83795309067;
   fMin_1[0][14] = 0.0245936494321;
   fMax_1[0][14] = 6.85796403885;
   fMin_1[1][14] = 0.0342578701675;
   fMax_1[1][14] = 7.59379291534;
   fMin_1[2][14] = 0.0245936494321;
   fMax_1[2][14] = 7.59379291534;
   fMin_1[0][15] = 0.07235570997;
   fMax_1[0][15] = 7.17004442215;
   fMin_1[1][15] = 0.0183821171522;
   fMax_1[1][15] = 6.23720550537;
   fMin_1[2][15] = 0.0183821171522;
   fMax_1[2][15] = 7.17004442215;
   fMin_1[0][16] = 0.000293850898743;
   fMax_1[0][16] = 6.25128030777;
   fMin_1[1][16] = 9.36985015869e-05;
   fMax_1[1][16] = 6.25079774857;
   fMin_1[2][16] = 9.36985015869e-05;
   fMax_1[2][16] = 6.25128030777;
   fMin_1[0][17] = 60.0013084412;
   fMax_1[0][17] = 159.993743896;
   fMin_1[1][17] = 60.0244789124;
   fMax_1[1][17] = 159.999816895;
   fMin_1[2][17] = 60.0013084412;
   fMax_1[2][17] = 159.999816895;
   fMin_1[0][18] = 104.987121582;
   fMax_1[0][18] = 3156.22827148;
   fMin_1[1][18] = 110.601150513;
   fMax_1[1][18] = 4475.03857422;
   fMin_1[2][18] = 104.987121582;
   fMax_1[2][18] = 4475.03857422;
   fMin_1[0][19] = 42.1632194519;
   fMax_1[0][19] = 3031.91503906;
   fMin_1[1][19] = 44.5250282288;
   fMax_1[1][19] = 3519.41210938;
   fMin_1[2][19] = 42.1632194519;
   fMax_1[2][19] = 3519.41210938;
   fMin_1[0][20] = 86.4190216064;
   fMax_1[0][20] = 2917.90478516;
   fMin_1[1][20] = 88.8523406982;
   fMax_1[1][20] = 4438.00146484;
   fMin_1[2][20] = 86.4190216064;
   fMax_1[2][20] = 4438.00146484;
   fMin_1[0][21] = 0.0299043245614;
   fMax_1[0][21] = 460.327148438;
   fMin_1[1][21] = 0.00475058425218;
   fMax_1[1][21] = 535.521972656;
   fMin_1[2][21] = 0.00475058425218;
   fMax_1[2][21] = 535.521972656;
   fMin_1[0][22] = 0.00143084453885;
   fMax_1[0][22] = 1058.67456055;
   fMin_1[1][22] = 0.0021944725886;
   fMax_1[1][22] = 1580.10388184;
   fMin_1[2][22] = 0.00143084453885;
   fMax_1[2][22] = 1580.10388184;
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 23;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesGet.push_back( 14);
   indicesGet.push_back( 15);
   indicesGet.push_back( 16);
   indicesGet.push_back( 17);
   indicesGet.push_back( 18);
   indicesGet.push_back( 19);
   indicesGet.push_back( 20);
   indicesGet.push_back( 21);
   indicesGet.push_back( 22);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);
   indicesPut.push_back( 14);
   indicesPut.push_back( 15);
   indicesPut.push_back( 16);
   indicesPut.push_back( 17);
   indicesPut.push_back( 18);
   indicesPut.push_back( 19);
   indicesPut.push_back( 20);
   indicesPut.push_back( 21);
   indicesPut.push_back( 22);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<23;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
