// Class: ReadMLPTuned
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPTuned
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : ineuteli
Date           : Thu Nov 19 14:07:16 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.11.2.el6.x86_64 #1 SMP Wed Mar 26 09:39:43 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/ineuteli/phase2/CMSSW_5_3_24/src/Delphes/plots
Training events: 21448
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
HiddenLayers: "N+10" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
NCycles: "500" [Number of training cycles]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                                                      'F'    [0.354870975018,4.48389148712]
DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                                                      'F'    [0.295089483261,4.92900371552]
DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                                                      'F'    [0.290729790926,5.16654682159]
M_bb_closest                  M_bb_closest                  M_bb_closest                  M_bb_closest                                                    'F'    [8.52508640289,3205.42749023]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPTuned : public IClassifierReader {

 public:

   // constructor
   ReadMLPTuned( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPTuned" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "DeltaR_b1l", "DeltaR_bb1", "DeltaR_j1l", "M_bb_closest" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPTuned() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][4];
   double fMax_1[3][4];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[15][5];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][15];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPTuned::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 5; fWeights[0] = new double[5]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.981488989787872;
   fWeightMatrix0to1[1][0] = 1.94152545015027;
   fWeightMatrix0to1[2][0] = 0.120316634074181;
   fWeightMatrix0to1[3][0] = 1.73441134313271;
   fWeightMatrix0to1[4][0] = -1.6200434512847;
   fWeightMatrix0to1[5][0] = -1.36174033228644;
   fWeightMatrix0to1[6][0] = -2.3370162216698;
   fWeightMatrix0to1[7][0] = 0.0540379369974372;
   fWeightMatrix0to1[8][0] = -0.42759742217719;
   fWeightMatrix0to1[9][0] = -0.0127352882761452;
   fWeightMatrix0to1[10][0] = -1.50236334053095;
   fWeightMatrix0to1[11][0] = 0.645824713515585;
   fWeightMatrix0to1[12][0] = -0.534810147212261;
   fWeightMatrix0to1[13][0] = -0.00691712038122489;
   fWeightMatrix0to1[0][1] = -0.612185567084103;
   fWeightMatrix0to1[1][1] = 0.177950638008599;
   fWeightMatrix0to1[2][1] = 0.174444301267201;
   fWeightMatrix0to1[3][1] = 1.62149786496739;
   fWeightMatrix0to1[4][1] = 0.473123367794825;
   fWeightMatrix0to1[5][1] = 3.96488020362197;
   fWeightMatrix0to1[6][1] = 0.513880361968204;
   fWeightMatrix0to1[7][1] = -0.13563093846697;
   fWeightMatrix0to1[8][1] = 3.05741264492985;
   fWeightMatrix0to1[9][1] = 0.0795234892119787;
   fWeightMatrix0to1[10][1] = -0.630793455757893;
   fWeightMatrix0to1[11][1] = -3.82652957001571;
   fWeightMatrix0to1[12][1] = 1.1985236179127;
   fWeightMatrix0to1[13][1] = 0.227602920165905;
   fWeightMatrix0to1[0][2] = -3.56509023193009;
   fWeightMatrix0to1[1][2] = 0.312489823048672;
   fWeightMatrix0to1[2][2] = 0.2765220122359;
   fWeightMatrix0to1[3][2] = 1.68889021599349;
   fWeightMatrix0to1[4][2] = -0.0724544244118963;
   fWeightMatrix0to1[5][2] = 0.146984490921296;
   fWeightMatrix0to1[6][2] = -0.328223678585461;
   fWeightMatrix0to1[7][2] = -0.000518148839550051;
   fWeightMatrix0to1[8][2] = -0.784113073971266;
   fWeightMatrix0to1[9][2] = 0.590973611848334;
   fWeightMatrix0to1[10][2] = -1.14259498250149;
   fWeightMatrix0to1[11][2] = 0.962031471694967;
   fWeightMatrix0to1[12][2] = 1.24799577551874;
   fWeightMatrix0to1[13][2] = 0.229151157722541;
   fWeightMatrix0to1[0][3] = 1.40349677786122;
   fWeightMatrix0to1[1][3] = 0.906269542510673;
   fWeightMatrix0to1[2][3] = 0.233850939095039;
   fWeightMatrix0to1[3][3] = -1.31870681311524;
   fWeightMatrix0to1[4][3] = -1.19569406781364;
   fWeightMatrix0to1[5][3] = 1.27478809856409;
   fWeightMatrix0to1[6][3] = 2.12232282090465;
   fWeightMatrix0to1[7][3] = 1.21596549436969;
   fWeightMatrix0to1[8][3] = 5.40064597726091;
   fWeightMatrix0to1[9][3] = 0.201985627076062;
   fWeightMatrix0to1[10][3] = -1.96746159680751;
   fWeightMatrix0to1[11][3] = 2.38616866701033;
   fWeightMatrix0to1[12][3] = -1.46604099047703;
   fWeightMatrix0to1[13][3] = -0.965801385335813;
   fWeightMatrix0to1[0][4] = -1.41704145875985;
   fWeightMatrix0to1[1][4] = -2.3379958046539;
   fWeightMatrix0to1[2][4] = 0.451351528678143;
   fWeightMatrix0to1[3][4] = 1.01558554408188;
   fWeightMatrix0to1[4][4] = -2.54821668623287;
   fWeightMatrix0to1[5][4] = 2.45429203198984;
   fWeightMatrix0to1[6][4] = 0.832988037545445;
   fWeightMatrix0to1[7][4] = 1.11769069783578;
   fWeightMatrix0to1[8][4] = 7.07919838025396;
   fWeightMatrix0to1[9][4] = 0.6037475611448;
   fWeightMatrix0to1[10][4] = 1.05537022397518;
   fWeightMatrix0to1[11][4] = -0.214746516970422;
   fWeightMatrix0to1[12][4] = 0.000831057302170357;
   fWeightMatrix0to1[13][4] = -0.662583198666155;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.396119327980186;
   fWeightMatrix1to2[0][1] = -1.26052901729906;
   fWeightMatrix1to2[0][2] = 0.104858757912956;
   fWeightMatrix1to2[0][3] = -0.136966938094814;
   fWeightMatrix1to2[0][4] = 0.345926875628416;
   fWeightMatrix1to2[0][5] = -0.34469041260493;
   fWeightMatrix1to2[0][6] = -0.215968715458143;
   fWeightMatrix1to2[0][7] = -0.0383071469263646;
   fWeightMatrix1to2[0][8] = 1.23693745233167;
   fWeightMatrix1to2[0][9] = -0.0189045838673752;
   fWeightMatrix1to2[0][10] = 0.048226385467809;
   fWeightMatrix1to2[0][11] = 1.04275004834549;
   fWeightMatrix1to2[0][12] = 0.372121214902744;
   fWeightMatrix1to2[0][13] = 0.0312089559947291;
   fWeightMatrix1to2[0][14] = -0.708825006566252;
}

inline double ReadMLPTuned::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPTuned::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPTuned::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPTuned::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPTuned::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.354870975018;
   fMax_1[0][0] = 4.48140478134;
   fMin_1[1][0] = 0.376676082611;
   fMax_1[1][0] = 4.48389148712;
   fMin_1[2][0] = 0.354870975018;
   fMax_1[2][0] = 4.48389148712;
   fMin_1[0][1] = 0.295089483261;
   fMax_1[0][1] = 4.71407461166;
   fMin_1[1][1] = 0.331655144691;
   fMax_1[1][1] = 4.92900371552;
   fMin_1[2][1] = 0.295089483261;
   fMax_1[2][1] = 4.92900371552;
   fMin_1[0][2] = 0.290729790926;
   fMax_1[0][2] = 5.16654682159;
   fMin_1[1][2] = 0.32630905509;
   fMax_1[1][2] = 4.34218025208;
   fMin_1[2][2] = 0.290729790926;
   fMax_1[2][2] = 5.16654682159;
   fMin_1[0][3] = 8.52508640289;
   fMax_1[0][3] = 1460.97070312;
   fMin_1[1][3] = 12.8134212494;
   fMax_1[1][3] = 3205.42749023;
   fMin_1[2][3] = 8.52508640289;
   fMax_1[2][3] = 3205.42749023;
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 4;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<4;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
