// Class: ReadMLPTuned
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPTuned
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : ineuteli
Date           : Wed Nov 18 22:28:05 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.11.2.el6.x86_64 #1 SMP Wed Mar 26 09:39:43 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/ineuteli/phase2/CMSSW_5_3_24/src/Delphes/plots
Training events: 21448
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
HiddenLayers: "N+10" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
NCycles: "500" [Number of training cycles]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
bjet1Pt                       bjet1Pt                       bjet1Pt                       bjet1Pt                                                         'F'    [23.8701992035,1105.5402832]
jet1Pt                        jet1Pt                        jet1Pt                        jet1Pt                                                          'F'    [20.0867805481,1072.85205078]
DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                                                      'F'    [0.354870975018,4.48389148712]
DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                                                      'F'    [0.295089483261,4.92900371552]
DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                                                      'F'    [0.290729790926,5.16654682159]
DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                                                      'F'    [0.427045226097,457.230957031]
M_bb_closest                  M_bb_closest                  M_bb_closest                  M_bb_closest                                                    'F'    [8.52508640289,3205.42749023]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPTuned : public IClassifierReader {

 public:

   // constructor
   ReadMLPTuned( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPTuned" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "bjet1Pt", "jet1Pt", "DeltaR_b1l", "DeltaR_bb1", "DeltaR_j1l", "DeltaR_j2l", "M_bb_closest" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPTuned() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][7];
   double fMax_1[3][7];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[18][8];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][18];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPTuned::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 8; fWeights[0] = new double[8]; 
   fLayerSize[1] = 18; fWeights[1] = new double[18]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.0216537022918;
   fWeightMatrix0to1[1][0] = 1.59509225986118;
   fWeightMatrix0to1[2][0] = 6.58039109259591;
   fWeightMatrix0to1[3][0] = 2.58113880034008;
   fWeightMatrix0to1[4][0] = -1.97922798863975;
   fWeightMatrix0to1[5][0] = -0.882006826851111;
   fWeightMatrix0to1[6][0] = -1.3149842787344;
   fWeightMatrix0to1[7][0] = 0.542169189886007;
   fWeightMatrix0to1[8][0] = -0.670790165242724;
   fWeightMatrix0to1[9][0] = -0.168677937700818;
   fWeightMatrix0to1[10][0] = -2.96414726099201;
   fWeightMatrix0to1[11][0] = 0.775973018407325;
   fWeightMatrix0to1[12][0] = -3.07439051081731;
   fWeightMatrix0to1[13][0] = 1.05117838816276;
   fWeightMatrix0to1[14][0] = -0.908338962682858;
   fWeightMatrix0to1[15][0] = 0.942222715108977;
   fWeightMatrix0to1[16][0] = -0.349029253900765;
   fWeightMatrix0to1[0][1] = 1.10780008098506;
   fWeightMatrix0to1[1][1] = 0.290229661814217;
   fWeightMatrix0to1[2][1] = 0.425474551005279;
   fWeightMatrix0to1[3][1] = -0.00850158360855663;
   fWeightMatrix0to1[4][1] = -0.770633918589249;
   fWeightMatrix0to1[5][1] = 0.803873987257133;
   fWeightMatrix0to1[6][1] = -0.00755294815941699;
   fWeightMatrix0to1[7][1] = -1.65753332665304;
   fWeightMatrix0to1[8][1] = 0.720410141038749;
   fWeightMatrix0to1[9][1] = 1.26357609868629;
   fWeightMatrix0to1[10][1] = -0.998493772523792;
   fWeightMatrix0to1[11][1] = -1.16189840360392;
   fWeightMatrix0to1[12][1] = 0.022980786764248;
   fWeightMatrix0to1[13][1] = 0.734982042170556;
   fWeightMatrix0to1[14][1] = 1.73533098639814;
   fWeightMatrix0to1[15][1] = 0.128903902034007;
   fWeightMatrix0to1[16][1] = -0.563981719006438;
   fWeightMatrix0to1[0][2] = 0.333913189368656;
   fWeightMatrix0to1[1][2] = -0.356583822516119;
   fWeightMatrix0to1[2][2] = 0.466177795077408;
   fWeightMatrix0to1[3][2] = 2.08004102325206;
   fWeightMatrix0to1[4][2] = -1.23701780863172;
   fWeightMatrix0to1[5][2] = 0.0669253502623058;
   fWeightMatrix0to1[6][2] = 0.107578125217318;
   fWeightMatrix0to1[7][2] = 1.2915465300473;
   fWeightMatrix0to1[8][2] = 1.31565259103136;
   fWeightMatrix0to1[9][2] = 1.46306915886397;
   fWeightMatrix0to1[10][2] = -0.114821768154982;
   fWeightMatrix0to1[11][2] = -0.554157627473759;
   fWeightMatrix0to1[12][2] = 0.241111120269097;
   fWeightMatrix0to1[13][2] = -0.671391053902087;
   fWeightMatrix0to1[14][2] = 1.45310782192997;
   fWeightMatrix0to1[15][2] = 0.233704352487199;
   fWeightMatrix0to1[16][2] = 0.828184379223338;
   fWeightMatrix0to1[0][3] = -0.196296742108168;
   fWeightMatrix0to1[1][3] = -1.67592462966451;
   fWeightMatrix0to1[2][3] = 2.82829545246139;
   fWeightMatrix0to1[3][3] = -0.833949789083627;
   fWeightMatrix0to1[4][3] = -0.910723347555559;
   fWeightMatrix0to1[5][3] = 0.24463166043174;
   fWeightMatrix0to1[6][3] = -2.44435462890848;
   fWeightMatrix0to1[7][3] = 1.29665786543331;
   fWeightMatrix0to1[8][3] = 0.519299035596895;
   fWeightMatrix0to1[9][3] = -0.168329846193661;
   fWeightMatrix0to1[10][3] = 1.56873870763736;
   fWeightMatrix0to1[11][3] = -0.687270882277672;
   fWeightMatrix0to1[12][3] = 1.19790225789513;
   fWeightMatrix0to1[13][3] = 2.77132078069645;
   fWeightMatrix0to1[14][3] = -0.0968162894430467;
   fWeightMatrix0to1[15][3] = 0.208688034900384;
   fWeightMatrix0to1[16][3] = -1.27300700749225;
   fWeightMatrix0to1[0][4] = 0.950349131746001;
   fWeightMatrix0to1[1][4] = -0.546572002204968;
   fWeightMatrix0to1[2][4] = -0.403039659376312;
   fWeightMatrix0to1[3][4] = -0.451642069014112;
   fWeightMatrix0to1[4][4] = 0.710201432414824;
   fWeightMatrix0to1[5][4] = 0.398368465007325;
   fWeightMatrix0to1[6][4] = 0.169259680056108;
   fWeightMatrix0to1[7][4] = 0.332983258126651;
   fWeightMatrix0to1[8][4] = -2.39423828672036;
   fWeightMatrix0to1[9][4] = -2.96107002227978;
   fWeightMatrix0to1[10][4] = 0.944702947386027;
   fWeightMatrix0to1[11][4] = 0.754534603305832;
   fWeightMatrix0to1[12][4] = 3.18040197885613;
   fWeightMatrix0to1[13][4] = 0.271311574139409;
   fWeightMatrix0to1[14][4] = 0.501760517257614;
   fWeightMatrix0to1[15][4] = 0.0177302602298905;
   fWeightMatrix0to1[16][4] = -0.906352573218009;
   fWeightMatrix0to1[0][5] = -0.043529925039689;
   fWeightMatrix0to1[1][5] = 1.27760954773142;
   fWeightMatrix0to1[2][5] = -4.15920260974215;
   fWeightMatrix0to1[3][5] = -2.11379330126025;
   fWeightMatrix0to1[4][5] = -1.72056999474862;
   fWeightMatrix0to1[5][5] = 0.432959679179551;
   fWeightMatrix0to1[6][5] = -1.0365607702975;
   fWeightMatrix0to1[7][5] = 0.295871491086252;
   fWeightMatrix0to1[8][5] = -1.51017221529614;
   fWeightMatrix0to1[9][5] = -0.693010461638571;
   fWeightMatrix0to1[10][5] = 1.84568142020872;
   fWeightMatrix0to1[11][5] = -0.433838914765362;
   fWeightMatrix0to1[12][5] = -1.78567477953849;
   fWeightMatrix0to1[13][5] = -3.71832327979059;
   fWeightMatrix0to1[14][5] = -0.174567122623844;
   fWeightMatrix0to1[15][5] = -1.26928130553066;
   fWeightMatrix0to1[16][5] = -1.67095529660346;
   fWeightMatrix0to1[0][6] = 0.293747254814376;
   fWeightMatrix0to1[1][6] = 1.61759982385798;
   fWeightMatrix0to1[2][6] = -0.545418714011933;
   fWeightMatrix0to1[3][6] = 0.608202602403055;
   fWeightMatrix0to1[4][6] = -0.963087107919909;
   fWeightMatrix0to1[5][6] = -0.721507784097829;
   fWeightMatrix0to1[6][6] = 3.47442505421622;
   fWeightMatrix0to1[7][6] = 0.385725190598015;
   fWeightMatrix0to1[8][6] = -1.77267500341172;
   fWeightMatrix0to1[9][6] = 0.317314044511712;
   fWeightMatrix0to1[10][6] = 0.00139481155299762;
   fWeightMatrix0to1[11][6] = 0.625303380798325;
   fWeightMatrix0to1[12][6] = -0.168213881320564;
   fWeightMatrix0to1[13][6] = 4.71244907352161;
   fWeightMatrix0to1[14][6] = -0.0950763897418103;
   fWeightMatrix0to1[15][6] = -0.447184306858198;
   fWeightMatrix0to1[16][6] = 0.861973744283203;
   fWeightMatrix0to1[0][7] = -1.2415648709063;
   fWeightMatrix0to1[1][7] = -1.68943077085926;
   fWeightMatrix0to1[2][7] = 3.38867166447049;
   fWeightMatrix0to1[3][7] = 0.217838618555431;
   fWeightMatrix0to1[4][7] = 1.81324197779301;
   fWeightMatrix0to1[5][7] = 0.115256885201661;
   fWeightMatrix0to1[6][7] = 1.00802909851351;
   fWeightMatrix0to1[7][7] = 1.00325182187549;
   fWeightMatrix0to1[8][7] = 0.301920647169205;
   fWeightMatrix0to1[9][7] = -1.97915421198821;
   fWeightMatrix0to1[10][7] = 0.811097631251793;
   fWeightMatrix0to1[11][7] = -0.254038337252992;
   fWeightMatrix0to1[12][7] = -1.40703202298824;
   fWeightMatrix0to1[13][7] = 2.86078841464619;
   fWeightMatrix0to1[14][7] = -1.15275115689931;
   fWeightMatrix0to1[15][7] = -0.573621652766331;
   fWeightMatrix0to1[16][7] = 0.699018822475238;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.8988033608855;
   fWeightMatrix1to2[0][1] = -1.36748286103013;
   fWeightMatrix1to2[0][2] = 0.480220309482731;
   fWeightMatrix1to2[0][3] = 0.247161200706033;
   fWeightMatrix1to2[0][4] = 1.17973147004739;
   fWeightMatrix1to2[0][5] = -0.0959822669268509;
   fWeightMatrix1to2[0][6] = -0.524093632583713;
   fWeightMatrix1to2[0][7] = -0.283694077584305;
   fWeightMatrix1to2[0][8] = -1.42688967548811;
   fWeightMatrix1to2[0][9] = 0.232727775627617;
   fWeightMatrix1to2[0][10] = 0.439345272933095;
   fWeightMatrix1to2[0][11] = 0.2787323505144;
   fWeightMatrix1to2[0][12] = -0.212185236774947;
   fWeightMatrix1to2[0][13] = -0.509653932683372;
   fWeightMatrix1to2[0][14] = -0.646682761268224;
   fWeightMatrix1to2[0][15] = -0.112232483551853;
   fWeightMatrix1to2[0][16] = 1.42823355082889;
   fWeightMatrix1to2[0][17] = -0.977895930388643;
}

inline double ReadMLPTuned::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPTuned::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPTuned::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPTuned::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPTuned::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 23.8701992035;
   fMax_1[0][0] = 904.02545166;
   fMin_1[1][0] = 27.4655246735;
   fMax_1[1][0] = 1105.5402832;
   fMin_1[2][0] = 23.8701992035;
   fMax_1[2][0] = 1105.5402832;
   fMin_1[0][1] = 20.0867805481;
   fMax_1[0][1] = 724.193359375;
   fMin_1[1][1] = 21.6149330139;
   fMax_1[1][1] = 1072.85205078;
   fMin_1[2][1] = 20.0867805481;
   fMax_1[2][1] = 1072.85205078;
   fMin_1[0][2] = 0.354870975018;
   fMax_1[0][2] = 4.48140478134;
   fMin_1[1][2] = 0.376676082611;
   fMax_1[1][2] = 4.48389148712;
   fMin_1[2][2] = 0.354870975018;
   fMax_1[2][2] = 4.48389148712;
   fMin_1[0][3] = 0.295089483261;
   fMax_1[0][3] = 4.71407461166;
   fMin_1[1][3] = 0.331655144691;
   fMax_1[1][3] = 4.92900371552;
   fMin_1[2][3] = 0.295089483261;
   fMax_1[2][3] = 4.92900371552;
   fMin_1[0][4] = 0.290729790926;
   fMax_1[0][4] = 5.16654682159;
   fMin_1[1][4] = 0.32630905509;
   fMax_1[1][4] = 4.34218025208;
   fMin_1[2][4] = 0.290729790926;
   fMax_1[2][4] = 5.16654682159;
   fMin_1[0][5] = 0.427045226097;
   fMax_1[0][5] = 457.230957031;
   fMin_1[1][5] = 0.505508899689;
   fMax_1[1][5] = 339.015960693;
   fMin_1[2][5] = 0.427045226097;
   fMax_1[2][5] = 457.230957031;
   fMin_1[0][6] = 8.52508640289;
   fMax_1[0][6] = 1460.97070312;
   fMin_1[1][6] = 12.8134212494;
   fMax_1[1][6] = 3205.42749023;
   fMin_1[2][6] = 8.52508640289;
   fMax_1[2][6] = 3205.42749023;
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 7;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<7;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
