// Class: ReadMLPTuned
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPTuned
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : ineuteli
Date           : Thu Nov 19 13:53:27 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.11.2.el6.x86_64 #1 SMP Wed Mar 26 09:39:43 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/ineuteli/phase2/CMSSW_5_3_24/src/Delphes/plots
Training events: 21448
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
HiddenLayers: "N+10" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
NCycles: "500" [Number of training cycles]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
bjet1Pt                       bjet1Pt                       bjet1Pt                       bjet1Pt                                                         'F'    [23.8701992035,1105.5402832]
jet1Pt                        jet1Pt                        jet1Pt                        jet1Pt                                                          'F'    [20.0867805481,1072.85205078]
DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                                                      'F'    [0.354870975018,4.48389148712]
DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                                                      'F'    [0.423246353865,769.836181641]
M_bb_closest                  M_bb_closest                  M_bb_closest                  M_bb_closest                                                    'F'    [8.52508640289,3205.42749023]
DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                                                      'F'    [0.290729790926,5.16654682159]
DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                                                      'F'    [0.427045226097,457.230957031]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPTuned : public IClassifierReader {

 public:

   // constructor
   ReadMLPTuned( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPTuned" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "bjet1Pt", "jet1Pt", "DeltaR_b1l", "DeltaR_b2l", "M_bb_closest", "DeltaR_j1l", "DeltaR_j2l" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPTuned() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][7];
   double fMax_1[3][7];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[18][8];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][18];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPTuned::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 8; fWeights[0] = new double[8]; 
   fLayerSize[1] = 18; fWeights[1] = new double[18]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.44536297173887;
   fWeightMatrix0to1[1][0] = 3.15961418801032;
   fWeightMatrix0to1[2][0] = 0.750435863766635;
   fWeightMatrix0to1[3][0] = 3.46494293286888;
   fWeightMatrix0to1[4][0] = -2.0317545949095;
   fWeightMatrix0to1[5][0] = -1.54139173821533;
   fWeightMatrix0to1[6][0] = -1.12779815530299;
   fWeightMatrix0to1[7][0] = 1.38808366716447;
   fWeightMatrix0to1[8][0] = -0.353178278625545;
   fWeightMatrix0to1[9][0] = -0.184588896864679;
   fWeightMatrix0to1[10][0] = -3.21885999973033;
   fWeightMatrix0to1[11][0] = -0.0846011328493292;
   fWeightMatrix0to1[12][0] = -1.5784533251234;
   fWeightMatrix0to1[13][0] = -1.47517757727911;
   fWeightMatrix0to1[14][0] = -0.895563081995017;
   fWeightMatrix0to1[15][0] = 1.09491426238307;
   fWeightMatrix0to1[16][0] = -0.919561219850584;
   fWeightMatrix0to1[0][1] = 1.79425482471932;
   fWeightMatrix0to1[1][1] = 0.589274520686448;
   fWeightMatrix0to1[2][1] = 2.01140108634792;
   fWeightMatrix0to1[3][1] = -0.329651942414102;
   fWeightMatrix0to1[4][1] = -0.744176016369262;
   fWeightMatrix0to1[5][1] = 1.15471842861372;
   fWeightMatrix0to1[6][1] = 0.911164486758426;
   fWeightMatrix0to1[7][1] = -1.51169756563873;
   fWeightMatrix0to1[8][1] = -0.0439035543201124;
   fWeightMatrix0to1[9][1] = 0.677406066773464;
   fWeightMatrix0to1[10][1] = -0.166523245940987;
   fWeightMatrix0to1[11][1] = -1.181794355323;
   fWeightMatrix0to1[12][1] = 0.261299212107916;
   fWeightMatrix0to1[13][1] = 0.387301602816081;
   fWeightMatrix0to1[14][1] = 1.63846815444038;
   fWeightMatrix0to1[15][1] = -0.0709271992865728;
   fWeightMatrix0to1[16][1] = -0.51447838173907;
   fWeightMatrix0to1[0][2] = 0.230030195933309;
   fWeightMatrix0to1[1][2] = -0.313702441968336;
   fWeightMatrix0to1[2][2] = -1.17290389502717;
   fWeightMatrix0to1[3][2] = 1.10424017899648;
   fWeightMatrix0to1[4][2] = -1.19535857437057;
   fWeightMatrix0to1[5][2] = -0.294089476859628;
   fWeightMatrix0to1[6][2] = -0.161316440699849;
   fWeightMatrix0to1[7][2] = 0.229430011444109;
   fWeightMatrix0to1[8][2] = 1.50205861952694;
   fWeightMatrix0to1[9][2] = 0.00257752908016988;
   fWeightMatrix0to1[10][2] = -0.380885339150704;
   fWeightMatrix0to1[11][2] = -3.46013119814828;
   fWeightMatrix0to1[12][2] = 1.47826873169614;
   fWeightMatrix0to1[13][2] = 0.323002659833673;
   fWeightMatrix0to1[14][2] = 1.43859610403056;
   fWeightMatrix0to1[15][2] = 0.230830076726823;
   fWeightMatrix0to1[16][2] = 1.61341818817792;
   fWeightMatrix0to1[0][3] = 1.39027139060378;
   fWeightMatrix0to1[1][3] = -2.63944879495302;
   fWeightMatrix0to1[2][3] = 1.25541609167075;
   fWeightMatrix0to1[3][3] = -1.8056708598432;
   fWeightMatrix0to1[4][3] = -0.887512709460972;
   fWeightMatrix0to1[5][3] = -1.4475951352015;
   fWeightMatrix0to1[6][3] = -2.01211490964963;
   fWeightMatrix0to1[7][3] = 0.731123751688599;
   fWeightMatrix0to1[8][3] = 0.89741452596559;
   fWeightMatrix0to1[9][3] = -1.54920903665291;
   fWeightMatrix0to1[10][3] = 1.51766863517067;
   fWeightMatrix0to1[11][3] = 0.427993939632184;
   fWeightMatrix0to1[12][3] = -0.0947568125205151;
   fWeightMatrix0to1[13][3] = 1.3550645676605;
   fWeightMatrix0to1[14][3] = 0.0418573424565572;
   fWeightMatrix0to1[15][3] = 0.563727847884951;
   fWeightMatrix0to1[16][3] = -1.05665041753368;
   fWeightMatrix0to1[0][4] = 0.826651241520021;
   fWeightMatrix0to1[1][4] = -1.82204552961325;
   fWeightMatrix0to1[2][4] = -2.10184541024749;
   fWeightMatrix0to1[3][4] = -5.02206895293148;
   fWeightMatrix0to1[4][4] = 0.759876812712585;
   fWeightMatrix0to1[5][4] = 3.60780035387453;
   fWeightMatrix0to1[6][4] = 3.12893407391478;
   fWeightMatrix0to1[7][4] = -0.999772133010688;
   fWeightMatrix0to1[8][4] = -1.89858808280879;
   fWeightMatrix0to1[9][4] = -1.89618517859588;
   fWeightMatrix0to1[10][4] = 1.45017357553841;
   fWeightMatrix0to1[11][4] = 1.96767739193063;
   fWeightMatrix0to1[12][4] = 3.32360026338207;
   fWeightMatrix0to1[13][4] = 0.119066169783682;
   fWeightMatrix0to1[14][4] = 0.767313805260118;
   fWeightMatrix0to1[15][4] = -1.07469619801485;
   fWeightMatrix0to1[16][4] = -0.869049879478499;
   fWeightMatrix0to1[0][5] = -0.207003115417002;
   fWeightMatrix0to1[1][5] = -0.147252807850313;
   fWeightMatrix0to1[2][5] = -0.856320012970172;
   fWeightMatrix0to1[3][5] = -3.48386930108779;
   fWeightMatrix0to1[4][5] = -1.67496528512663;
   fWeightMatrix0to1[5][5] = -0.17103202799557;
   fWeightMatrix0to1[6][5] = -0.0526271443122666;
   fWeightMatrix0to1[7][5] = 0.911125972219778;
   fWeightMatrix0to1[8][5] = -1.88448498321688;
   fWeightMatrix0to1[9][5] = -0.127285422291744;
   fWeightMatrix0to1[10][5] = 0.909592458762543;
   fWeightMatrix0to1[11][5] = -0.188175784037251;
   fWeightMatrix0to1[12][5] = -1.06569167776133;
   fWeightMatrix0to1[13][5] = -0.530111582784325;
   fWeightMatrix0to1[14][5] = -0.101953223548878;
   fWeightMatrix0to1[15][5] = -0.149228999065961;
   fWeightMatrix0to1[16][5] = -1.46185587924349;
   fWeightMatrix0to1[0][6] = 0.643498841900549;
   fWeightMatrix0to1[1][6] = 1.3867122495141;
   fWeightMatrix0to1[2][6] = -0.739116724148952;
   fWeightMatrix0to1[3][6] = 3.35574765530796;
   fWeightMatrix0to1[4][6] = -0.931079020916555;
   fWeightMatrix0to1[5][6] = -0.752368505753009;
   fWeightMatrix0to1[6][6] = -0.219940095654956;
   fWeightMatrix0to1[7][6] = -0.370527436921089;
   fWeightMatrix0to1[8][6] = -1.29178227183974;
   fWeightMatrix0to1[9][6] = 0.297085608602689;
   fWeightMatrix0to1[10][6] = 0.509196219439177;
   fWeightMatrix0to1[11][6] = 0.392394284606932;
   fWeightMatrix0to1[12][6] = -2.6471155509865;
   fWeightMatrix0to1[13][6] = 1.32008592823126;
   fWeightMatrix0to1[14][6] = 0.529902742094226;
   fWeightMatrix0to1[15][6] = -0.509857829683315;
   fWeightMatrix0to1[16][6] = 0.7501254333199;
   fWeightMatrix0to1[0][7] = -1.08974865431854;
   fWeightMatrix0to1[1][7] = -0.85986168818259;
   fWeightMatrix0to1[2][7] = -0.359063307663459;
   fWeightMatrix0to1[3][7] = -2.98329054106999;
   fWeightMatrix0to1[4][7] = 1.78091095541845;
   fWeightMatrix0to1[5][7] = 0.791537156093635;
   fWeightMatrix0to1[6][7] = 0.559193760178278;
   fWeightMatrix0to1[7][7] = 0.351410337300277;
   fWeightMatrix0to1[8][7] = 0.0034375717200128;
   fWeightMatrix0to1[9][7] = -1.98363219496581;
   fWeightMatrix0to1[10][7] = 0.863578798945012;
   fWeightMatrix0to1[11][7] = 0.375793284552968;
   fWeightMatrix0to1[12][7] = -0.542091737081373;
   fWeightMatrix0to1[13][7] = 1.11200823224307;
   fWeightMatrix0to1[14][7] = -1.55777271482805;
   fWeightMatrix0to1[15][7] = -0.385892864193111;
   fWeightMatrix0to1[16][7] = 1.21784583763346;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.98862627166937;
   fWeightMatrix1to2[0][1] = -0.614133131998275;
   fWeightMatrix1to2[0][2] = 0.316645227375265;
   fWeightMatrix1to2[0][3] = 0.315692615538112;
   fWeightMatrix1to2[0][4] = 1.40447465206936;
   fWeightMatrix1to2[0][5] = -0.341580426567744;
   fWeightMatrix1to2[0][6] = -0.167550599830367;
   fWeightMatrix1to2[0][7] = -0.14843895151696;
   fWeightMatrix1to2[0][8] = -0.537425509698401;
   fWeightMatrix1to2[0][9] = -0.328205158815481;
   fWeightMatrix1to2[0][10] = -0.421852413655444;
   fWeightMatrix1to2[0][11] = -0.246537414479742;
   fWeightMatrix1to2[0][12] = -0.252177183438675;
   fWeightMatrix1to2[0][13] = -0.366025397636556;
   fWeightMatrix1to2[0][14] = -0.762229529723997;
   fWeightMatrix1to2[0][15] = -0.449993431473793;
   fWeightMatrix1to2[0][16] = 1.43945643012881;
   fWeightMatrix1to2[0][17] = -0.770626352379336;
}

inline double ReadMLPTuned::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPTuned::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPTuned::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPTuned::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPTuned::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 23.8701992035;
   fMax_1[0][0] = 904.02545166;
   fMin_1[1][0] = 27.4655246735;
   fMax_1[1][0] = 1105.5402832;
   fMin_1[2][0] = 23.8701992035;
   fMax_1[2][0] = 1105.5402832;
   fMin_1[0][1] = 20.0867805481;
   fMax_1[0][1] = 724.193359375;
   fMin_1[1][1] = 21.6149330139;
   fMax_1[1][1] = 1072.85205078;
   fMin_1[2][1] = 20.0867805481;
   fMax_1[2][1] = 1072.85205078;
   fMin_1[0][2] = 0.354870975018;
   fMax_1[0][2] = 4.48140478134;
   fMin_1[1][2] = 0.376676082611;
   fMax_1[1][2] = 4.48389148712;
   fMin_1[2][2] = 0.354870975018;
   fMax_1[2][2] = 4.48389148712;
   fMin_1[0][3] = 0.548147320747;
   fMax_1[0][3] = 769.836181641;
   fMin_1[1][3] = 0.423246353865;
   fMax_1[1][3] = 631.76385498;
   fMin_1[2][3] = 0.423246353865;
   fMax_1[2][3] = 769.836181641;
   fMin_1[0][4] = 8.52508640289;
   fMax_1[0][4] = 1460.97070312;
   fMin_1[1][4] = 12.8134212494;
   fMax_1[1][4] = 3205.42749023;
   fMin_1[2][4] = 8.52508640289;
   fMax_1[2][4] = 3205.42749023;
   fMin_1[0][5] = 0.290729790926;
   fMax_1[0][5] = 5.16654682159;
   fMin_1[1][5] = 0.32630905509;
   fMax_1[1][5] = 4.34218025208;
   fMin_1[2][5] = 0.290729790926;
   fMax_1[2][5] = 5.16654682159;
   fMin_1[0][6] = 0.427045226097;
   fMax_1[0][6] = 457.230957031;
   fMin_1[1][6] = 0.505508899689;
   fMax_1[1][6] = 339.015960693;
   fMin_1[2][6] = 0.427045226097;
   fMax_1[2][6] = 457.230957031;
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 7;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<7;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
