// Class: ReadMLPTuned
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPTuned
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : ineuteli
Date           : Thu Nov 26 21:58:24 2015
Host           : Linux cmsdev02.cern.ch 2.6.32-431.11.2.el6.x86_64 #1 SMP Wed Mar 26 09:39:43 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /shome/ineuteli/phase2/CMSSW_5_3_24/src/Delphes/plots
Training events: 20731
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
HiddenLayers: "N+10" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
NCycles: "500" [Number of training cycles]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                    DeltaR_b1l                                                      'F'    [0.514531254768,5.3588013649]
DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                    DeltaR_b2l                                                      'F'    [0.331118583679,4.68913269043]
DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                    DeltaR_bb1                                                      'F'    [0.383479446173,3.09936523438]
DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                    DeltaR_j1l                                                      'F'    [0.267349809408,5.96390295029]
DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                    DeltaR_j2l                                                      'F'    [0.411826014519,6.17678260803]
M_bb_closest                  M_bb_closest                  M_bb_closest                  M_bb_closest                                                    'F'    [60.0008811951,159.999816895]
M_jjb_leading                 M_jjb_leading                 M_jjb_leading                 M_jjb_leading                                                   'F'    [35.0392456055,3519.41210938]
M_blnu                        M_blnu                        M_blnu                        M_blnu                                                          'F'    [87.2848510742,4438.00146484]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPTuned : public IClassifierReader {

 public:

   // constructor
   ReadMLPTuned( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPTuned" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "DeltaR_b1l", "DeltaR_b2l", "DeltaR_bb1", "DeltaR_j1l", "DeltaR_j2l", "M_bb_closest", "M_jjb_leading", "M_blnu" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPTuned() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[19][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][19];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPTuned::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 19; fWeights[1] = new double[19]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.45705752973598;
   fWeightMatrix0to1[1][0] = 0.767286959782762;
   fWeightMatrix0to1[2][0] = 1.01158520912979;
   fWeightMatrix0to1[3][0] = 0.900136753631048;
   fWeightMatrix0to1[4][0] = -1.1124408849019;
   fWeightMatrix0to1[5][0] = -0.931765556822478;
   fWeightMatrix0to1[6][0] = -1.44739097626141;
   fWeightMatrix0to1[7][0] = 0.705497250582323;
   fWeightMatrix0to1[8][0] = 0.513601690591902;
   fWeightMatrix0to1[9][0] = 0.150588803097578;
   fWeightMatrix0to1[10][0] = -1.23076076771288;
   fWeightMatrix0to1[11][0] = -0.480272495358847;
   fWeightMatrix0to1[12][0] = -1.42600047012726;
   fWeightMatrix0to1[13][0] = -0.691907583917005;
   fWeightMatrix0to1[14][0] = 0.0946975533552594;
   fWeightMatrix0to1[15][0] = 0.500845472484126;
   fWeightMatrix0to1[16][0] = 0.423769408713413;
   fWeightMatrix0to1[17][0] = 0.885717817127721;
   fWeightMatrix0to1[0][1] = 1.20674539858863;
   fWeightMatrix0to1[1][1] = 0.0355044445038282;
   fWeightMatrix0to1[2][1] = -0.178325321314227;
   fWeightMatrix0to1[3][1] = -0.14425097757051;
   fWeightMatrix0to1[4][1] = 0.358667517901958;
   fWeightMatrix0to1[5][1] = -0.084975753569499;
   fWeightMatrix0to1[6][1] = -0.184003486108751;
   fWeightMatrix0to1[7][1] = -0.19661229749496;
   fWeightMatrix0to1[8][1] = -0.31522090886885;
   fWeightMatrix0to1[9][1] = -0.39186623630042;
   fWeightMatrix0to1[10][1] = -1.43706066807059;
   fWeightMatrix0to1[11][1] = 0.555623516869966;
   fWeightMatrix0to1[12][1] = -0.352628007803758;
   fWeightMatrix0to1[13][1] = 0.524601835053174;
   fWeightMatrix0to1[14][1] = 0.461933983569286;
   fWeightMatrix0to1[15][1] = 0.44237667777497;
   fWeightMatrix0to1[16][1] = 0.99588259448608;
   fWeightMatrix0to1[17][1] = -0.914868890953867;
   fWeightMatrix0to1[0][2] = -2.27169509473935;
   fWeightMatrix0to1[1][2] = 0.485234602382189;
   fWeightMatrix0to1[2][2] = -1.22363541230872;
   fWeightMatrix0to1[3][2] = 0.407004015887386;
   fWeightMatrix0to1[4][2] = 0.563773311415597;
   fWeightMatrix0to1[5][2] = 1.20024704939935;
   fWeightMatrix0to1[6][2] = 0.467195015568434;
   fWeightMatrix0to1[7][2] = -0.216427793523544;
   fWeightMatrix0to1[8][2] = -0.137472376459488;
   fWeightMatrix0to1[9][2] = -0.109631715760766;
   fWeightMatrix0to1[10][2] = 0.865344947715375;
   fWeightMatrix0to1[11][2] = -0.459657491996904;
   fWeightMatrix0to1[12][2] = 0.44636862357;
   fWeightMatrix0to1[13][2] = 0.133838825390719;
   fWeightMatrix0to1[14][2] = 1.63836102577238;
   fWeightMatrix0to1[15][2] = 0.90102605751453;
   fWeightMatrix0to1[16][2] = -1.76719360002085;
   fWeightMatrix0to1[17][2] = 0.703076846065728;
   fWeightMatrix0to1[0][3] = -1.43564153876539;
   fWeightMatrix0to1[1][3] = -0.659639753640575;
   fWeightMatrix0to1[2][3] = -1.40251748721811;
   fWeightMatrix0to1[3][3] = -3.03055208401178;
   fWeightMatrix0to1[4][3] = 1.20169854679929;
   fWeightMatrix0to1[5][3] = 0.44452716834437;
   fWeightMatrix0to1[6][3] = -0.43925102866314;
   fWeightMatrix0to1[7][3] = 0.591929591760236;
   fWeightMatrix0to1[8][3] = -0.493248112170928;
   fWeightMatrix0to1[9][3] = 0.0153976431600397;
   fWeightMatrix0to1[10][3] = 0.913255911286189;
   fWeightMatrix0to1[11][3] = -0.2711046145923;
   fWeightMatrix0to1[12][3] = 0.258973007784307;
   fWeightMatrix0to1[13][3] = -0.493354026139981;
   fWeightMatrix0to1[14][3] = 0.0225170795085733;
   fWeightMatrix0to1[15][3] = -0.198610693938201;
   fWeightMatrix0to1[16][3] = -0.724573328158388;
   fWeightMatrix0to1[17][3] = -1.45852748310612;
   fWeightMatrix0to1[0][4] = 0.602175879977236;
   fWeightMatrix0to1[1][4] = 0.413111384102053;
   fWeightMatrix0to1[2][4] = 1.19638377526713;
   fWeightMatrix0to1[3][4] = -0.390935270173511;
   fWeightMatrix0to1[4][4] = -0.780704630390118;
   fWeightMatrix0to1[5][4] = -0.291535863989989;
   fWeightMatrix0to1[6][4] = 0.750786410398739;
   fWeightMatrix0to1[7][4] = 0.41579868824129;
   fWeightMatrix0to1[8][4] = 3.0236176441869;
   fWeightMatrix0to1[9][4] = -0.0832542182494681;
   fWeightMatrix0to1[10][4] = -0.147690299810613;
   fWeightMatrix0to1[11][4] = -0.0318206596847398;
   fWeightMatrix0to1[12][4] = -0.824193771560622;
   fWeightMatrix0to1[13][4] = 0.290900523438338;
   fWeightMatrix0to1[14][4] = 0.468652513249414;
   fWeightMatrix0to1[15][4] = -0.4322936400706;
   fWeightMatrix0to1[16][4] = -0.205530884363512;
   fWeightMatrix0to1[17][4] = -1.40650018745467;
   fWeightMatrix0to1[0][5] = 0.588578660857413;
   fWeightMatrix0to1[1][5] = -0.103068360042034;
   fWeightMatrix0to1[2][5] = 1.5234212666552;
   fWeightMatrix0to1[3][5] = -0.407185846001297;
   fWeightMatrix0to1[4][5] = -0.2827187052338;
   fWeightMatrix0to1[5][5] = 0.951440149554949;
   fWeightMatrix0to1[6][5] = -0.153931950818877;
   fWeightMatrix0to1[7][5] = -0.0912469254014277;
   fWeightMatrix0to1[8][5] = -0.308001517058138;
   fWeightMatrix0to1[9][5] = 0.0411006043664776;
   fWeightMatrix0to1[10][5] = -2.04675034211953;
   fWeightMatrix0to1[11][5] = -1.7677921310046;
   fWeightMatrix0to1[12][5] = 0.803894689392359;
   fWeightMatrix0to1[13][5] = -0.042549351814075;
   fWeightMatrix0to1[14][5] = -1.26986282129143;
   fWeightMatrix0to1[15][5] = 1.18952196046024;
   fWeightMatrix0to1[16][5] = -1.45576411603423;
   fWeightMatrix0to1[17][5] = -0.302154419582721;
   fWeightMatrix0to1[0][6] = -1.18957443854882;
   fWeightMatrix0to1[1][6] = 0.913911714554651;
   fWeightMatrix0to1[2][6] = -1.88051056255873;
   fWeightMatrix0to1[3][6] = 0.940527240691924;
   fWeightMatrix0to1[4][6] = -0.00617902730352556;
   fWeightMatrix0to1[5][6] = 0.019262996475832;
   fWeightMatrix0to1[6][6] = -2.00100320855074;
   fWeightMatrix0to1[7][6] = 1.81308955942608;
   fWeightMatrix0to1[8][6] = 0.76989174285125;
   fWeightMatrix0to1[9][6] = -1.21486846568933;
   fWeightMatrix0to1[10][6] = 0.07956418231655;
   fWeightMatrix0to1[11][6] = -0.48853009959937;
   fWeightMatrix0to1[12][6] = -0.877842677194036;
   fWeightMatrix0to1[13][6] = -0.112860681689403;
   fWeightMatrix0to1[14][6] = -0.4760651974578;
   fWeightMatrix0to1[15][6] = 0.753980781050366;
   fWeightMatrix0to1[16][6] = -0.127377723525804;
   fWeightMatrix0to1[17][6] = -0.604882694367286;
   fWeightMatrix0to1[0][7] = 0.498060219005258;
   fWeightMatrix0to1[1][7] = 0.57870437487765;
   fWeightMatrix0to1[2][7] = -1.83863214088447;
   fWeightMatrix0to1[3][7] = 1.46087928642687;
   fWeightMatrix0to1[4][7] = -0.335299781807671;
   fWeightMatrix0to1[5][7] = -0.625398615486399;
   fWeightMatrix0to1[6][7] = 1.07259787228477;
   fWeightMatrix0to1[7][7] = -1.46211540208019;
   fWeightMatrix0to1[8][7] = 0.609047499784048;
   fWeightMatrix0to1[9][7] = 1.01323089716555;
   fWeightMatrix0to1[10][7] = 0.986902809667527;
   fWeightMatrix0to1[11][7] = -0.920100320436174;
   fWeightMatrix0to1[12][7] = -0.201130164533662;
   fWeightMatrix0to1[13][7] = 1.05599755407003;
   fWeightMatrix0to1[14][7] = 1.0780871512744;
   fWeightMatrix0to1[15][7] = -1.14607343669356;
   fWeightMatrix0to1[16][7] = -0.39032855686121;
   fWeightMatrix0to1[17][7] = -0.869287384096753;
   fWeightMatrix0to1[0][8] = -1.40381402817701;
   fWeightMatrix0to1[1][8] = 1.12499642216576;
   fWeightMatrix0to1[2][8] = 1.21439777446923;
   fWeightMatrix0to1[3][8] = -0.777352634915292;
   fWeightMatrix0to1[4][8] = 0.159567492854859;
   fWeightMatrix0to1[5][8] = 0.388023004906414;
   fWeightMatrix0to1[6][8] = -1.27911229554398;
   fWeightMatrix0to1[7][8] = 0.440504855692966;
   fWeightMatrix0to1[8][8] = 1.12465654540368;
   fWeightMatrix0to1[9][8] = -0.148309805038909;
   fWeightMatrix0to1[10][8] = 0.401379997034024;
   fWeightMatrix0to1[11][8] = 0.0248076605306797;
   fWeightMatrix0to1[12][8] = 1.88475655223264;
   fWeightMatrix0to1[13][8] = 0.90688924938022;
   fWeightMatrix0to1[14][8] = 1.18932453234313;
   fWeightMatrix0to1[15][8] = -0.519761793912261;
   fWeightMatrix0to1[16][8] = 1.94493235569864;
   fWeightMatrix0to1[17][8] = 1.71504531625676;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.174234523427498;
   fWeightMatrix1to2[0][1] = 0.212605753350678;
   fWeightMatrix1to2[0][2] = 1.26647814337368;
   fWeightMatrix1to2[0][3] = 0.29847459062141;
   fWeightMatrix1to2[0][4] = 0.187373984664264;
   fWeightMatrix1to2[0][5] = 0.32135113399463;
   fWeightMatrix1to2[0][6] = -0.239461112889487;
   fWeightMatrix1to2[0][7] = -0.256506773311549;
   fWeightMatrix1to2[0][8] = 0.266372781506135;
   fWeightMatrix1to2[0][9] = 0.0115637256873079;
   fWeightMatrix1to2[0][10] = -0.18249635602496;
   fWeightMatrix1to2[0][11] = 0.471012304427252;
   fWeightMatrix1to2[0][12] = 1.32931118990514;
   fWeightMatrix1to2[0][13] = -0.154305585062318;
   fWeightMatrix1to2[0][14] = -0.1950152925572;
   fWeightMatrix1to2[0][15] = -0.210289225306558;
   fWeightMatrix1to2[0][16] = -0.357139262222032;
   fWeightMatrix1to2[0][17] = -0.780238482336664;
   fWeightMatrix1to2[0][18] = -1.27201635550643;
}

inline double ReadMLPTuned::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPTuned::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPTuned::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPTuned::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPTuned::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.548147320747;
   fMax_1[0][0] = 5.12846136093;
   fMin_1[1][0] = 0.514531254768;
   fMax_1[1][0] = 5.3588013649;
   fMin_1[2][0] = 0.514531254768;
   fMax_1[2][0] = 5.3588013649;
   fMin_1[0][1] = 0.345456838608;
   fMax_1[0][1] = 4.68913269043;
   fMin_1[1][1] = 0.331118583679;
   fMax_1[1][1] = 4.59567117691;
   fMin_1[2][1] = 0.331118583679;
   fMax_1[2][1] = 4.68913269043;
   fMin_1[0][2] = 0.389083296061;
   fMax_1[0][2] = 3.09887003899;
   fMin_1[1][2] = 0.383479446173;
   fMax_1[1][2] = 3.09936523438;
   fMin_1[2][2] = 0.383479446173;
   fMax_1[2][2] = 3.09936523438;
   fMin_1[0][3] = 0.267349809408;
   fMax_1[0][3] = 5.96390295029;
   fMin_1[1][3] = 0.32699367404;
   fMax_1[1][3] = 4.57333946228;
   fMin_1[2][3] = 0.267349809408;
   fMax_1[2][3] = 5.96390295029;
   fMin_1[0][4] = 0.411826014519;
   fMax_1[0][4] = 6.17678260803;
   fMin_1[1][4] = 0.517152249813;
   fMax_1[1][4] = 5.48278474808;
   fMin_1[2][4] = 0.411826014519;
   fMax_1[2][4] = 6.17678260803;
   fMin_1[0][5] = 60.0008811951;
   fMax_1[0][5] = 159.889877319;
   fMin_1[1][5] = 60.0244789124;
   fMax_1[1][5] = 159.999816895;
   fMin_1[2][5] = 60.0008811951;
   fMax_1[2][5] = 159.999816895;
   fMin_1[0][6] = 35.0392456055;
   fMax_1[0][6] = 3031.91503906;
   fMin_1[1][6] = 40.3004264832;
   fMax_1[1][6] = 3519.41210938;
   fMin_1[2][6] = 35.0392456055;
   fMax_1[2][6] = 3519.41210938;
   fMin_1[0][7] = 87.2848510742;
   fMax_1[0][7] = 1635.71276855;
   fMin_1[1][7] = 89.7603530884;
   fMax_1[1][7] = 4438.00146484;
   fMin_1[2][7] = 87.2848510742;
   fMax_1[2][7] = 4438.00146484;
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPTuned::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPTuned::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
